### DISCUSSION TITLE
Standby cluster stanza behavior in patroni in kubernetes ?

### DISCUSSION THREAD

**Discussion by ganesh-karthick** [patroni/patroni#3136] [Q&A] [answered]
Hi,

On experimenting patroni [multi DC HA](https://patroni.readthedocs.io/en/latest/ha_multi_dc.html#asynchronous-replication) version 3.2.1 for [standby cluster](https://patroni.readthedocs.io/en/latest/standby_cluster.html) .  Is the below optimized setup possible ?

### Normal scenario ###

1.  Clear any previous DCS config by doing ```patronictl remove cluster```
2.  Bootstrapping PG via pg basebackup 
3. Starting patroni afresh to bring up postgres. It comes in Leader/Running state 
4. Apply standby stanza via api or patronictl edit-config

```
  patronictl edit-config --force -s standby_cluster.host=192.168.6.60  -s standby_cluster.port=5432 -s standby_cluster.primary_slot_name=repslot -s standby_cluster.create_replica_methods='- basebackup'
```
5. It moves to standby leader stopped , runs rewind ,finally moves to standby leader streaming.

Could one optimize it to move directly to move state to standby leader post base backup?

### Optimized scenario ###

1.  Clear any previous DCS config by doing ```patronictl remove cluster```
2.  Bootstrapping PG via pg basebackup 
3. Edit patroni.yml to add standby stanza , ex config snippet

```
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    synchronous_mode: false
    slots:
      repslot:
        type: 'physical'
    standby_cluster:
      create_replica_methods:
      - basebackup
      host: 192.168.6.60
      port: 5432
      primary_slot_name: repslot
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_level: 'replica'
        hot_standby: 'on'
        synchronous_commit: 'local'
        wal_keep_segments: 960
        wal_compression: 'on'
        archive_mode: 'on'
        archive_command: '/bin/true'
        fsync: 'on'
 
```

4. Start patroni , so that DB directly moves to standby leader - streaming without intermediate leader transition.

In my testing despite the standby stanza being present in yaml , it does not seem to be  honoring it, it still moves to leader /running? Though the on edit-config it moves to intended state
