### DISCUSSION TITLE
Install Citus and Patroni

### DISCUSSION THREAD

**Discussion by northboys** [patroni/patroni#3140] [General]
Is there a tutorial available for setting up Citus and Patroni natively (without Docker) on a Linux environment?

**Comment by CyberDem0n** [comment]
Have you read [the docs](https://patroni.readthedocs.io/en/latest/citus.html)?
It is only about installing Citus packages on every node and applying a small change to Patroni configs.

**Reply by northboys** [reply]
Should I install Citus according to the [documentation](https://docs.citusdata.com/en/v12.1/installation/multi_node_debian.html#steps-to-be-executed-on-all-nodes?) ?

**Reply by CyberDem0n** [reply]
exactly

**Reply by northboys** [reply]
Okay, thanks

**Reply by northboys** [reply]
I encountered issues during my initial installation. Could you help me determine if there's anything wrong with my configuration?

<img width="810" alt="image" src="https://github.com/user-attachments/assets/a3f6d222-2edd-4ead-aafc-e71f5b17ffbd">

```
scope: demo
name: citus-coordinator2
namespace: /service/

citus:
  group: 0   
  database: citus  

restapi:
  listen: 0.0.0.0:8008
  connect_address: 172.16.20.39:8008

etcd:
  hosts: 172.16.20.74:2379

bootstrap:
  method: initdb
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: false
    synchronous_mode_strict: false
    synchronous_node_count: 1
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters: 
        max_connections: 1000
        shared_buffers: 512MB

  initdb:
    - encoding: UTF8
    - locale: en_US.UTF-8
    - data-checksums

  pg_hba:
    - host replication replicator 127.0.0.1/32 md5
    - host all all 0.0.0.0/0 md5

postgresql:
  listen: 0.0.0.0:5432
  connect_address: 172.16.20.39:5432
  data_dir: /var/lib/postgresql/16/main
  bin_dir: /usr/lib/postgresql/16/bin
  config_dir: /etc/postgresql/16/main
  authentication:
    replication:
      username: replicator
      password: replicate
    superuser:
      username: postgres
      password: postgres
  parameters:
    unix_socket_directories: /var/run/postgresql

tags:
  nosync: false
  noloadbalance: false
  nofailover: false
  clonefrom: false
```
