### DISCUSSION TITLE
Patroni fails with TLS for REST API enabled

### DISCUSSION THREAD

**Discussion by Henchway** [patroni/patroni#3179] [Q&A] [answered]
Hello,

I'm going slightly crazy with this issue, once i set cafile, certfile and keyfile in the rest api configuration yaml, Patroni fails with an HTTP_REQUEST error.  

The error I'm experiencing once I enable these settings, this keeps repeating over and over again.
```
patroni1  | Exception in thread Thread-10 (process_request_thread):
patroni1  | Traceback (most recent call last):
patroni1  |   File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
patroni1  |     self.run()
patroni1  |   File "/usr/lib/python3.11/threading.py", line 975, in run
patroni1  |     self._target(*self._args, **self._kwargs)
patroni1  |   File "/patroni/api.py", line 1700, in process_request_thread
patroni1  |     request.do_handshake()
patroni1  |   File "/usr/lib/python3.11/ssl.py", line 1379, in do_handshake
patroni1  |     self._sslobj.do_handshake()
patroni1  | ssl.SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:992)
```

Yaml config:
```
restapi:
  listen: 127.0.0.1:8008
  cafile: /usr/local/share/ca-certificates/ca.crt
  certfile: /etc/ssl/certs/server.crt
  keyfile: /etc/ssl/private/server.key

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    synchronous_mode: true
    synchronous_standby_names: "*"
    postgresql:
      use_pg_rewind: true
      pg_hba:
        - host replication replicator 127.0.0.1/32 md5
        - host all all 0.0.0.0/0 md5
      parameters:
        shared_buffers: 4GB
        effective_cache_size: 12GB
        maintenance_work_mem: 1GB
        checkpoint_completion_target: 0.9
        wal_buffers: 16MB
        default_statistics_target: 100
        random_page_cost: 4
        effective_io_concurrency: 2
        work_mem: 20971kB
        huge_pages: off
        min_wal_size: 1GB # 1GB / 16MB
        max_wal_size: 4GB # 4 GB / 16MB
        max_worker_processes: 4
        max_parallel_workers_per_gather: 2
        max_parallel_workers: 4
        max_parallel_maintenance_workers: 2
        ssl: on
        ssl_ca_file: /usr/local/share/ca-certificates/ca.crt
        ssl_cert_file: /etc/ssl/certs/server.crt
        ssl_key_file: /etc/ssl/private/server.key
  initdb: # Note: It needs to be a list (some options need values, others are switches)
    - encoding: UTF8
    - data-checksums
postgresql:
  listen: 127.0.0.1:5432
  data_dir: data/postgresql0
  pgpass: /tmp/pgpass0
tags:
  noloadbalance: false
  clonefrom: false
  nosync: false
  nostream: false
```

Instead of the .crt and .key files, I also tested using .pem files.  The used certificates have the IP, as well as the fqdn in the alternative names.

The docker compose (for one node):
```yaml
version: '3.8'

services:
  etcd:
    image: ${PATRONI_IMAGE:-cns.dev.dkr.frequentis.frq/icm/icm-patroni:latest}
    restart: unless-stopped
    environment:
      ETCD_LISTEN_PEER_URLS: https://${CURRENT_NODE_IP}:2380, https://127.0.0.1:2380 # Note: This doesn't accept hostnames, only IPs
      ETCD_LISTEN_CLIENT_URLS: https://${CURRENT_NODE_IP}:2379,https://127.0.0.1:2379 # Note: This doesn't accept hostnames, only IPs
      ETCD_INITIAL_CLUSTER: etcd1=https://${NODE1_DNS}:2380,etcd2=https://${NODE2_DNS}:2380,etcd3=https://${NODE3_DNS}:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: icm-patroni
      ETCD_TRUSTED_CA_FILE: /usr/local/share/ca-certificates/ca.crt
      ETCD_PEER_TRUSTED_CA_FILE: /usr/local/share/ca-certificates/ca.crt
      ETCD_CERT_FILE: /etc/ssl/certs/server.crt
      ETCD_PEER_CERT_FILE: /etc/ssl/certs/server.crt
      ETCD_KEY_FILE: /etc/ssl/private/server.key
      ETCD_PEER_KEY_FILE: /etc/ssl/private/server.key
      # ETCD_CLIENT_CERT_AUTH: true
      # ETCD_PEER_CLIENT_CERT_AUTH: true
    container_name: etcd
    command: etcd --name etcd${NODE_NUMBER} --initial-advertise-peer-urls https://${CURRENT_NODE_IP}:2380 --advertise-client-urls https://${CURRENT_NODE_IP}:2379 # The ETCD names have to coincide with the cluster nodes configured in ETCD_INITIAL_CLUSTER
    network_mode: "host"
    volumes:
      - /opt/etcd_data:/home/postgres/etcd${NODE_NUMBER}.etcd
      - ./certs/server.crt:/etc/ssl/certs/server.crt:ro
      - ./certs/server.key:/etc/ssl/private/server.key:ro

  haproxy:
    image: ${PATRONI_IMAGE:-cns.dev.dkr.frequentis.frq/icm/icm-patroni:latest}
    restart: unless-stopped
    container_name: haproxy
    command: haproxy
    environment: &haproxy_env
      ETCDCTL_ENDPOINTS: https://${NODE1_DNS}:2379,https://${NODE2_DNS}:2379,https://${NODE3_DNS}:2379
      PATRONI_ETCD3_HOSTS: "'${NODE1_DNS}:2379','${NODE2_DNS}:2379','${NODE3_DNS}:2379'"
      PATRONI_SCOPE: icm-patroni
    network_mode: "host"


  patroni:
    image: ${PATRONI_IMAGE:-cns.dev.dkr.frequentis.frq/icm/icm-patroni:latest}
    restart: unless-stopped
    container_name: patroni${NODE_NUMBER}
    environment:
      <<: *haproxy_env
      PATRONI_NAME: patroni${NODE_NUMBER}
      PATRONI_ETCD3_CACERT: /usr/local/share/ca-certificates/ca.crt
      PATRONI_ETCD3_CERT: /etc/ssl/certs/server.crt
      PATRONI_ETCD3_KEY: /etc/ssl/private/server.key
      PATRONI_ETCD3_PROTOCOL: https
      PATRONI_LOGLEVEL: DEBUG
    network_mode: "host"
    volumes:
      - /opt/pg_data:/home/postgres/data
      - ./certs/server.crt:/etc/ssl/certs/server.crt:ro
      - ./certs/server.key:/etc/ssl/private/server.key:ro
      # - ./certs/server.pem:/etc/ssl/certs/server.pem:ro
      # - ./certs/key.pem:/etc/ssl/private/key.pem:ro
```

The Dockerfile is based on the provided example, but slightly adapted to add the root ca certificate :

```
## This Dockerfile is meant to aid in the building and debugging patroni whilst developing on your local machine
## It has all the necessary components to play/debug with a single node appliance, running etcd
ARG PG_MAJOR=16
ARG COMPRESS=false
ARG PGHOME=/home/postgres
ARG PGDATA=$PGHOME/data
ARG LC_ALL=C.UTF-8
ARG LANG=C.UTF-8

FROM postgres:$PG_MAJOR as builder

ARG PGHOME
ARG PGDATA
ARG LC_ALL
ARG LANG

ENV ETCDVERSION=3.3.13 CONFDVERSION=0.16.0

RUN set -ex \
    && export DEBIAN_FRONTEND=noninteractive \
    && echo 'APT::Install-Recommends "0";\nAPT::Install-Suggests "0";' > /etc/apt/apt.conf.d/01norecommend \
    && apt-get update -y \
    # postgres:10 is based on debian, which has the patroni package. We will install all required dependencies
    && apt-cache depends patroni | sed -n -e 's/.*Depends: \(python3-.\+\)$/\1/p' \
            | grep -Ev '^python3-(sphinx|etcd|consul|kazoo|kubernetes)' \
            | xargs apt-get install -y vim curl less jq locales haproxy sudo \
                            python3-etcd python3-kazoo python3-pip busybox \
                            net-tools iputils-ping dumb-init --fix-missing \
\
    # Cleanup all locales but en_US.UTF-8
    && find /usr/share/i18n/charmaps/ -type f ! -name UTF-8.gz -delete \
    && find /usr/share/i18n/locales/ -type f ! -name en_US ! -name en_GB ! -name i18n* ! -name iso14651_t1 ! -name iso14651_t1_common ! -name 'translit_*' -delete \
    && echo 'en_US.UTF-8 UTF-8' > /usr/share/i18n/SUPPORTED \
\
    # Make sure we have a en_US.UTF-8 locale available
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 \
\
    # haproxy dummy config
    && echo 'global\n        stats socket /run/haproxy/admin.sock mode 660 level admin' > /etc/haproxy/haproxy.cfg \
\
    # vim config
    && echo 'syntax on\nfiletype plugin indent on\nset mouse-=a\nautocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab' > /etc/vim/vimrc.local \
\
    # Prepare postgres/patroni/haproxy environment
    && mkdir -p "$PGHOME/.config/patroni" /patroni /run/haproxy \
    && ln -s ../../postgres0.yml "$PGHOME/.config/patroni/patronictl.yaml" \
    && ln -s /patronictl.py /usr/local/bin/patronictl \
    && sed -i "s|/var/lib/postgresql.*|$PGHOME:/bin/bash|" /etc/passwd \
    && chown -R postgres:postgres /var/log \
\
    # Download etcd
    && curl -sL "https://github.com/coreos/etcd/releases/download/v$ETCDVERSION/etcd-v$ETCDVERSION-linux-$(dpkg --print-architecture).tar.gz" \
            | tar xz -C /usr/local/bin --strip=1 --wildcards --no-anchored etcd etcdctl \
\
    && if [ $(dpkg --print-architecture) = 'arm64' ]; then \
        # Build confd
        apt-get install -y git make \
        && curl -sL https://go.dev/dl/go1.20.4.linux-arm64.tar.gz | tar xz -C /usr/local go \
        && export GOROOT=/usr/local/go && export PATH=$PATH:$GOROOT/bin \
        && git clone --recurse-submodules https://github.com/kelseyhightower/confd.git \
        && make -C confd \
        && cp confd/bin/confd /usr/local/bin/confd \
        && rm -rf /confd /usr/local/go; \
    else \
        # Download confd
        curl -sL "https://github.com/kelseyhightower/confd/releases/download/v$CONFDVERSION/confd-$CONFDVERSION-linux-$(dpkg --print-architecture)" \
            > /usr/local/bin/confd && chmod +x /usr/local/bin/confd; \
    fi \
\
    # Clean up all useless packages and some files
    && apt-get purge -y --allow-remove-essential python3-pip gzip bzip2 util-linux e2fsprogs \
                libmagic1 bsdmainutils login ncurses-bin libmagic-mgc e2fslibs bsdutils \
                exim4-config gnupg-agent dirmngr \
                git make \
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/* \
        /root/.cache \
        /var/cache/debconf/* \
        /etc/rc?.d \
        /etc/systemd \
        /docker-entrypoint* \
        /sbin/pam* \
        /sbin/swap* \
        /sbin/unix* \
        /usr/local/bin/gosu \
        /usr/sbin/[acgipr]* \
        /usr/sbin/*user* \
        /usr/share/doc* \
        /usr/share/man \
        /usr/share/info \
        /usr/share/i18n/locales/translit_hangul \
        /usr/share/locale/?? \
        /usr/share/locale/??_?? \
        /usr/share/postgresql/*/man \
        /usr/share/postgresql-common/pg_wrapper \
        /usr/share/vim/vim*/doc \
        /usr/share/vim/vim*/lang \
        /usr/share/vim/vim*/tutor \
#        /var/lib/dpkg/info/* \
    && find /usr/bin -xtype l -delete \
    && find /var/log -type f -exec truncate --size 0 {} \; \
    && find /usr/lib/python3/dist-packages -name '*test*' | xargs rm -fr \
    && find /lib/$(uname -m)-linux-gnu/security -type f ! -name pam_env.so ! -name pam_permit.so ! -name pam_unix.so -delete

# perform compression if it is necessary
ARG COMPRESS
RUN if [ "$COMPRESS" = "true" ]; then \
        set -ex \
        # Allow certain sudo commands from postgres
        && echo 'postgres ALL=(ALL) NOPASSWD: /bin/tar xpJf /a.tar.xz -C /, /bin/rm /a.tar.xz, /bin/ln -snf dash /bin/sh' >> /etc/sudoers \
        && ln -snf busybox /bin/sh \
        && arch=$(uname -m) \
        && darch=$(uname -m | sed 's/_/-/') \
        && files="/bin/sh /usr/bin/sudo /usr/lib/sudo/sudoers.so /lib/$arch-linux-gnu/security/pam_*.so" \
        && libs="$(ldd $files | awk '{print $3;}' | grep '^/' | sort -u) /lib/ld-linux-$darch.so.* /lib/$arch-linux-gnu/ld-linux-$darch.so.* /lib/$arch-linux-gnu/libnsl.so.* /lib/$arch-linux-gnu/libnss_compat.so.* /lib/$arch-linux-gnu/libnss_files.so.*" \
        && (echo /var/run $files $libs | tr ' ' '\n' && realpath $files $libs) | sort -u | sed 's/^\///' > /exclude \
        && find /etc/alternatives -xtype l -delete \
        && save_dirs="usr lib var bin sbin etc/ssl etc/init.d etc/alternatives etc/apt" \
        && XZ_OPT=-e9v tar -X /exclude -cpJf a.tar.xz $save_dirs \
        # we call "cat /exclude" to avoid including files from the $save_dirs that are also among
        # the exceptions listed in the /exclude, as "uniq -u" eliminates all non-unique lines.
        # By calling "cat /exclude" a second time we guarantee that there will be at least two lines
        # for each exception and therefore they will be excluded from the output passed to 'rm'.
        && /bin/busybox sh -c "(find $save_dirs -not -type d && cat /exclude /exclude && echo exclude) | sort | uniq -u | xargs /bin/busybox rm" \
        && /bin/busybox --install -s \
        && /bin/busybox sh -c "find $save_dirs -type d -depth -exec rmdir -p {} \; 2> /dev/null"; \
    else \
        /bin/busybox --install -s; \
    fi

FROM scratch
COPY --from=builder / /

LABEL maintainer="Alexander Kukushkin <akukushkin@microsoft.com>"

ARG PG_MAJOR
ARG COMPRESS
ARG PGHOME
ARG PGDATA
ARG LC_ALL
ARG LANG

ARG PGBIN=/usr/lib/postgresql/$PG_MAJOR/bin

ENV LC_ALL=$LC_ALL LANG=$LANG EDITOR=/usr/bin/editor
ENV PGDATA=$PGDATA PATH=$PATH:$PGBIN
ENV ETCDCTL_API=3

COPY rootca.crt /usr/local/share/ca-certificates/ca.crt
COPY patroni /patroni/
COPY extras/confd/conf.d/haproxy.toml /etc/confd/conf.d/
COPY extras/confd/templates/haproxy.tmpl /etc/confd/templates/
COPY patroni*.py docker/entrypoint.sh /
COPY postgres?.yml $PGHOME/

WORKDIR $PGHOME

RUN sed -i 's/env python/&3/' /patroni*.py \
    # "fix" patroni configs
    && sed -i 's/^  listen: 127.0.0.1/  listen: 0.0.0.0/' postgres?.yml \
    && sed -i "s|^\(  data_dir: \).*|\1$PGDATA|" postgres?.yml \
    && sed -i "s|^#\(  bin_dir: \).*|\1$PGBIN|" postgres?.yml \
    && sed -i 's/^  - encoding: UTF8/  - locale: en_US.UTF-8\n&/' postgres?.yml \
    && sed -i 's/^\(scope\|name\|etcd\|  host\|  authentication\|  connect_address\|  parameters\):/#&/' postgres?.yml \
    && sed -i 's/^    \(replication\|superuser\|rewind\|unix_socket_directories\|\(\(  \)\{0,1\}\(username\|password\)\)\):/#&/' postgres?.yml \
    && sed -i 's/^      parameters:/&\n        max_connections: 100/'  postgres?.yml \
    && sed -i 's/^      pg_hba:/&\n      - local all all trust/' postgres?.yml \
    && sed -i 's/^\(.*\) \(.*\) md5/\1 all md5/' postgres?.yml \
    && if [ "$COMPRESS" = "true" ]; then chmod u+s /usr/bin/sudo; fi \
    && chmod +s /bin/ping \
    && chown -R postgres:postgres "$PGHOME" /run /etc/haproxy \
    && chown -R 999:999 /usr/local/share/ca-certificates/ca.crt && chmod 644 /usr/local/share/ca-certificates/ca.crt \
    && openssl x509 -in /usr/local/share/ca-certificates/ca.crt -out /usr/local/share/ca-certificates/ca.pem -outform PEM \
    && cat /usr/local/share/ca-certificates/ca.crt >> /etc/ssl/certs/ca-certificates.crt \
    && update-ca-certificates

USER postgres

ENTRYPOINT ["/bin/sh", "/entrypoint.sh"]
```

entrypoint.sh has also been slightly adapted (hostname resolution & removed some of the cases which were not applicant to this setup):

```
#!/bin/sh

readonly PATRONI_SCOPE="${PATRONI_SCOPE:-batman}"
PATRONI_NAMESPACE="${PATRONI_NAMESPACE:-/service}"
readonly PATRONI_NAMESPACE="${PATRONI_NAMESPACE%/}"
DOCKER_IP=$(hostname -I | awk '{print $1}')

export DUMB_INIT_SETSID=0

case "$1" in
    haproxy)
        haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D
        set -- confd "-prefix=$PATRONI_NAMESPACE/$PATRONI_SCOPE" -interval=10 -backend
        while ! etcdctl member list 2> /dev/null; do
            sleep 1
        done
        set -- "$@" etcdv3
        while IFS='' read -r line; do
            set -- "$@" -node "$line"
        done <<-EOT
$(echo "$ETCDCTL_ENDPOINTS" | sed 's/,/\n/g')
EOT
        exec dumb-init "$@"
        ;;
    etcd)
        exec "$@" --auto-compaction-retention=1
        ;;
esac

## We start an etcd
if [ -z "$PATRONI_ETCD3_HOSTS" ] && [ -z "$PATRONI_ZOOKEEPER_HOSTS" ]; then
    export PATRONI_ETCD_URL="http://127.0.0.1:2379"
    etcd --data-dir /tmp/etcd.data -advertise-client-urls=$PATRONI_ETCD_URL -listen-client-urls=http://0.0.0.0:2379 > /var/log/etcd.log 2> /var/log/etcd.err &
fi

export PATRONI_SCOPE
export PATRONI_NAMESPACE
export PATRONI_NAME="${PATRONI_NAME:-$(hostname)}"
export PATRONI_RESTAPI_CONNECT_ADDRESS="$DOCKER_IP:8008"
export PATRONI_RESTAPI_LISTEN="0.0.0.0:8008"
export PATRONI_admin_PASSWORD="${PATRONI_admin_PASSWORD:-admin}"
export PATRONI_admin_OPTIONS="${PATRONI_admin_OPTIONS:-createdb, createrole}"
export PATRONI_POSTGRESQL_CONNECT_ADDRESS="$DOCKER_IP:5432"
export PATRONI_POSTGRESQL_LISTEN="0.0.0.0:5432"
export PATRONI_POSTGRESQL_DATA_DIR="${PATRONI_POSTGRESQL_DATA_DIR:-$PGDATA}"
export PATRONI_REPLICATION_USERNAME="${PATRONI_REPLICATION_USERNAME:-replicator}"
export PATRONI_REPLICATION_PASSWORD="${PATRONI_REPLICATION_PASSWORD:-replicate}"
export PATRONI_SUPERUSER_USERNAME="${PATRONI_SUPERUSER_USERNAME:-postgres}"
export PATRONI_SUPERUSER_PASSWORD="${PATRONI_SUPERUSER_PASSWORD:-postgres}"
export PATRONI_REPLICATION_SSLMODE="${PATRONI_REPLICATION_SSLMODE:-$PGSSLMODE}"
export PATRONI_REPLICATION_SSLKEY="${PATRONI_REPLICATION_SSLKEY:-$PGSSLKEY}"
export PATRONI_REPLICATION_SSLCERT="${PATRONI_REPLICATION_SSLCERT:-$PGSSLCERT}"
export PATRONI_REPLICATION_SSLROOTCERT="${PATRONI_REPLICATION_SSLROOTCERT:-$PGSSLROOTCERT}"
export PATRONI_SUPERUSER_SSLMODE="${PATRONI_SUPERUSER_SSLMODE:-$PGSSLMODE}"
export PATRONI_SUPERUSER_SSLKEY="${PATRONI_SUPERUSER_SSLKEY:-$PGSSLKEY}"
export PATRONI_SUPERUSER_SSLCERT="${PATRONI_SUPERUSER_SSLCERT:-$PGSSLCERT}"
export PATRONI_SUPERUSER_SSLROOTCERT="${PATRONI_SUPERUSER_SSLROOTCERT:-$PGSSLROOTCERT}"

exec dumb-init python3 /patroni.py postgres0.yml
```
Do you have any suggestion what else I could look at? The containers are able to access the REST API via https, as well as the :2379 endpoint is also working via HTTPS. Any help is greatly appreciated!

Best regards
Thomas
