### DISCUSSION TITLE
How to debug this LAG issue in Patronictl ?

### DISCUSSION THREAD

**Discussion by dotsinspace** [patroni/patroni#3200] [General]
Thank you for this sweet library. Love it.

Today morning i got query from my team that DB is not working proprely and behaviouing wierdly. for that to understand consider following code snippet. i am using prisma.

```
const CreateNewEntry = await DataBase.sometable({ 'data': {....} })

console.log('-----DATA Found', CreateNewEntry)

const SearchEntry = await DataBase.sometable({ where: { 'id': CreateNewEntry?.id } })

console.log('---DATA not found', SearchEntry)
```

Now i check the patroni for any lag.

![image](https://github.com/user-attachments/assets/a6318054-cbca-4235-8098-e08c287e9f3a)

But didn't found that much and even some queries are running and some are not. 

I just got one small server dedicated to this only (Patroni cluster).
32GB Ram
6vcpu

```
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    autovacuum_max_workers: 4
    autovacuum_vacuum_cost_limit: 2000
    effective_cache_size: 18GB
    maintenance_work_mem: 1GB
    max_connections: 1500
    shared_buffers: 6GB
    synchronous_commit: false
    work_mem: 16MB
  pg_hba:
  - local all all trust
  - host replication replicator all md5
  - host all all all md5
  use_pg_rewind: true
retry_timeout: 10
ttl: 30
```

this is my patroni config. Now i seriously don't know how to solve this BUG...
