### DISCUSSION TITLE
updating pg_hba

### DISCUSSION THREAD

**Discussion by shubhammakharia** [patroni/patroni#3347] [Q&A]
Hi; 
I wish to update pg_hba on an existing patroni (already bootstrapped cluster).
`  - host replication replication 127.0.0.1/32 md5`
1. Do we add new entry via patronictl edit-config or do we manually update file and then reload?
2. I tried to do edit-config; and it did not show me any block of pg_hba, probably because the pg_hba is a part of bootstrap config and not postgresql config.
3. anyhow i tried adding the config and heres current:
```
[root@scv-dbpoc-pgsql01b data]# patronictl  -c /etc/patroni/patroni.yml show-config
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_mode: true
    archive_timeout: 3600
    client_min_messages: warning
    work_mem: 16MB
  pg_hba:
  - host replication replication 127.0.0.1/32 md5
  use_pg_rewind: true
```
4. After saving the config, i still see no change on pg_hba or the client connection succeeding. 
```[root@scv-dbpoc-pgsql01b data]# cat pg_hba.conf
# Do not edit this file manually!
# It will be overwritten by Patroni!
local all all ident
host replication replication 10.1.8.0/24 md5
host replication replication 17.8.2.0/24 md5
host all all 10.0.0.0/8 md5
host all all 17.0.0.0/8 md5
host all all 100.96.0.0/12 md5
host all all 127.0.0.1/32 md5
host all all ::1/128 md5
```
