### ISSUE TITLE
Postgresql failed to start after deletion of postgresql.base.conf due to recursion

### ISSUE THREAD

**Issue by crztssr** [patroni/patroni#3080]
### What happened?

I've deleted postgresql.base.conf (since I've found that it had some leftover parameters I don't need anymore).
After this I've restarted the cluster and it won't start with following error:

`Jun 13 15:59:53 pghost.domainname patroni[161837]: 2024-06-13 12:59:53.759 GMT [161837] LOG:  configuration file recursion in "/etc/postgresql/14/main/postgresql.base.conf"
Jun 13 15:59:53 pghost.domainname patroni[161837]: 2024-06-13 12:59:53.760 GMT [161837] FATAL:  configuration file "/etc/postgresql/14/main/postgresql.conf" contains errors
`

I found out that it happened due to patroni default behaviour mentioned in [Patroni configuration page](https://patroni.readthedocs.io/en/latest/patroni_configuration.html#postgresql-parameters-controlled-by-patroni):

```
...
If there is no custom_conf nor postgresql.base.conf, the original postgresql.conf is renamed to postgresql.base.conf and used as the base configuration.
...
```

So I've got /etc/postgresql/15/main/postgresql.base.conf copied from /etc/postgresql/15/main/postgresql.conf, and since /etc/postgresql/15/main/postgresql.conf had 
`include 'postgresql.base.conf'`

I've got a recursion which prevented postgresql from start.

### How can we reproduce it (as minimally and precisely as possible)?

1) Make a backup of postgresql.base.conf on leader (be sure to replace version and cluster name with your values):
`mv /etc/postgresql/15/main/postgresql.base.conf /etc/postgresql/15/main/postgresql.base.conf_back_`date +%F`
2) Remove postgresql.base.conf on leader:
`rm /etc/postgresql/15/main/postgresql.base.conf`
3) Reload patroni cluster:
`patronictl -c /etc/patroni/patroni.yml reload <clustername>`
4) Check that both files now contains same include:
postgres@pghost ~ $ grep include /etc/postgresql/15/main/postgresql*.conf
/etc/postgresql/15/main/postgresql.conf:include 'postgresql.base.conf'
/etc/postgresql/15/main/postgresql.base.conf:include 'postgresql.base.conf'
5) Restart patroni and check the status or patroni.log:
```
pghost ~ # systemctl restart patroni
pghost ~ # systemctl status patroni
pghost ~ # tail -f /var/log/patroni/patroni.log
```

### What did you expect to happen?

I expect that patroni will remove _include 'postgresql.base.conf'_  from postgresql.base.conf when copying it from postgresql.conf

### Patroni/PostgreSQL/DCS version

-   Patroni version: patroni 3.2.2, patroni 3.3.0
-   PostgreSQL version: 14.10, 14.12, 15.*
-   DCS (and its version): etcd 3

### Patroni configuration file

```yaml
irrelevent in this case, I don't have custom_conf
```

### patronictl show-config

```yaml
postgresql:
  parameters:
    archive_command: /usr/local/bin/wal-g wal-push "%p" >> /var/log/postgresql/archive_command.log 2>&1
    archive_mode: 'on'
    archive_timeout: 60
    auto_explain.log_analyze: 'true'
    auto_explain.log_buffers: 'true'
    auto_explain.log_min_duration: 2s
    auto_explain.log_nested_statements: 'true'
    auto_explain.log_timing: 'true'
    auto_explain.log_triggers: 'true'
    autovacuum: 'on'
    autovacuum_analyze_scale_factor: '0.05'
    autovacuum_max_workers: 6
    autovacuum_naptime: 1
    autovacuum_vacuum_scale_factor: '0.01'
    checkpoint_completion_target: '0.9'
    datestyle: iso, dmy
    default_statistics_target: 100
    effective_cache_size: 150GB
    effective_io_concurrency: 200
    hot_standby: 'on'
    jit: 'off'
    listen_addresses: '*'
    log_autovacuum_min_duration: 1000
    log_checkpoints: 'on'
    log_connections: 'off'
    log_destination: csvlog,stderr
    log_directory: /var/lib/postgresql/log
    log_disconnections: 'off'
    log_error_verbosity: default
    log_filename: postgres-%Y-%m-%d.log
    log_line_prefix: '%m [%p] [%x] [%v]: user=%u,db=%d,app=%a,client=%h '
    log_lock_waits: 'on'
    log_min_duration_statement: 1000
    log_min_messages: WARNING
    log_rotation_age: 1d
    log_statement: none
    log_temp_files: 0
    logging_collector: 'on'
    maintenance_work_mem: 2GB
    max_connections: 505
    max_parallel_maintenance_workers: 4
    max_parallel_workers: 10
    max_parallel_workers_per_gather: 0
    max_wal_size: 4GB
    max_worker_processes: 10
    min_wal_size: 1GB
    password_encryption: md5
    pg_stat_statements.track: top
    pg_stat_statements.track_planning: 'on'
    port: 5432
    random_page_cost: '1.1'
    restore_command: /usr/local/bin/wal-g wal-fetch "%f" "%p" >> /var/log/postgresql/restore_command.log 2>&1
    session_preload_libraries: auto_explain
    shared_buffers: 50GB
    shared_preload_libraries: pg_stat_statements
    ssl: 'off'
    track_activities: 'on'
    track_activity_query_size: 2048
    track_counts: 'on'
    track_functions: pl
    track_io_timing: 'on'
    track_wal_io_timing: 'on'
    unix_socket_directories: /var/run/postgresql
    vacuum_cost_limit: 1000
    wal_buffers: 16MB
    wal_level: replica
    wal_log_hints: 'on'
    work_mem: 25954kB
  use_pg_rewind: 'true'
  use_slots: 'false'
retry_timeout: '10'
synchronous_mode: 'false'
synchronous_mode_strict: 'false'
ttl: '30'
```

### Patroni log files

```shell
Jun 13 15:59:53 pghost.domainname patroni[161837]: 2024-06-13 12:59:53.759 GMT [161837] LOG:  configuration file recursion in "/etc/postgresql/14/main/postgresql.base.conf"
Jun 13 15:59:53 pghost.domainname patroni[161837]: 2024-06-13 12:59:53.760 GMT [161837] FATAL:  configuration file "/etc/postgresql/14/main/postgresql.conf" contains errors
```

### PostgreSQL log files

```shell
Not presented since postgresql fails before startup
```

### Have you tried to use GitHub issue search?

- [X] Yes
