### ISSUE TITLE
ERROR:  replication slot "bar_psqldb04" does not exist

### ISSUE THREAD

**Issue by prime-minister-of-fun** [patroni/patroni#3090]
### What happened?

After a round of patching, secondary nodes stopped rejoining the primary as a replca.
Warning: the config is vaguely anonymized, so, some usernames and such might be inconsistent.

### How can we reproduce it (as minimally and precisely as possible)?

Use the config attached.  Install patroni and postgresql 15 from the Percona repositories onto RHEL8 VM.

### What did you expect to happen?

The replicas re-join the primary. 

### Patroni/PostgreSQL/DCS version

-   Patroni version:  percona-patroni-3.3.0-1.el8.x86_64 patroni 3.3.0
-   PostgreSQL version:  15  percona-postgresql15-server-15.7-1.el8.x86_64
-   DCS (and its version):  etcd  etcd-3.5.13-1.el8.x86_64

### Patroni configuration file

```yaml
scope: vcfs-dev4
namespace: /foo-dba-dev/
name: bar-psqldb04

restapi:
  listen: 0.0.0.0:8008
  #full domain required for tls!
  connect_address: bar-psqldb04.ssl.compatible.com:8008
  cafile: /etc/pki/tls/certs/ca.crt
  certfile: /etc/pki/tls/certs/host.crt
  keyfile: /etc/pki/tls/private/host.key
  authentication:
    username: my_patroni_user
    password: superseeecret_ssshhhh
# If you want to force the list of allowed IPs, use allowlist
#  allowlist:

ctl:
  insecure: true
  cafile: /etc/ssl/certs/ca-bundle.crt
  certfile: /etc/ssl/certs/host.crt
  keyfile: /etc/pki/tls/private/host.key

etcd3:
  protocol: https
  cacert: /etc/pki/tls/certs/ca.crt
  cert:  /etc/pki/tls/certs/host.crt
  key: /etc/pki/tls/private/host.key
  hosts:
   - bar-psqldb01.ssl.compatible.com:2379
   - bar-psqldb02.ssl.compatible.com:2379
   - bar-psqldb03.ssl.compatible.com:2379
   - bar-psqldb04.ssl.compatible.com:2379
   - bar-psqldb05.ssl.compatible.com:2379
bootstrap:
  dcs:
   ttl: 30
   loop_wait: 10
   retry_timeout: 10
   maximum_lag_on_failover: 1048576
   master_start_timeout: 300  #default
   postgresql:
    use_pg_rewind: false
    use_slots: true
    use_unix_socket_repl: false
    use_unix_socket: true
    #putting parameters here means every node in the cluster gets it
    parameters:
      wal_keep_segments: 30
      max_wal_senders: 10
      max_replication_slots: 10
      checkpoint_timeout: 30
      wal_level: logical
      hotstandby: on
      tcp_keepalives_interval: 10
      tcp_keepalives_count: 3
      tcp_keepalives_idle: 60

  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - locale: en_US.utf8
  - data-checksums
  users:
   repl_role:
    password: staqreas
    options:
    - replication
   rewind_role_dev:
    password: fringlistis
    options:
    - replication
   super_dooper:
    password: another_secret
    options:
    - superuser
    - createdb
    - createrole
postgresql:
  listen: "0.0.0.0,::1:5432"
  listen_addresses: "192.168.2.2,127.0.0.1,::1"
  connect_address: 192.168.2.2:5432
  bin_dir: "/usr/pgsql-15/bin"
  data_dir: '/var/lib/pgsql/15/mount/data'
  pgpass: /var/lib/pgsql/.pgpass
  use_pg_rewind: false
  use_unix_socket: true
  remove_data_directory_on_diverged_timelines: true
  pg_hba:
   - local replication repl_role,rewind_role_dev scram-sha-256
   - local postgres postgres peer
   - local postgres super_dooper scram-sha-256
   - hostnossl replication repl_role,rewind_role_dev 127.0.0.1/32 scram-sha-256
   - hostnossl replication repl_role,rewind_role_dev ::1/128 scram-sha-256
   - hostssl replication repl_role,rewind_role_dev 192.168.101.0/24 scram-sha-256
   - hostnossl  all  all  0.0.0.0/0 reject
authentication:
    replication:
      username: repl_role
      password: 8th_mystery
      sslmode: "require"
      sslkey: "/etc/pki/tls/private/postgresql.key"
      sslcert: "/etc/pki/tls/certs/postgresql.crt"
      sslrootcert: "/etc/pki/tls/certs/ca.crt"
      gssencmode: "disable"
      channel_binding: "disable"
      rewind:  # Has no effect on postgres 10 and lower
      username: rewind_user
      password: strongly_typed_password
      sslmode: "require"
      sslkey: "/etc/pki/tls/private/postgresql.key"
      sslcert: "/etc/pki/tls/certs/postgresqo.crt"
      sslrootcert: "/etc/pki/tls/certs/ca.crt"
      gssencmode: "disable"
      channel_binding: "disable"
    superuser:
      username: super_dooper
      password: another_mystery
      sslmode: "require"
      sslkey: "/etc/pki/tls/private/postgresql.key"
      sslcert: "/etc/pki/tls/certs/postgresql.crt"
      sslrootcert: "/etc/pki/tls/certs/ca.crt"
      gssencmode: "disable"
      channel_binding: "disable"
 create_replica_methods:
    - basebackup
    - pgbackrest
  pgbackrest:
    command: "/bin/pgbackrest --stanza=pg-dev --log-level-file=detail --delta restore"
    keep_data: True
    no_params: True
  basebackup:
    max-rate: "100M"
  recovery_conf:
    recovery_target_timeline: latest
    restore_command: "/bin/pgbackrest --stanza=pg-dev archive-get %f %p"
  parameters:
    archive_mode: 'on'
    archive_command: /bin/pgbackrest --stanza=pg-dev archive-push %p
    log_destination: jsonlog
    log_directory: /var/log/postgresql/15
    log_filename: postgresql-%a.log
    log_min_duration_statement: '250ms'
    log_rotation_age: 1d
    log_timezone: America/Chicago
    log_truncate_on_rotation: 'on'
    logging_collector: 'on'
    log_connections: on
    log_line_prefix: '< %m %u %c: >'
    ssl: 'on'
    ssl_ca_file: /etc/ssl/certs/ca-bundle.crt
    ssl_cert_file: /etc/ssl/certs/fancy-ssl.crt
    ssl_key_file: /etc/pki/tls/private/fancy-key.key
ssl_min_protocol_version: 'TLSv1.2'
    unix_socket_directories: /run/postgresql
    unix_socket_group: postgres
    unix_socket_permissions: '0777'
    compute_query_id: 'on'
    wal_recycle: 'off'
    checkpoint_warning: '30'
    fsync: 'on'
    huge_page_size: 0
    huge_pages: try
    idle_in_transaction_session_timeout: "5min"
    maintenance_work_mem: "64MB"
    max_connections: 1024
    max_prepared_transactions: 1024
    pgaudit.log: 'ddl,write'
    pg_stat_statements.max: 10000
    pg_stat_statements.track: all
    shared_buffers: 128MB
    shared_preload_libraries: 'pgaudit,pg_stat_statements,pg_repack,ltree,pgcrypto,pg_trgm,tablefunc'
```

### patronictl show-config

```yaml
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    checkpoint_timeout: 30
    max_connections: 1024
    max_prepared_transactions: 1024
    max_replication_slots: 10
    max_wal_senders: 10
    tcp_keepalives_count: 3
    tcp_keepalives_idle: 60
    tcp_keepalives_interval: 10
    wal_keep_segments: 30
    wal_level: logical
  use_pg_rewind: false
  use_slots: true
  use_unix_socket: true
retry_timeout: 10
ttl: 30
```

### Patroni log files

```shell
2024-06-18 17:26:54,386 DEBUG: does not have lock
2024-06-18 17:26:54,387 DEBUG: Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2024-06-18 17:26:54,395 DEBUG: Received message: {'result': {'header': {'cluster_id': '17572998961377807224', 'member_id': '8988864463841141323', 'revision': '256158', 'raft_term': '6905'}, 'events': [{'kv': {'key': 'L29zaXQtZGJhLWRldi92Y2ZzLWRldjQvbWVtYmVycy92YXMtMXgtcHNxbGRiMDI=', 'create_revision': '249763', 'mod_revision': '256158', 'version': '2244', 'value': 'eyJjb25uX3VybCI6InBvc3RncmVzOi8vMTAuMy4xMC43MTo1NDMyL3Bvc3RncmVzIiwiYXBpX3VybCI6Imh0dHBzOi8vdmFzLTF4LXBzcWxkYjAyLmlkbS5saGkuY29tOjgwMDgvcGF0cm9uaSIsInN0YXRlIjoicnVubmluZyIsInJvbGUiOiJtYXN0ZXIiLCJ2ZXJzaW9uIjoiMy4zLjAiLCJ4bG9nX2xvY2F0aW9uIjo0MDkyMjcxNDMzNiwidGltZWxpbmUiOjU0fQ==', 'lease': '5549437558039345951'}}]}}
2024-06-18 17:26:54,431 DEBUG: https://bar-psqldb05.ssl.compatible.com:2379 "POST /v3/lease/keepalive HTTP/1.1" 200 None
2024-06-18 17:26:54,432 INFO: no action. I am (bar-psqldb04), a secondary, and following a leader (bar-psqldb02)
2024-06-18 17:27:04,336 DEBUG: Received message: {'result': {'header': {'cluster_id': '17572998961377807224', 'member_id': '8988864463841141323', 'revision': '256159', 'raft_term': '6905'}, 'events': [{'kv': {'key': 'L29zaXQtZGJhLWRldi92Y2ZzLWRldjQvc3RhdHVz', 'create_revision': '208', 'mod_revision': '256159', 'version': '52761', 'value': 'eyJvcHRpbWUiOjQwOTIyODc5NjQ4fQ=='}}]}}
2024-06-18 17:27:04,336 DEBUG: L29zaXQtZGJhLWRldi92Y2ZzLWRldjQvc3RhdHVz changed from eyJvcHRpbWUiOjQwOTIyNzE0MzM2fQ== to eyJvcHRpbWUiOjQwOTIyODc5NjQ4fQ==
2024-06-18 17:27:04,371 INFO: Lock owner: bar-psqldb02; I am bar-psqldb04
```

### PostgreSQL log files

```shell
{"timestamp":"2024-06-18 17:17:14.409 CDT","pid":184885,"session_id":"66720769.2d235","line_num":1,"session_start":"2024-06-18 17:17:13 CDT","txid":0,"error_severity":"LOG","message":"ending log output to stderr","hint":"Future log output will go to log destination \"jsonlog\".","backend_type":"postmaster","query_id":0}
{"timestamp":"2024-06-18 17:17:14.409 CDT","pid":184885,"session_id":"66720769.2d235","line_num":2,"session_start":"2024-06-18 17:17:13 CDT","txid":0,"error_severity":"LOG","message":"starting PostgreSQL 15.7 - Percona Distribution on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-20.0.3), 64-bit","backend_type":"postmaster","query_id":0}
{"timestamp":"2024-06-18 17:17:14.410 CDT","pid":184885,"session_id":"66720769.2d235","line_num":3,"session_start":"2024-06-18 17:17:13 CDT","txid":0,"error_severity":"LOG","message":"listening on IPv4 address \"0.0.0.0\", port 5432","backend_type":"postmaster","query_id":0}
{"timestamp":"2024-06-18 17:17:14.413 CDT","pid":184885,"session_id":"66720769.2d235","line_num":4,"session_start":"2024-06-18 17:17:13 CDT","txid":0,"error_severity":"LOG","message":"listening on IPv6 address \"::1\", port 5432","backend_type":"postmaster","query_id":0}
{"timestamp":"2024-06-18 17:17:14.414 CDT","pid":184885,"session_id":"66720769.2d235","line_num":5,"session_start":"2024-06-18 17:17:13 CDT","txid":0,"error_severity":"LOG","message":"listening on Unix socket \"/run/postgresql/.s.PGSQL.5432\"","backend_type":"postmaster","query_id":0}
{"timestamp":"2024-06-18 17:17:14.436 CDT","pid":184890,"session_id":"6672076a.2d23a","line_num":1,"session_start":"2024-06-18 17:17:14 CDT","txid":0,"error_severity":"LOG","message":"database system was shut down in recovery at 2024-06-18 17:16:28 CDT","backend_type":"startup","query_id":0}
{"timestamp":"2024-06-18 17:17:14.460 CDT","pid":184890,"session_id":"6672076a.2d23a","line_num":2,"session_start":"2024-06-18 17:17:14 CDT","txid":0,"error_severity":"LOG","message":"entering standby mode","backend_type":"startup","query_id":0}
{"timestamp":"2024-06-18 17:17:14.489 CDT","pid":184890,"session_id":"6672076a.2d23a","line_num":3,"session_start":"2024-06-18 17:17:14 CDT","txid":0,"error_severity":"LOG","message":"restored log file \"00000036.history\" from archive","backend_type":"startup","query_id":0}
{"timestamp":"2024-06-18 17:17:14.542 CDT","pid":184897,"remote_host":"[local]","session_id":"6672076a.2d241","line_num":1,"ps":"","session_start":"2024-06-18 17:17:14 CDT","txid":0,"error_severity":"LOG","message":"connection received: host=[local]","backend_type":"not initialized","query_id":0}
{"timestamp":"2024-06-18 17:17:14.542 CDT","user":"super_dooper","dbname":"postgres","pid":184897,"remote_host":"[local]","session_id":"6672076a.2d241","line_num":2,"ps":"","session_start":"2024-06-18 17:17:14 CDT","txid":0,"error_severity":"FATAL","state_code":"57P03","message":"the database system is starting up","backend_type":"client backend","query_id":0}
{"timestamp":"2024-06-18 17:17:14.897 CDT","pid":184903,"remote_host":"[local]","session_id":"6672076a.2d247","line_num":1,"ps":"","session_start":"2024-06-18 17:17:14 CDT","txid":0,"error_severity":"LOG","message":"connection received: host=[local]","backend_type":"not initialized","query_id":0}
{"timestamp":"2024-06-18 17:17:14.897 CDT","user":"super_dooper","dbname":"postgres","pid":184903,"remote_host":"[local]","session_id":"6672076a.2d247","line_num":2,"ps":"","session_start":"2024-06-18 17:17:14 CDT","txid":0,"error_severity":"FATAL","state_code":"57P03","message":"the database system is starting up","backend_type":"client backend","query_id":0}
{"timestamp":"2024-06-18 17:17:14.908 CDT","pid":184905,"remote_host":"[local]","session_id":"6672076a.2d249","line_num":1,"ps":"","session_start":"2024-06-18 17:17:14 CDT","txid":0,"error_severity":"LOG","message":"connection received: host=[local]","backend_type":"not initialized","query_id":0}
{"timestamp":"2024-06-18 17:17:14.909 CDT","user":"super_dooper","dbname":"postgres","pid":184905,"remote_host":"[local]","session_id":"6672076a.2d249","line_num":2,"ps":"","session_start":"2024-06-18 17:17:14 CDT","txid":0,"error_severity":"FATAL","state_code":"57P03","message":"the database system is starting up","backend_type":"client backend","query_id":0}
{"timestamp":"2024-06-18 17:17:15.173 CDT","pid":184890,"session_id":"6672076a.2d23a","line_num":4,"session_start":"2024-06-18 17:17:14 CDT","txid":0,"error_severity":"LOG","message":"restored log file \"000000360000000900000086\" from archive","backend_type":"startup","query_id":0}
{"timestamp":"2024-06-18 17:17:15.225 CDT","pid":184890,"session_id":"6672076a.2d23a","line_num":5,"session_start":"2024-06-18 17:17:14 CDT","vxid":"1/0","txid":0,"error_severity":"LOG","message":"redo starts at 9/86343C50","backend_type":"startup","query_id":0}
{"timestamp":"2024-06-18 17:17:15.237 CDT","pid":184890,"session_id":"6672076a.2d23a","line_num":6,"session_start":"2024-06-18 17:17:14 CDT","vxid":"1/0","txid":0,"error_severity":"LOG","message":"consistent recovery state reached at 9/87000000","backend_type":"startup","query_id":0}
{"timestamp":"2024-06-18 17:17:15.237 CDT","pid":184885,"session_id":"66720769.2d235","line_num":6,"session_start":"2024-06-18 17:17:13 CDT","txid":0,"error_severity":"LOG","message":"database system is ready to accept read-only connections","backend_type":"postmaster","query_id":0}
{"timestamp":"2024-06-18 17:17:15.379 CDT","pid":184910,"session_id":"6672076b.2d24e","line_num":1,"session_start":"2024-06-18 17:17:15 CDT","txid":0,"error_severity":"FATAL","state_code":"08P01","message":"could not start WAL streaming: ERROR:  replication slot \"bar-psqldb04\" does not exist","backend_type":"walreceiver","query_id":0}
{"timestamp":"2024-06-18 17:17:15.546 CDT","pid":184915,"session_id":"6672076b.2d253","line_num":1,"session_start":"2024-06-18 17:17:15 CDT","txid":0,"error_severity":"FATAL","state_code":"08P01","message":"could not start WAL streaming: ERROR:  replication slot \"bar-psqldb04\" does not exist","backend_type":"walreceiver","query_id":0}
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

I can validate both sides of pg_backrest.  Meaning, from the database server and the pgbackrest repo both pass checks.  I ran a full backup and it finished successfully.
No log shipping errors on the postgresql server side.
