### ISSUE TITLE
Patroni overwrite synchronous_standby_names on primary in async mode

### ISSUE THREAD

**Issue by Nudin** [patroni/patroni#3093]
### What happened?

We run a patroni cluster of 4 hosts and we have synchronous_mode off, but we have turned on postgresqls synchronous_commits and set synchronous_standby_names. [The documentation](https://patroni.readthedocs.io/en/latest/replication_modes.html#postgresql-synchronous-replication) tells this is possible and what we want. But patroni sets synchronous_standby_names to the configured value on all hosts except on the primary. On this host patroni sets it to the empty value, thus deactivating synchronous_commits.[](url)

### How can we reproduce it (as minimally and precisely as possible)?

Set up a patroni cluster of 3+ nodes, set `synchronous_commit: "on"` and `synchronous_standby_names: "*"` to enable Postgres’s [synchronous replication](http://www.postgresql.org/docs/current/static/warm-standby.html#SYNCHRONOUS-REPLICATION) but leave synchronous_mode off.

### What did you expect to happen?

Patroni to set synchronous_standby_names to  the configured value on all hosts and not interfere with it.

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.3.0
-   PostgreSQL version: 15.0
-   DCS (and its version): etcd 

### Patroni configuration file

```yaml
scope: xxx
namespace: /db_xxx/
name: xxx
restapi:
    listen: 0:8008
    connect_address: 10.0.1.100:8008

etcd3:
    host: localhost:2379

bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
          use_pg_rewind: true
          parameters:
            wal_keep_size: 8GB
            max_connections: 500
            shared_buffers: 700MB
            maintenance_work_mem: 512MB
            work_mem: 4MB
            effective_cache_size: 8GB
            log_lock_waits: on

    initdb:
    - encoding: UTF8
    - data-checksums


postgresql:
    listen: 0:5432
    connect_address: 10.0.1.100:5432
    data_dir: /var/lib/patroni/data
    bin_dir: /usr/lib/postgresql/15/bin
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: replicator
            password: "xxx"
        superuser:
            username: postgres
            password: "xxx"
        rewind:
            username: rewind_user
            password: "xxx"
    use_pg_rewind: true
    parameters:
        unix_socket_directories: '.'
synchronous_commit: "on"
        synchronous_standby_names: '*'

        wal_keep_size: 8GB
        max_connections: 500
        log_lock_waits: on
        shared_buffers: 700MB
        maintenance_work_mem: 512MB
        work_mem: 4MB
        effective_cache_size: 8GB
        shared_preload_libraries: 'pg_stat_statements,auto_explain'
        pg_stat_statements.max: 10000
        pg_stat_statements.track: all
        auto_explain.log_min_duration: "1s"
        tcp_keepalives_idle: 60s
        tcp_keepalives_interval: 5s
        tcp_keepalives_count: 3
        client_connection_check_interval: 5s
        autovacuum_analyze_scale_factor: 0.05
        autovacuum_vacuum_scale_factor: 0.1
        autovacuum_vacuum_insert_scale_factor: 0.1
        log_destination: 'jsonlog'
        logging_collector : on
        log_directory: '/var/log/postgresql'
        

    pg_hba:
    - local   all          all                trust
    - host    all          all  127.0.0.1/32  trust
    - host    all          all  ::1/128       trust
    - local   replication  all                trust
    - host    replication  all  127.0.0.1/32  trust
    - host    replication  all  ::1/128       trust
    - host replication replicator 10.0.1.100/0 md5
    - host replication replicator 10.0.1.101/0 md5
    - host replication replicator 10.0.1.102/0 md5
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator ::1/128 md5
    - host all all 0.0.0.0/0 md5

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

### patronictl show-config

```yaml
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    effective_cache_size: 8GB
    log_lock_waits: true
    maintenance_work_mem: 512MB
    max_connections: 500
    shared_buffers: 700MB
    wal_keep_size: 8GB
    work_mem: 4MB
  use_pg_rewind: true
retry_timeout: 10
synchronous_mode: true
ttl: 30
```

### Patroni log files

```shell
-
```

### PostgreSQL log files

```shell
-
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

Discussed it in the Slack Channel:
https://postgresteam.slack.com/archives/C9XPYG92A/p1719398978518599
