### ISSUE TITLE
Patroni Does Not Failover on Data Disk Full Shutdown

### ISSUE THREAD

**Issue by prime-minister-of-fun** [patroni/patroni#3102]
### What happened?

Preamble:
cluster name: vcfs-dev4
bar-psqldb01 10.3.10.77
bar-psqldb02 10.3.10.76
bar-psqldb03 10.3.10.71
bar-psqldb04 10.3.10.75

A couple of things happened.  
Data partition ran out of disk space on host bar-psqldb03 and shut down the Postgresql server.   Patroni did not failover to another node. 
My response was: shut down patroni on host bar-psqldb03 so another node would become primary.  
After systctl stop patroni on host bar-psqldb03, bar-psqldb02 becomes primary, but the replicas are all still pointed at bar-psqldb03 ( 10.3.10.71 in the logging)
I attempt to `patronictl -c /etc/patroni/postgresql.yml reinit  vcfs-dev4 bar-psqldb01` .  Patroni is attempting to take a snapshot from bar-psqldb03, not the leader.

Logging from bar-psqldb01
```
 psycopg2.OperationalError: connection to server at "10.3.10.71", port 5432 failed: session is read-only
2024-07-12 10:41:22,506 INFO: no action. I am (vm1), a secondary, and following a leader (vm2)
```
So, patroni seems aware that bar-psqldb02 is the leader, but, reaching out to bar-psqldb03 for a database snapshot. 

Now I have a node accepting reads/writes, but no replicas connected to it.  And no obvious method to get the replicas pointed at the new leader bar-psqldb02.   Also, no method to fail back to the old leader, bar-psqldb03.

Manual pg_basebackup on bar-psqldb01 using the new leader, bar-psqldb02 gets the current database.  Patroni starts, but, still insists on trying to connect to bar-psqldb03.

### How can we reproduce it (as minimally and precisely as possible)?

Let the leader node run out of disk space.

### What did you expect to happen?

- I expected patroni to perform a failover event when PostgreSQL stopped running because it ran out of disk space.
- I expected all nodes to be replicating from the new leader. 

### Patroni/PostgreSQL/DCS version

- Patroni version: percona-patroni-3.3.0-1.el8.x86_64 patroni 3.3.0
- PostgreSQL version: 15 percona-postgresql15-server-15.7-1.el8.x86_64
- DCS (and its version): etcd etcd-3.5.13-1.el8.x86_64

### Patroni configuration file

```yaml
scope: vcfs-dev4
namespace: /foo-dba-dev/
name: bar-psqldb04

restapi:
  listen: 0.0.0.0:8008
  #full domain required for tls!
  connect_address: bar-psqldb04.ssl.compatible.com:8008
  cafile: /etc/pki/tls/certs/ca.crt
  certfile: /etc/pki/tls/certs/host.crt
  keyfile: /etc/pki/tls/private/host.key
  authentication:
    username: my_patroni_user
    password: superseeecret_ssshhhh
# If you want to force the list of allowed IPs, use allowlist
#  allowlist:

ctl:
  insecure: true
  cafile: /etc/ssl/certs/ca-bundle.crt
  certfile: /etc/ssl/certs/host.crt
  keyfile: /etc/pki/tls/private/host.key

etcd3:
  protocol: https
  cacert: /etc/pki/tls/certs/ca.crt
  cert:  /etc/pki/tls/certs/host.crt
  key: /etc/pki/tls/private/host.key
  hosts:
   - bar-psqldb01.ssl.compatible.com:2379
   - bar-psqldb02.ssl.compatible.com:2379
   - bar-psqldb03.ssl.compatible.com:2379
   - bar-psqldb04.ssl.compatible.com:2379
   - bar-psqldb05.ssl.compatible.com:2379
bootstrap:
  dcs:
   ttl: 30
   loop_wait: 10
   retry_timeout: 10
   maximum_lag_on_failover: 1048576
   master_start_timeout: 300  #default
   postgresql:
    use_pg_rewind: false
    use_slots: true
    use_unix_socket_repl: false
    use_unix_socket: true
    #putting parameters here means every node in the cluster gets it
    parameters:
      wal_keep_segments: 30
      max_wal_senders: 10
      max_replication_slots: 10
      checkpoint_timeout: 30
      wal_level: logical
      hotstandby: on
      tcp_keepalives_interval: 10
      tcp_keepalives_count: 3
      tcp_keepalives_idle: 60

  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - locale: en_US.utf8
  - data-checksums
  users:
   repl_role:
    password: staqreas
    options:
    - replication
   rewind_role_dev:
    password: fringlistis
    options:
    - replication
   super_dooper:
    password: another_secret
    options:
    - superuser
    - createdb
    - createrole
postgresql:
  listen: "0.0.0.0,::1:5432"
  listen_addresses: "192.168.2.2,127.0.0.1,::1"
  connect_address: 192.168.2.2:5432
  bin_dir: "/usr/pgsql-15/bin"
  data_dir: '/var/lib/pgsql/15/mount/data'
  pgpass: /var/lib/pgsql/.pgpass
  use_pg_rewind: false
  use_unix_socket: true
  remove_data_directory_on_diverged_timelines: true
  pg_hba:
   - local replication repl_role,rewind_role_dev scram-sha-256
   - local postgres postgres peer
   - local postgres super_dooper scram-sha-256
   - hostnossl replication repl_role,rewind_role_dev 127.0.0.1/32 scram-sha-256
   - hostnossl replication repl_role,rewind_role_dev ::1/128 scram-sha-256
   - hostssl replication repl_role,rewind_role_dev 192.168.101.0/24 scram-sha-256
   - hostnossl  all  all  0.0.0.0/0 reject
authentication:
    replication:
      username: repl_role
      password: 8th_mystery
      sslmode: "require"
      sslkey: "/etc/pki/tls/private/postgresql.key"
      sslcert: "/etc/pki/tls/certs/postgresql.crt"
      sslrootcert: "/etc/pki/tls/certs/ca.crt"
      gssencmode: "disable"
      channel_binding: "disable"
      rewind:  # Has no effect on postgres 10 and lower
      username: rewind_user
      password: strongly_typed_password
      sslmode: "require"
      sslkey: "/etc/pki/tls/private/postgresql.key"
      sslcert: "/etc/pki/tls/certs/postgresqo.crt"
      sslrootcert: "/etc/pki/tls/certs/ca.crt"
      gssencmode: "disable"
      channel_binding: "disable"
    superuser:
      username: super_dooper
      password: another_mystery
      sslmode: "require"
      sslkey: "/etc/pki/tls/private/postgresql.key"
      sslcert: "/etc/pki/tls/certs/postgresql.crt"
      sslrootcert: "/etc/pki/tls/certs/ca.crt"
      gssencmode: "disable"
      channel_binding: "disable"
 create_replica_methods:
    - basebackup
  basebackup:
    max-rate: "100M"
  parameters:
    archive_mode: 'on'
    archive_command: /bin/pgbackrest --stanza=pg-dev archive-push %p
    log_destination: jsonlog
    log_directory: /var/log/postgresql/15
    log_filename: postgresql-%a.log
    log_min_duration_statement: '250ms'
    log_rotation_age: 1d
    log_timezone: America/Chicago
    log_truncate_on_rotation: 'on'
    logging_collector: 'on'
    log_connections: on
    log_line_prefix: '< %m %u %c: >'
    ssl: 'on'
    ssl_ca_file: /etc/ssl/certs/ca-bundle.crt
    ssl_cert_file: /etc/ssl/certs/fancy-ssl.crt
    ssl_key_file: /etc/pki/tls/private/fancy-key.key
ssl_min_protocol_version: 'TLSv1.2'
    unix_socket_directories: /run/postgresql
    unix_socket_group: postgres
    unix_socket_permissions: '0777'
    compute_query_id: 'on'
    wal_recycle: 'off'
    checkpoint_warning: '30'
    fsync: 'on'
    huge_page_size: 0
    huge_pages: try
    idle_in_transaction_session_timeout: "5min"
    maintenance_work_mem: "64MB"
    max_connections: 1024
    max_prepared_transactions: 1024
    pgaudit.log: 'ddl,write'
    pg_stat_statements.max: 10000
    pg_stat_statements.track: all
    shared_buffers: 128MB
    shared_preload_libraries: 'pgaudit,pg_stat_statements,pg_repack,ltree,pgcrypto,pg_trgm,tablefunc'
```

### patronictl show-config

```yaml
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    checkpoint_timeout: 30
    max_connections: 1024
    max_prepared_transactions: 1024
    max_replication_slots: 10
    max_wal_senders: 10
    tcp_keepalives_count: 3
    tcp_keepalives_idle: 60
    tcp_keepalives_interval: 10
    wal_keep_segments: 30
    wal_level: logical
  use_pg_rewind: false
  use_slots: true
  use_unix_socket: true
retry_timeout: 10
ttl: 30
```

### Patroni log files

```shell
psycopg2.OperationalError: connection to server at "10.3.10.71", port 5432 failed: session is read-only
2024-07-12 10:41:22,506 INFO: no action. I am (bar-psqldb01), a secondary, and following a leader (bar-psqldb02)
```

### PostgreSQL log files

```shell
Nothing relevant in the PostgreSQL log files.
```

### Have you tried to use GitHub issue search?

- [X] Yes
