### ISSUE TITLE
recovery parameters in parameters will cause recovery_conf ignored while buiding config

### ISSUE THREAD

**Issue by waynerv** [patroni/patroni#3114]
### What happened?

https://github.com/patroni/patroni/blob/cd3f52b029a38781fee5805a48704f12b235078f/patroni/postgresql/config.py#L977

If we configure any recovery parameters such as `restore_command` in `postgresql.parameters` section, all settings in `postgresql.recovery_conf` will be disregarded. 

Is this intentional? If so, we should improve the documentation to clearly state this behavior.

### How can we reproduce it (as minimally and precisely as possible)?

create a following configuration:
```
  postgresql:
      parameters:
        recovery_end_command: ''
      recovery_conf:
        restore_command: 'cp %f "%p"'
 ```

 `recovery_end_command` will cause `restore_command` in recovery_conf ignored when configuring a follower.

### What did you expect to happen?

Both parameters function, but one has higher priority.

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.1.2
-   PostgreSQL version: 14 
-   DCS (and its version):  kubernetes

### Patroni configuration file

```yaml
bootstrap:
  method: initdb
  dcs:
    postgresql:
      parameters:
        archive_command: '/home/postgres/bin/pgbackrest_archive_push.sh %p'
        archive_cleanup_command: ''
        password_encryption: scram-sha-256
        pgaudit.log: none
        recovery_end_command: ''
      use_slots: true
      recovery_conf:
        restore_command: 'pgbackrest
          archive-get --archive-async=y --process-max=2 --archive-get-queue-max=1GiB
          %f "%p"'
      custom_conf: /pgconf/postgres.base.conf
```

### patronictl show-config

```yaml
-
```

### Patroni log files

```shell
-
```

### PostgreSQL log files

```shell
-
```

### Have you tried to use GitHub issue search?

- [X] Yes
