### ISSUE TITLE
WAL Files are not deleted after 20 GB pg_restore on primary node

### ISSUE THREAD

**Issue by VinnyVicious** [patroni/patroni#3117]
### What happened?

Restored a single table of around 20 GB using pg_restore. Took 8 hours.

### How can we reproduce it (as minimally and precisely as possible)?

Import a large table using pg_restore into the primary node of the cluster.

### What did you expect to happen?

WAL files to be deleted

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.3.0
-   PostgreSQL version: 16
-   DCS (and its version): 3.3.0

### Patroni configuration file

```yaml
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    checkpoint_completion_target: 0.9
    default_statistics_target: 100
    effective_cache_size: 12GB
    effective_io_concurrency: 200
    hot_standby: 'on'
    huge_pages: false
    logging_collector: 'on'
    maintenance_work_mem: 4GB
    max_connections: 300
    max_parallel_maintenance_workers: 4
    max_parallel_workers: 8
    max_parallel_workers_per_gather: 4
    max_replication_slots: 10
    max_wal_senders: 5
    max_wal_size: 4GB
    max_worker_processes: 8
    min_wal_size: 1GB
    random_page_cost: 1.1
    shared_buffers: 4GB
    wal_buffers: 16MB
    wal_keep_segments: 10
    wal_level: replica
    wal_log_hints: 'on'
    work_mem: 16MB
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
slots:
  percona_cluster_1:
    type: physical
ttl: 30
```

### patronictl show-config

```yaml
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    checkpoint_completion_target: 0.9
    default_statistics_target: 100
    effective_cache_size: 12GB
    effective_io_concurrency: 200
    hot_standby: 'on'
    huge_pages: false
    logging_collector: 'on'
    maintenance_work_mem: 4GB
    max_connections: 300
    max_parallel_maintenance_workers: 4
    max_parallel_workers: 8
    max_parallel_workers_per_gather: 4
    max_replication_slots: 10
    max_wal_senders: 5
    max_wal_size: 4GB
    max_worker_processes: 8
    min_wal_size: 1GB
    random_page_cost: 1.1
    shared_buffers: 4GB
    wal_buffers: 16MB
    wal_keep_segments: 10
    wal_level: replica
    wal_log_hints: 'on'
    work_mem: 16MB
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
slots:
  percona_cluster_1:
    type: physical
ttl: 30
```

### Patroni log files

```shell
No errors or anything strange
```

### PostgreSQL log files

```shell
Output of replication slots:

"slot_name"	"bytes_behind"	"active"	"wal_status"
"percona_cluster_1"	"596551317984"	"false"	"extended"
"db_production01"	"0"	"true"	"reserved"
"db_production03"	"0"	"true"	"reserved"
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

percona_cluster_1 is a physical replication slot, as shown in the config. It has a lot of bytes behind, meanwhile the replicas are stable.
