### ISSUE TITLE
Duplicate patroni.yml log_filename config lines can cause issues

### ISSUE THREAD

**Issue by m384wwn** [patroni/patroni#3135]
### What happened?

I accidentally duplicated the log_filename configuration line in patroni.yml. While the system still runs, it causes a number of issues down the road, such as:
- hilarious log file names:  postgresql-2024-05-15.log-2024-05-17.log-2024-05-19.log-2024-05-21.log-2024-05-23.log-2024-05-25.log-2024-05-27.log-2024-05-30.log
- reinit failure due to:  pg_basebackup: error: could not get write-ahead log end position from server: ERROR:  file name too long for tar format: "log/postgresql-2024-05-01.log-2024-05-04.log-2024-05-07.log-2024-05-11.log-2024-05-13.log-2024-05-20.log-2024-05-22.log"
- logrotate running indefinitely with high cpu and memory usage

### How can we reproduce it (as minimally and precisely as possible)?

duplicate the log_filename paramter in the patroni.yml config then run it e.g.:

[root@db01 ~]#  cat /etc/patroni.yml | grep log_filename
        log_filename: 'postgresql-%Y-%m-%d.log'
        log_filename: 'postgresql-%Y-%m-%d.log'

### What did you expect to happen?

I think Patroni should either ignore the second parameter entry or have another way of handling this, such as failing to start and/or logging the issue.

### Patroni/PostgreSQL/DCS version

[root@db01 ~]# patroni --version
patroni 3.2.1

### Patroni configuration file

```yaml
#Relevant lines only
postgresql:
    parameters:
        log_timezone: 'UTC'
        log_statement: none
        log_min_messages: INFO
        log_min_error_statement: INFO
        log_min_duration_statement: 3s
        log_connections: 'on'
        log_disconnections: 'on'
        log_duration: 'off'
        log_line_prefix: '%m [pid=%p %a] [%u@%d %l %i %e] '
        log_filename: 'postgresql-%Y-%m-%d.log'
        log_filename: 'postgresql-%Y-%m-%d.log'
```

### patronictl show-config

```yaml
not relevant
```

### Patroni log files

```shell
not relevant
```

### PostgreSQL log files

```shell
not relevant
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

The root cause of this issue is a misconfiguration in patroni.yml, but it might be a good idea to handle this type of minor misconfiguration to prevent slight errors from having an insidious effect and turning into significant issues later. It may also be worth checking the handling of other duplicate parameters.

Keep up the good work, thanks!
