### ISSUE TITLE
Static slots make performance degradation

### ISSUE THREAD

**Issue by Medzon888** [patroni/patroni#3153]
### What happened?

I have the following situation with static logical slots on patroni clusters: performance is slowly decreasing and bloat is growth. Autovacuum works but still leave a couple of dead tuples, for system tables as well. All of this happened after we enable static slots and hot_standby_feedback(as default for this scenario). We have no any read queries on replicas except monitoring wich is use system tables and their execution time is lower than 100ms.

Problems:
1) Found that table bloat growth (this is camunda and they have high workload so I found problem on the next day after we enable slots) and autovacuums not save the situation
2) Found that query planning is huge (300ms planning against 1ms executing) for the first execution and ok for the next one. After ~20sec if repeat this then first planning again is big:
![image](https://github.com/user-attachments/assets/0aa45eec-77e5-4f54-81e6-991bdae163f7)

Checked system tables and found bloat for statistic, there is amount of n_dead_tup. Like that:
```

    relname     | n_live_tup | n_dead_tup | ratio% | Total Size | Table Size | Index Size | last_vacuum |        last_autovacuum        |         last_analyze          |       last_autoanalyze
----------------+------------+------------+--------+------------+------------+------------+-------------+-------------------------------+-------------------------------+-------------------------------
 pg_statistic   |        715 |    1291606 | 180391 | 422 MB     | 364 MB     | 59 MB      |             | 2024-09-09 11:29:39.361462+03 |                               |
 pg_toast_2619  |         52 |      34311 |  64737 | 51 MB      | 50 MB      | 840 kB     |             | 2024-09-09 11:29:42.04358+03  |                               |
 pg_attribute   |       2513 |       7010 |    278 | 2480 kB    | 1760 kB    | 720 kB     |             | 2024-09-09 11:29:39.363419+03 | 2024-09-09 10:12:16.706212+03 | 2024-09-09 10:52:40.849449+03
 pg_class       |        839 |       5097 |    606 | 1512 kB    | 1104 kB    | 408 kB     |             | 2024-09-09 11:29:39.364294+03 | 2024-09-09 10:12:16.82263+03  | 2024-09-09 10:52:38.441281+03
 pg_proc        |       3384 |         53 |      1 | 1296 kB    | 816 kB     | 480 kB     |             |                               | 2024-09-09 10:12:16.794+03    |
 pg_depend      |       3004 |       3281 |    109 | 936 kB     | 392 kB     | 544 kB     |             | 2024-09-09 11:29:39.365921+03 | 2024-09-09 10:12:17.127089+03 | 2024-09-09 10:52:34.75709+03
 pg_rewrite     |        148 |          5 |      3 | 792 kB     | 112 kB     | 680 kB     |             |                               | 2024-09-09 10:12:17.009284+03 |
 pg_toast_2618  |         12 |         12 |     92 | 616 kB     | 568 kB     | 48 kB      |             |                               |                               |
 pg_description |       5240 |          7 |      0 | 616 kB     | 360 kB     | 256 kB     |             |                               | 2024-09-09 10:12:17.044904+03 |
 pg_type        |        727 |        730 |    100 | 440 kB     | 288 kB     | 152 kB     |             | 2024-09-09 11:29:39.362082+03 | 2024-09-09 10:12:16.566079+03 | 2024-09-09 10:52:34.589857+03
 pg_index       |        489 |        948 |    193 | 376 kB     | 256 kB     | 120 kB     |             | 2024-09-09 11:29:39.365076+03 | 2024-09-09 10:12:16.870653+03 | 2024-09-09 10:52:38.464815+03
 pg_collation   |        860 |          0 |      0 | 256 kB     | 120 kB     | 136 kB     |             |                               | 2024-09-09 10:12:17.338941+03 |
 pg_constraint  |        211 |         91 |     42 | 232 kB     | 72 kB      | 160 kB     |             | 2024-09-09 11:29:39.36477+03  | 2024-09-09 10:12:16.85494+03  | 2024-09-09 09:58:14.298045+03
 pg_operator    |        799 |          0 |      0 | 232 kB     | 112 kB     | 120 kB     |             |                               | 2024-09-09 10:12:16.901476+03 |
 pg_amop        |        945 |          0 |      0 | 224 kB     | 56 kB      | 168 kB     |             |                               | 2024-09-09 10:12:16.956981+03 |
(15 rows)

```
Manual vacuum showing a lot of dead tuples wich can't be removed
```

INFO:  vacuuming "pickup_orchestrator.pg_catalog.pg_statistic"
INFO:  finished vacuuming "pickup_orchestrator.pg_catalog.pg_statistic": index scans: 0
pages: 0 removed, 46702 remain, 46702 scanned (100.00% of total)
tuples: 0 removed, 1296353 remain, 1295638 are dead but not yet removable
removable cutoff: 3051616, which was 6998656 XIDs old when operation ended
new relminmxid: 485936, which is 30 MXIDs ahead of previous value
frozen: 0 pages from table (0.00% of total) had 0 tuples frozen
index scan not needed: 0 pages from table (0.00% of total) had 0 dead item identifiers removed
avg read rate: 0.000 MB/s, avg write rate: 0.000 MB/s
buffer usage: 93437 hits, 0 misses, 0 dirtied
WAL usage: 1 records, 0 full page images, 225 bytes
system usage: CPU: user: 0.18 s, system: 0.09 s, elapsed: 0.27 s
INFO:  vacuuming "pickup_orchestrator.pg_toast.pg_toast_2619"
INFO:  finished vacuuming "pickup_orchestrator.pg_toast.pg_toast_2619": index scans: 0
pages: 0 removed, 6359 remain, 6359 scanned (100.00% of total)
tuples: 0 removed, 34363 remain, 34311 are dead but not yet removable
removable cutoff: 3051616, which was 6998656 XIDs old when operation ended
new relminmxid: 485936, which is 27 MXIDs ahead of previous value
frozen: 0 pages from table (0.00% of total) had 0 tuples frozen
index scan not needed: 0 pages from table (0.00% of total) had 0 dead item identifiers removed
avg read rate: 0.000 MB/s, avg write rate: 0.000 MB/s
buffer usage: 12731 hits, 0 misses, 0 dirtied
WAL usage: 1 records, 0 full page images, 188 bytes
system usage: CPU: user: 0.01 s, system: 0.00 s, elapsed: 0.02 s

```

After some investigation when no any changes for settings helps we exclude slots from patroni config. This make performance much better. From CPU side its looks like this:
![image](https://github.com/user-attachments/assets/d7a2e9c9-5110-44ab-b413-22b50545efaf)

Planning time now always 0.3 ms or something. Then we vacuum full statistic table and its make them 300kb. 
Table bloat's not growth anymore. All happy.

Whats wrong? Its look's like static slots prevent vacuum work and hold tuples. 

p.s. we have another cluster without camunda and there is same situation. after exculde slots all fine.
p.p.s we have statis slots on patroni with version 3.0.* and looks like they work a long time without this problem

### How can we reproduce it (as minimally and precisely as possible)?

Install patroni cluster with 3 nodes. Make statis slots for any tables. Make workload.
Check for system tables growth. For camunda you can check act_ru_job table growth.

### What did you expect to happen?

Stable autovacuum work. No growth for system tables and others. Stable planning time for queries.

### Patroni/PostgreSQL/DCS version

-   Patroni version: 4.0.1
-   PostgreSQL version: 16.4
-   DCS (and its version): 3.5.7

### Patroni configuration file

```yaml
scope: main
namespace: /service/
name: p-tms-picking-patroni-01-db-03

log:
  level: DEBUG
  format: '%(asctime)s %(levelname)s: %(message)s'
  max_queue_size: 1000
  dir: /data/pg_data/logs/patroni
  file_num: 4
  file_size: 25000000
  loggers:
    patroni.postmaster: DEBUG
    urllib3: DEBUG

restapi:
  connect_address: p-tms-picking-patroni-01-db-03.***:8008
  listen: 0.0.0.0:8008
  authentication:
    username: patroni
    password: ***



etcd3:
  hosts: ***:2379,***:2379,***:2379
  username: root
  password: ***

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: true
    synchronous_mode_strict: false
    check_timeline: true
    postgresql:
      use_pg_rewind: false
      use_slots: true
      parameters:
        max_connections: 300
        max_locks_per_transaction: 64
        max_worker_processes: 8
        max_prepared_transactions: 0
        wal_level: logical
        wal_log_hints: on
        track_commit_timestamp: off
        max_wal_senders: 10
        max_replication_slots: 10
  initdb:
    - encoding: UTF8
    - data-checksums
    - waldir: /data/pg_wal/postgres
  users:
    postgres:
      password: ***
    replica:
      password: ***
      options:
        - replication

postgresql:
  use_unix_socket: true
  listen: 0.0.0.0:5435
  connect_address: p-tms-picking-patroni-01-db-03.***:5435
  data_dir: /data/pg_data/postgres
  bin_dir: /usr/lib/postgresql/16/bin
  config_dir: /etc/postgresql/16/main
  pgpass: /var/lib/postgresql/.pgpass
  authentication:
    superuser:
      username: postgres
      password: ***
    replication:
      username: replica
      password: ***
  create_replica_methods:
    - basebackup
  basebackup:
    waldir: /data/pg_wal/postgres
  parameters:
    unix_socket_directories: /var/run/postgresql
    shared_preload_libraries: pg_stat_statements,auto_explain
    archive_mode: on
    archive_command: wal-g wal-push %p
  pg_hba:
    - local all all trust
    - host all all 127.0.0.1/32 trust
    - host all all 0.0.0.0/0 scram-sha-256
    - host replication replica 127.0.0.1/32 scram-sha-256
    - host replication replica ***8/32 scram-sha-256
    - host replication replica ***7/32 scram-sha-256
    - host replication replica ***/32 scram-sha-256
  pg_ctl_timeout: 60

watchdog:
  mode: automatic
  device: /dev/watchdog
  safety_margin: 5

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

### patronictl show-config

```yaml
check_timeline: true
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    max_connections: 300
    max_locks_per_transaction: 64
    max_prepared_transactions: 0
    max_replication_slots: 10
    max_wal_senders: 10
    max_worker_processes: 8
    track_commit_timestamp: false
    wal_level: logical
    wal_log_hints: true
  use_pg_rewind: false
  use_slots: true
retry_timeout: 10
slots:
  picking_pdpkfk_slot:
    database: picking
    plugin: pgoutput
    type: logical
  picking_rtdwh_pdpkfk_slot:
    database: picking
    plugin: pgoutput
    type: logical
synchronous_mode: true
synchronous_mode_strict: false
ttl: 30
```

### Patroni log files

```shell
Not needed
```

### PostgreSQL log files

```shell
Not needed
```

### Have you tried to use GitHub issue search?

- [X] Yes
