### ISSUE TITLE
Sudden cluster configuration crash 

### ISSUE THREAD

**Issue by gsl23** [patroni/patroni#3154]
### What happened?

We had Patroni cluster with 2 data nodes, and 3 node etcd 
data : 
b2c-db-p01
b2c-db-p02
etcd: 
b2c-db-p01
b2c-db-p02
b2c-db-etcd-p01
( yep, two etcd instances together with data nodes )

Few days ago I randomly recognized that node 1(primary) just  disappearred from cluster configuration  :

```
[root@b2c-db-p01 base]# patronictl -c /etc/patroni/patroni.yml list
+ Cluster: b2c-db-p (7374751084427556490) --------------------+----+-----------+
| Member     | Host           | Role    | State               | TL | Lag in MB |
+------------+----------------+---------+---------------------+----+-----------+
| b2c-db-p02 | x.x.x.39 | Replica | in archive recovery |  7 |         0 |
+------------+----------------+---------+---------------------+----+-----------+
```

But service is worked without interruption : 
```
[root@b2c-db-p01 base]# systemctl status patroni
● patroni.service - Runners to orchestrate a high-availability PostgreSQL
     Loaded: loaded (/usr/lib/systemd/system/patroni.service; enabled; preset: disabled)
     Active: active (running) since Thu 2024-05-30 18:04:27 +05; 3 months 5 days ago
   Main PID: 23283 (patroni)
      Tasks: 275 (limit: 99094)
     Memory: 12.5G
        CPU: 15h 51min 990ms
     CGroup: /system.slice/patroni.service
             ├─ 23283 /usr/bin/python3 /usr/bin/patroni /etc/patroni/patroni.yml
             
```
postgresql process is active and didn't have any interruption as well : 
```
[root@b2c-db-p01 base]# ps -ef | grep postgresql.conf
root      285856  276034  0 16:21 pts/1    00:00:00 grep --color=auto postgresql.conf
postgres  344661       1  0 **May31** ?        01:40:46 /usr/pgsql-15/bin/postgres -D /pg_data/data --config-file=/pg_data/data/postgresql.conf --listen_addresses=127.0.0.1:5432,0.0.0.0 --port=5432 --cluster_name=b2c-db-p --wal_level=replica --hot_standby=on --max_connections=1000 --max_wal_senders=10 --max_prepared_transactions=0 --max_locks_per_transaction=64 --track_commit_timestamp=off --max_replication_slots=5 --max_worker_processes=8 --wal_log_hints=on

```

### How can we reproduce it (as minimally and precisely as possible)?

I dont know.

### What did you expect to happen?

Normal work. 

### Patroni/PostgreSQL/DCS version

-   Patroni version:   3.3.0
-   PostgreSQL version:  15.3
-   DCS (and its version):  3.5.10

### Patroni configuration file

```yaml
scope: b2c-db-p
#namespace: /service/
name: b2c-db-p01

restapi:
  listen: x.x.x.x:8008
  connect_address: x.x.x.x:8008
  auth: 'username:test'

etcd:
  hosts: x.x.x.38:2379,x.x.x.39:2379,x.x.x.42:2379

bootstrap:
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  # and all other cluster members will use it as a `global configuration`
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: false
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        max_connections: 1000
        wal_level: hot_standby
        hot_standby: "on"
        wal_keep_segments: 8
        max_wal_senders: 10
        max_replication_slots: 5
        wal_log_hints: "on"
        archive_mode: "on"
        archive_timeout: 1800s
        archive_command: mkdir -p /pg_data/data/../wal_archive && test ! -f /pg_data/data/../wal_archive/%f && cp %p /pg_data/data/../wal_archive/%f
      recovery_conf:
        restore_command: cp /pg_data/data/../wal_archive/%f %p

  # some desired options for 'initdb'
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
  - host replication replicator x.x.x.0/24  scram-sha-256
  - host replication replicator 127.0.0.1/32  scram-sha-256
  - host all all 0.0.0.0/0  scram-sha-256
  - hostssl all all 0.0.0.0/0  scram-sha-256


  # Additional script to be launched after initial cluster creation (will be passed the connection URL as parameter)
# post_init: /usr/local/bin/setup_cluster.sh

  # Some additional users users which needs to be created after initializing new cluster
#  users:
#    admin:
#      password: admin
#      options:
#        - createrole
#        - createdb


postgresql:
  listen: 127.0.0.1:5432,0.0.0.0:5432
  connect_address: x.x.x.38:5432
  data_dir: /pg_data/data
  bin_dir: /usr/pgsql-15/bin
#  config_dir:
  pg_rewind:
    username: postgres
    password: ***
  pgpass: /var/lib/pgsql/pgpass0
  authentication:
    replication:
      username: replicator
      password: ***
    superuser:
      username: postgres
      password: ***
  parameters:
    archive_command: 'pg_probackup-15 archive-push -B /backup/postgres/ --instance=b2c-db-p01 --wal-file-path=%p --wal-file-name=%f --remote-host=pg-bckp-p01 --remote-user=postgres --compress'
    shared_preload_libraries: 'pg_stat_statements, pg_cron'
    unix_socket_directories: /run/postgresql
    pg_stat_statements.max: 10000
    pg_stat_statements.track: all
    max_connections: 1000
    shared_buffers: 6GB
    effective_cache_size: 8GB
    maintenance_work_mem: 512MB
    checkpoint_completion_target: 0.9
    wal_buffers: 16MB
    default_statistics_target: 100
    random_page_cost: 1.1
    effective_io_concurrency: 200
    work_mem: 2097kB
```

### patronictl show-config

```yaml
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: ''
    archive_mode: always
    archive_timeout: 1800s
    hot_standby: 'on'
    max_connections: 1000
    max_replication_slots: 5
    max_wal_senders: 10
    wal_keep_segments: 8
    wal_level: hot_standby
    wal_log_hints: 'on'
  recovery_conf:
    restore_command: cp /pg_data/data/../wal_archive/%f %p
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: false
ttl: 30
```

### Patroni log files

```shell
journalctl patroni node 1 :
Aug 06 13:13:10 b2c-db-p01 patroni[23283]: 2024-08-06 13:13:10,082 INFO: no action. I am (b2c-db-p01), the leader with the lock
Aug 06 13:13:20 b2c-db-p01 patroni[23283]: 2024-08-06 13:13:20,080 INFO: no action. I am (b2c-db-p01), the leader with the lock
Aug 06 13:13:30 b2c-db-p01 patroni[23283]: 2024-08-06 13:13:30,081 INFO: no action. I am (b2c-db-p01), the leader with the lock
Aug 06 13:13:40 b2c-db-p01 patroni[23283]: 2024-08-06 13:13:40,080 INFO: no action. I am (b2c-db-p01), the leader with the lock
Aug 06 13:13:50 b2c-db-p01 patroni[23283]: 2024-08-06 13:13:50,080 INFO: no action. I am (b2c-db-p01), the leader with the lock
Aug 06 13:14:00 b2c-db-p01 patroni[23283]: 2024-08-06 13:14:00,082 INFO: no action. I am (b2c-db-p01), the leader with the lock
Aug 06 13:14:10 b2c-db-p01 patroni[23283]: 2024-08-06 13:14:10,081 INFO: no action. I am (b2c-db-p01), the leader with the lock
Aug 06 13:14:20 b2c-db-p01 patroni[23283]: 2024-08-06 13:14:20,082 INFO: acquired session lock as a leader
Aug 06 13:14:30 b2c-db-p01 patroni[23283]: 2024-08-06 13:14:30,081 INFO: acquired session lock as a leader
Aug 06 13:14:40 b2c-db-p01 patroni[23283]: 2024-08-06 13:14:40,081 INFO: acquired session lock as a leader
Aug 06 13:14:50 b2c-db-p01 patroni[23283]: 2024-08-06 13:14:50,083 INFO: acquired session lock as a leader
Aug 06 13:15:00 b2c-db-p01 patroni[23283]: 2024-08-06 13:15:00,082 INFO: acquired session lock as a leader
....
Sep 04 16:34:40 b2c-db-p01 patroni[23283]: 2024-09-04 16:34:40,085 INFO: acquired session lock as a leader
etc ....
--------------------
journalctl patroni node 2 :
was rotated on the problem moment
```

### PostgreSQL log files

```shell
was rotated on the problem moment :(
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

Etcd log 
journalctl patroni etcd 1 :
Aug 06 13:14:03 b2c-db-p01 etcd[1594]: {"level":"warn","ts":"2024-08-06T13:14:03.809934+0500","caller":"rafthttp/probing_status.go:82","msg":"prober found high clock drift","round-tripper-name"...
Aug 06 13:14:03 b2c-db-p01 etcd[1594]: {"level":"warn","ts":"2024-08-06T13:14:03.809967+0500","caller":"rafthttp/probing_status.go:82","msg":"prober found high clock drift","round-tripper-name"...
Aug 06 13:14:03 b2c-db-p01 etcd[1594]: {"level":"warn","ts":"2024-08-06T13:14:03.809981+0500","caller":"rafthttp/probing_status.go:82","msg":"prober found high clock drift","round-tripper-name"...
Aug 06 13:14:33 b2c-db-p01 etcd[1594]: {"level":"warn","ts":"2024-08-06T13:14:33.81096+0500","caller":"rafthttp/probing_status.go:82","msg":"prober found higgh clock drift","round-tripper-name"...
Aug 06 13:14:33 b2c-db-p01 etcd[1594]: {"level":"warn","ts":"2024-08-06T13:14:33.810999+0500","caller":"rafthttp/probing_status.go:82","msg":"prober found high clock drift","round-tripper-name"...
Aug 06 13:15:03 b2c-db-p01 etcd[1594]: {"level":"warn","ts":"2024-08-06T13:15:03.811637+0500","caller":"rafthttp/probing_status.go:82","msg":"prober found high clock drift","round-tripper-name"...

[root@b2c-db-p01 base]# etcdctl ls / --recursive
/service
/service/b2c-db-p
/service/b2c-db-p/initialize
/service/b2c-db-p/config
/service/b2c-db-p/status
/service/b2c-db-p/history
/service/b2c-db-p/failover
/service/b2c-db-p/members
/service/b2c-db-p/members/b2c-db-p02

I understand, it may not be enought log data to ivestigate problem.
I hope to fix cluster configuration at least.
