### ISSUE TITLE
pg_wal grows infinitely on replica with Patroni 4.0.*

### ISSUE THREAD

**Issue by Foxeronie** [patroni/patroni#3171]
### What happened?

Hello everyone!

We updated Patroni from 3.3.2 to 4.0.1 in a one Primary + one Replica cluster szenario.
After that we restarted Patroni on the Replica.
Now the WAL files on the Replica will no longer be deleted/cleaned up. This goes on until the partition is full.
This also happens if both hosts running Patroni 4.0.1.
Patroni 4.0.2 didn't fix this behavior.
If we downgrade Patroni back to 3.3.2 and restart the Replica, the pg_wal directory will be cleaned up again.

![Screenshot 2024-09-18 at 10 20 02](https://github.com/user-attachments/assets/a0c7139a-e0dc-4400-a4a8-46b74c2191f8)

### How can we reproduce it (as minimally and precisely as possible)?

Have a Primary + Replica cluster with Patroni 3.3.2.
Update Patroni on the Replica to 4.0.*
Restart Patroni on the Replica.
WAL files in pg_wal/ will no longer be deleted/cleaned up.

### What did you expect to happen?

WAL files pg_wal/ should be deleted/cleaned up after some time

### Patroni/PostgreSQL/DCS version

-   Patroni version: 4.0.*
-   PostgreSQL version: 14, 15, 16 
-   DCS (and its version): etcd 3.3.25+dfsg-7ubuntu0.22.04.1

### Patroni configuration file

```yaml
scope: postgres
namespace: /puppet-db/
name: pg-puppet-db-2.domain.de

log:
  # https://docs.python.org/3.6/library/logging.html#levels
  level: DEBUG
  dir: /var/log/patroni
  file_size: 104857600
  format: '[%(asctime)s][%(levelname)s] %(message)s'

restapi:
    listen: "*:8008"
    connect_address: pg-puppet-db-2.domain.de:8008
    authentication:
        username: admin
        password: REDACTED
etcd:
    protocol: https
    hosts:
    - pg-etcd-1.domain.de:2379
    - pg-etcd-2.domain.de:2379
    - pg-etcd-3.domain.de:2379
    cert: /etc/patroni/client.pem
    key: /etc/patroni/client.key
    cacert: /etc/patroni/ca.pem
    username: puppet-db
    password: REDACTED

bootstrap:
    dcs:
        maximum_lag_on_failover: 1048576
        failsafe_mode: true
        postgresql:
            parameters:
                max_connections: 200
            recovery_conf:
                recovery_target_timeline: latest
                restore_command: /usr/bin/pgbackrest --stanza=puppet-db archive-get %f %p
    initdb:
    - encoding: UTF8
    - locale: C.UTF-8

    post_bootstrap: /var/lib/postgresql/post_bootstrap.sh puppet-db

postgresql:
    listen: pg-puppet-db-2.domain.de:5432
    connect_address: pg-puppet-db-2.domain.de:5432
    data_dir: /data/patroni/postgresql
    bin_dir: /usr/lib/postgresql/14/bin
    pgpass: /var/lib/postgresql/init_pgpass
    pg_hba:
    - local replication replicator scram-sha-256
    - hostssl replication replicator 127.0.0.1/32 scram-sha-256
    - hostssl replication replicator ::1/128 scram-sha-256
    - hostssl replication replicator pg-puppet-db-1.domain.de scram-sha-256
    - hostssl replication replicator pg-puppet-db-2.domain.de scram-sha-256
    - host replication replicator 0.0.0.0/0 reject
    - host replication replicator ::/0 reject
    - local all postgres scram-sha-256
    - hostssl all postgres pg-puppet-db-1.domain.de scram-sha-256
    - hostssl all postgres pg-puppet-db-2.domain.de scram-sha-256
    - host all postgres 0.0.0.0/0 reject
    - host all postgres ::/0 reject
    - local all exporter scram-sha-256
    - host all exporter 0.0.0.0/0 reject
    - host all exporter ::/0 reject
    - host monitoring icinga 192.168.194.118/32 scram-sha-256
    - host monitoring icinga 2001:638:700:10c2::1:76/128 scram-sha-256
    - host monitoring icinga 192.168.194.119/32 scram-sha-256
    - host monitoring icinga 2001:638:700:10c2::1:77/128 scram-sha-256
    - host monitoring icinga 192.168.40.27/32 scram-sha-256
    - host monitoring icinga 2001:638:700:1028::1b/128 scram-sha-256
    - host monitoring icinga 192.168.40.28/32 scram-sha-256
    - host monitoring icinga 2001:638:700:1028::1c/128 scram-sha-256
    - host monitoring icinga 192.168.40.29/32 scram-sha-256
    - host monitoring icinga 2001:638:700:1028::1d/128 scram-sha-256
    - host monitoring icinga 192.168.72.27/32 scram-sha-256
    - host monitoring icinga 2001:638:700:1048::1b/128 scram-sha-256
    - host monitoring icinga 192.168.72.28/32 scram-sha-256
    - host monitoring icinga 2001:638:700:1048::1c/128 scram-sha-256
    - host monitoring icinga 192.168.72.29/32 scram-sha-256
    - host monitoring icinga 2001:638:700:1048::1d/128 scram-sha-256
    - host all icinga 0.0.0.0/0 reject
    - host all icinga ::/0 reject
    - hostssl puppetdb puppetdb 192.168.72.16/28 cert map=puppetdb
    - hostssl puppetdb puppetdb 192.168.40.16/28 cert map=puppetdb
    - host postgres all 0.0.0.0/0 reject
    - host postgres all ::/0 reject
    - host monitoring all 0.0.0.0/0 reject
    - host monitoring all ::/0 reject
    - host all all 192.168.40.27/32 scram-sha-256
    - host all all 2001:638:700:1028::1b/128 scram-sha-256
    - host all all 192.168.40.28/32 scram-sha-256
    - host all all 2001:638:700:1028::1c/128 scram-sha-256
    - host all all 192.168.40.29/32 scram-sha-256
    - host all all 2001:638:700:1028::1d/128 scram-sha-256
    - host all all 192.168.72.27/32 scram-sha-256
    - host all all 2001:638:700:1048::1b/128 scram-sha-256
    - host all all 192.168.72.28/32 scram-sha-256
    - host all all 2001:638:700:1048::1c/128 scram-sha-256
    - host all all 192.168.72.29/32 scram-sha-256
    - host all all 2001:638:700:1048::1d/128 scram-sha-256
    - host all all 0.0.0.0/0 reject
    - host all all ::/0 reject
    pg_ident:
    - puppetdb it-puppet-pdb01.domain.de puppetdb
    - puppetdb it-puppet-pdb02.domain.de puppetdb
    authentication:
        replication:
            username: replicator
            password: REDACTED
        superuser:
            username: postgres
            password: REDACTED
    parameters:
        logging_collector: true
        log_directory: /var/log/patroni
        log_destination: "stderr"
        log_filename: postgresql.log
        log_min_messages: NOTICE
        log_min_error_statement: WARNING
        log_min_duration_statement: 60000
        client_min_messages: NOTICE
        shared_buffers: 6GB
        effective_cache_size: 12GB
        maintenance_work_mem: 1GB
        wal_buffers: 16MB
        work_mem: 40MB
        effective_io_concurrency: 200
        tcp_keepalives_count: 10
        tcp_keepalives_idle: 180
        tcp_keepalives_interval: 60
        archive_mode: on
        archive_timeout: 3600
        archive_command: "pgbackrest --stanza=puppet-db archive-push %p"
        shared_preload_libraries: pgaudit,pg_stat_statements,pg_trgm
        pgaudit.log: ROLE,DDL,MISC,MISC_SET
        track_io_timing: true
        log_timezone: "Europe/Berlin"
        timezone: "Europe/Berlin"
        default_text_search_config: "pg_catalog.english"
        max_wal_size: 8192
        ssl: true
        ssl_cert_file: /etc/patroni/client.pem
        ssl_key_file: /etc/patroni/client.key
        ssl_ca_file: /etc/patroni/ca.pem
    create_replica_methods:
        - pgbackrest
        - basebackup
    pgbackrest:
        command: /usr/bin/pgbackrest --stanza=puppet-db --delta restore
        keep_data: True
        no_params: True
    basebackup:
        max-rate: 100M

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

### patronictl show-config

```yaml
failsafe_mode: true
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    max_connections: 400
  recovery_conf:
    recovery_target_timeline: latest
    restore_command: /usr/bin/pgbackrest --stanza=puppet-db archive-get %f %p
```

### Patroni log files

```shell
no difference in output between both versions
```

### PostgreSQL log files

```shell
no difference in output between both versions
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

If you need any additional informations please let me know.

Thank you in advance!

Best regards,
Patrick
