### ISSUE TITLE
Getting pkg_resources.DistributionNotFound Error After Upgrading Python to 3.12

### ISSUE THREAD

**Issue by challagcp** [patroni/patroni#3195]
### What happened?

I installed Python 3.12 and started Patroni from the Python 3.12 environment, but I'm encountering the following error. It was functioning correctly with Python 3.6, and rolling back to Python 3.6 resolves the issue. Could you please help me understand which packages need to be installed to get Patroni running on Python 3.12? provided the list of packages installed on my machine below 
----**error**-----
/usr/bin/python3.12  /usr/bin/patroni /etc/patroni/patroni.yml
/usr/bin/patroni:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import load_entry_point
Traceback (most recent call last):
  File "/usr/bin/patroni", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.12/site-packages/pkg_resources/__init__.py", line 3327, in <module>
    @_call_aside
     ^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pkg_resources/__init__.py", line 3302, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.12/site-packages/pkg_resources/__init__.py", line 3340, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pkg_resources/__init__.py", line 631, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.12/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pkg_resources/__init__.py", line 829, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pkg_resources/__init__.py", line 870, in _resolve_dist
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'patroni==3.3.0' distribution was not found and is required by the application

```
**----- Installed Packages on the System -----**
python3.12.x86_64                            3.12.5-2.el8_10     
python3.12-PyMySQL.noarch                    1.1.0-3.el8_10      
python3.12-cffi.x86_64                       1.16.0-2.el8        
python3.12-charset-normalizer.noarch         3.3.0-2.el8         
python3.12-cryptography.x86_64               41.0.7-1.el8        
python3.12-devel.i686                        3.12.5-2.el8_10     
python3.12-devel.x86_64                      3.12.5-2.el8_10     
python3.12-idna.noarch                       3.4-2.el8           
python3.12-libs.i686                         3.12.5-2.el8_10     
python3.12-libs.x86_64                       3.12.5-2.el8_10     
python3.12-lxml.x86_64                       4.9.3-2.el8         
python3.12-mod_wsgi.x86_64                   4.9.4-2.el8         
python3.12-numpy.x86_64                      1.24.4-3.el8        
python3.12-numpy-f2py.x86_64                 1.24.4-3.el8        
python3.12-pip.noarch                        23.2.1-4.el8        
python3.12-pip-wheel.noarch                  23.2.1-4.el8        
python3.12-ply.noarch                        3.11-2.el8          
python3.12-psycopg2.x86_64                   2.9.6-2.el8         
python3.12-pycparser.noarch                  2.20-2.el8          
python3.12-pyyaml.x86_64                     6.0.1-2.el8         
python3.12-requests.noarch                   2.28.2-2.el8        
python3.12-rpm-macros.noarch                 3.12.5-2.el8_10     
python3.12-scipy.x86_64                      1.11.1-2.el8        
python3.12-setuptools.noarch                 68.2.2-4.el8_10     
python3.12-tkinter.x86_64                    3.12.5-2.el8_10     
python3.12-urllib3.noarch                    1.26.18-2.el8       
python3.12-wheel.noarch                      0.41.2-3.el8        

# Installed Packages for Specific Libraries
-----------------------------------------------
python3-libselinux.x86_64                    2.9-8.el8             
python3.12-devel.i686                        3.12.5-2.el8_10       
python3.12-devel.x86_64                      3.12.5-2.el8_10       
python3.12-psycopg2.x86_64                   2.9.6-2.el8           
python3.12-setuptools.noarch                 68.2.2-4.el8_10       
python3.12-pip.noarch                        23.2.1-4.el8          
python3.12-pip-wheel.noarch                  23.2.1-4.el8          
python3.12-urllib3.noarch                    1.26.18-2.el8         
patroni-consul.noarch                        3.3.0-1PGDG.rhel8
```     

### How can we reproduce it (as minimally and precisely as possible)?

Install Python 3.12.5 on RHEL 8 and attempt to start Patroni from the Python 3.12.5 environment and installed using RPM's.

- /usr/bin/python3.12  --version
  Python 3.12.5

### What did you expect to happen?

Patroni should be up and running. 

### Patroni/PostgreSQL/DCS version

-   Patroni version:  3.3.0
-   PostgreSQL version: 14
-   DCS (and its version):  consul and version v1.16.2

### Patroni configuration file

```yaml
scope: postgresql-patroni
name: postgresql-test1
namespace: /service

log:
  level: DEBUG
  traceback_level: ERROR
  format: '%(asctime)s %(levelname)s: %(message)s'
  dateformat: ''
  max_queue_size: 1000
  dir: /var/log/patroni
  file_num: 4
  file_size: 25000000
  loggers:
    patroni.postmaster: WARNING
    urllib3: WARNING

restapi:
  listen: localhost:8008
  connect_address: localhost:8008

consul:
  host: 127.0.0.1:8500
  token: 637cf05d-aad3-75b8-4851
  checks: []
  register_service: true

bootstrap:
  method: initdb
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: true
    synchronous_mode_strict: true
    synchronous_node_count: 1
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        max_connections: 100
        superuser_reserved_connections: 5
        max_locks_per_transaction: 512
        max_prepared_transactions: 0
        huge_pages: off
        shared_buffers: 1913MB
        effective_cache_size: 5739MB
        work_mem: 4MB
        maintenance_work_mem: 16MB
        checkpoint_timeout: 5min
        checkpoint_completion_target: 0.9
        min_wal_size: 80MB
        max_wal_size: 1GB
        wal_buffers: 4MB
        default_statistics_target: 100
        seq_page_cost: 1
        random_page_cost: 1.1
        effective_io_concurrency: 200
        synchronous_commit: on
        autovacuum: on
        autovacuum_max_workers: 3
        autovacuum_vacuum_threshold: 50
        autovacuum_vacuum_scale_factor: 0.2
        autovacuum_analyze_scale_factor: 0.1
        autovacuum_analyze_threshold: 50
        autovacuum_vacuum_cost_limit: -1
        autovacuum_vacuum_cost_delay: 2
        autovacuum_vacuum_insert_scale_factor: 0.2
        autovacuum_vacuum_insert_threshold: 1000
        autovacuum_naptime: 1min
        max_files_per_process: 4096
        archive_mode: on
        archive_timeout: 1800s
        archive_command: pgbackrest --stanza=pg_stanza archive-push %p
        wal_level: replica
        wal_keep_size: 2GB
        max_wal_senders: 10
        max_replication_slots: 10
        hot_standby: on
        wal_log_hints: on
        wal_compression: off
        shared_preload_libraries: pg_stat_statements
        pg_stat_statements.max: 10000
        pg_stat_statements.track: all
        pg_stat_statements.track_utility: false
        pg_stat_statements.save: true
        track_io_timing: on
        log_lock_waits: on
        log_temp_files: 0
        track_activities: on
        track_activity_query_size: 4096
        track_counts: on
        track_functions: all
        log_checkpoints: on
        logging_collector: on
        log_truncate_on_rotation: on
        log_rotation_age: 1d
        log_rotation_size: 0
        log_line_prefix: '%t [%p-%l] %r %q%u@%d '
        log_filename: postgresql-%a.log
        log_directory: /var/log/postgresql
        hot_standby_feedback: on
        max_standby_streaming_delay: 30s
        wal_receiver_status_interval: 10s
        idle_in_transaction_session_timeout: 0
        ssl: 'on'
        ssl_ca_file: /var/lib/pgsql/14/data/CA.crt
        ssl_cert_file: /var/lib/pgsql/14/data/wildcard.crt
        ssl_key_file: /var/lib/pgsql/14/data/wildcard.key
        jit: off
        max_worker_processes: 8
        max_parallel_workers: 8
        max_parallel_workers_per_gather: 2
        max_parallel_maintenance_workers: 2
    standby_cluster:
      host: 10.50.02.07
      port: 5432


  initdb:  # List options to be passed on to initdb
    - encoding: UTF8
    - locale: en_US.UTF-8
    - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
    - host replication replicator 127.0.0.1/32 scram-sha-256
    
postgresql:
  listen: 127.0.0.1:5432
  connect_address: localhost:5432
  use_unix_socket: true
  data_dir: /var/lib/pgsql/14/data
  bin_dir: /usr/pgsql-14/bin
  config_dir: /var/lib/pgsql/14/data
  pgpass: /var/lib/pgsql/
  authentication:
    replication:
      username: replicator
      password: 
    superuser:
      username: postgres
      password: 
  parameters:
    unix_socket_directories: /var/run/postgresql
    stats_temp_directory: /var/lib/pgsql_stats_tmp


  remove_data_directory_on_rewind_failure: true
  remove_data_directory_on_diverged_timelines: true

  create_replica_methods:
    - basebackup
    - pgbackrest
  pgbackrest:
    command: /usr/bin/pgbackrest --stanza=pg_stanza --log-level-file=detail --delta restore
    keep_data: true
    no_params: true
  basebackup:
    max-rate: '100M'
    checkpoint: 'fast'

  recovery_conf:
    restore_command: pgbackrest --stanza=pg_stanza archive-get %f %p

watchdog:
  mode: automatic  # Allowed values: off, automatic, required
  device: /dev/watchdog  # Path to the watchdog device
  safety_margin: 5

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false

  # specify a node to replicate from (cascading replication)
#  replicatefrom: (node name)
```

### patronictl show-config

```yaml
same as above
```

### Patroni log files

```shell
Started Runners to orchestrate a high-availability PostgreSQL.
 patroni.service: Main process exited, code=exited, status=203/EXEC
 patroni.service: Failed with result 'exit-code'.
 Started Runners to orchestrate a high-availability PostgreSQL.
 patroni.service: Main process exited, code=exited, status=203/EXEC
 patroni.service: Failed with result 'exit-code'.
```

### PostgreSQL log files

```shell
NA
```

### Have you tried to use GitHub issue search?

- [X] Yes
