### ISSUE TITLE
Thread leak in patronictl list -W

### ISSUE THREAD

**Issue by bjh21** [patroni/patroni#3202]
### What happened?

When running `patronictl list -W`, the number of threads in the patronictl process increases without bound.  Eventually (after some hours), patronictl exits with an error:

```
Traceback (most recent call last):
  File "./pv/bin/patronictl", line 8, in <module>
    sys.exit(ctl())
  File "/root/pv/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/root/pv/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/root/pv/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/pv/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/pv/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/root/pv/lib/python3.8/site-packages/patroni/ctl.py", line 1648, in members
    dcs = get_dcs(cluster_name, group)
  File "/root/pv/lib/python3.8/site-packages/patroni/ctl.py", line 354, in get_dcs
    dcs = _get_dcs(config)
  File "/root/pv/lib/python3.8/site-packages/patroni/dcs/__init__.py", line 137, in get_dcs
    return dcs_class(config[name], get_mpp(config))
  File "/root/pv/lib/python3.8/site-packages/patroni/dcs/etcd3.py", line 665, in __init__
    super(Etcd3, self).__init__(config, mpp, PatroniEtcd3Client,
  File "/root/pv/lib/python3.8/site-packages/patroni/dcs/etcd.py", line 484, in __init__
    self._abstract_client = self.get_etcd_client(config, client_cls)
  File "/root/pv/lib/python3.8/site-packages/patroni/dcs/etcd.py", line 583, in get_etcd_client
    dns_resolver = DnsCachingResolver()
  File "/root/pv/lib/python3.8/site-packages/patroni/dcs/etcd.py", line 60, in __init__
    self.start()
  File "/usr/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```

### How can we reproduce it (as minimally and precisely as possible)?

Given a running Patroni installation with configuration in `/etc/patroni/16-main.yml` (to provide a convenient API endpoint):

`virtualenv pv`
`./pv/bin/pip install patroni[psycopg2-binary,etcd3]`
`./pv/bin/patronictl -c /etc/patroni/16-main.yml list -W`

`watch "ps -LfC patronictl | wc -l"`
Watch the number increase. When it reaches about 10,000 (on a standard Ubuntu installation), `patronictl` will exit. To make it happen faster, run multiple copies of `patronictl` in parallel.

### What did you expect to happen?

`patronictl list -W` should run indefinitely without ever running out of threads, and the output from `ps -LfC patronictl | wc -l` should be stable.

### Patroni/PostgreSQL/DCS version

-   Patroni version: patronictl 4.0.3 talking to patroni 4.0.2-1.pgdg20.04+1
-   PostgreSQL version: 16.4 (Ubuntu 16.4-1.pgdg20.04+2)
-   DCS (and its version): etcd 3.2.26+dfsg-6ubuntu0.2

### Patroni configuration file

```yaml
# WARNING: File managed by Ansible: https://wiki.cam.ac.uk/uis/Platforms_Ansible
scope: "16-main"
namespace: "/postgresql-common/"
name: "moa-dev-patroni1"

etcd3:
  host: 127.0.0.1:2379

restapi:
  listen: :::8008
  connect_address: 172.28.208.105:8008
  certfile: /etc/moa-tls/patroni.crt
  keyfile: /etc/moa-tls/patroni.key
  cafile: /etc/moa-tls/ca/ca.crt
  verify_client: optional

ctl:
  cacert: /etc/moa-tls/ca/ca.crt
  certfile: /etc/moa-tls/patroni.crt
  keyfile: /etc/moa-tls/patroni.key

bootstrap:
  # Custom bootstrap method
  method: pg_createcluster
  pg_createcluster:
    command: /usr/share/patroni/pg_createcluster_patroni
  post_init: /etc/patroni/post-init

  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  # and all other cluster members will use it as a `global configuration`
  dcs: {"ttl": 30, "loop_wait": 10, "retry_timeout": 10, "master_stop_timeout": 30, "maximum_lag_on_failover": 1048576, "synchronous_mode": true, "postgresql": {"use_pg_rewind": false, "remove_data_directory_on_rewind_failure": true, "remove_data_directory_on_diverged_timelines": true, "use_slots": false, "parameters": {"ssl_cert_file": "/etc/moa-tls/postgresql.crt", "ssl_key_file": "/etc/moa-tls/postgresql.key", "ssl_min_protocol_version": "TLSv1", "password_encryption": "scram-sha-256", "wal_level": "logical", "log_connections": true, "log_disconnections": true, "log_destination": "syslog", "log_min_messages": "log", "logging_collector": false, "shared_buffers": "256MB"}, "pg_hba": ["local      all,replication  all                  peer map=local", "hostssl    replication      moa_replicator  all  scram-sha-256", "hostssl    postgres         moa_rewind      all  scram-sha-256", "hostssl    all,replication  all             all  md5", "hostnossl  all,replication  +moa_nossl      all  md5"], "pg_ident": ["local root moa_superuser", "local postgres moa_superuser", "local postgres moa_replicator", "local postgres moa_rewind", "local root moa_collectd", "local dump moa_superuser"]}}

postgresql:
  # Custom clone method
  create_replica_method:
    - pg_clonecluster
  pg_clonecluster:
    command: /usr/share/patroni/pg_clonecluster_patroni

  # Listen on all local addresses.  Note that Patroni extracts the port
  # number by looking for the last ':', so the IPv6 address won't
  # confuse it.
  listen: "::,0.0.0.0:5432"
  connect_address: 172.28.208.105:5432
  use_unix_socket: true
  data_dir: /var/lib/postgresql/16/main
  bin_dir: /usr/lib/postgresql/16/bin
  config_dir: /etc/postgresql/16/main
  pgpass: /var/lib/postgresql/16-main.pgpass
  authentication:
    replication:
      username: moa_replicator
      password: "<censored>"
      sslmode: verify-ca
    rewind:
      username: moa_rewind
      password: "<censored>"
      sslmode: verify-ca
# A superuser role is required in order for Patroni to manage the local
# Postgres instance.  If the option `use_unix_socket' is set to `true', then
# specifying an empty password results in no md5 password for the superuser
# being set and sockets being used for authentication. The `password:' line is
# nevertheless required.  Note that pg_rewind will not work if no md5 password
# is set.
    superuser:
      username: moa_superuser
      password:
  parameters:
    unix_socket_directories: '/var/run/postgresql/'
    # Emulate default Debian/Ubuntu logging
    logging_collector: 'on'
    log_directory: '/var/log/postgresql'
    log_filename: 'postgresql-16-main.log'
```

### patronictl show-config

```yaml
loop_wait: 10
master_stop_timeout: 30
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    log_connections: true
    log_destination: syslog
    log_disconnections: true
    log_min_messages: log
    logging_collector: false
    password_encryption: scram-sha-256
    shared_buffers: 256MB
    shared_preload_libraries: timescaledb
    ssl_cert_file: /etc/moa-tls/postgresql.crt
    ssl_key_file: /etc/moa-tls/postgresql.key
    ssl_min_protocol_version: TLSv1
    timescaledb.license_key: CommunityLicense
    wal_level: logical
  pg_hba:
  - local      all,replication  all                  peer map=local
  - hostssl    replication      moa_replicator  all  scram-sha-256
  - hostssl    postgres         moa_rewind      all  scram-sha-256
  - hostssl    all,replication  all             all  md5
  - hostnossl  all,replication  +moa_nossl      all  md5
  pg_ident:
  - local root moa_superuser
  - local postgres moa_superuser
  - local postgres moa_replicator
  - local postgres moa_rewind
  - local root moa_collectd
  - local dump moa_superuser
  remove_data_directory_on_diverged_timelines: true
  remove_data_directory_on_rewind_failure: true
  use_pg_rewind: false
  use_slots: false
retry_timeout: 10
synchronous_mode: true
ttl: 30
```

### Patroni log files

```shell
n/a (patronictl problem)
```

### PostgreSQL log files

```shell
n/a (patronictl problem)
```

### Have you tried to use GitHub issue search?

- [X] Yes
