### ISSUE TITLE
same node showing as Primary and Sync standby

### ISSUE THREAD

**Issue by challagcp** [patroni/patroni#3203]
### What happened?

can-postgressdb1 node is acting as the leader, and in the PostgreSQL logs, it shows the same node as the sync standby.Please find the below.

When I perform a failover to another node, everything works correctly. However, I would like to understand why this behavior is occurring for these specific node.

```
2024-11-08 21:27:55 IST [1457128-11] LOG: received SIGHUP, reloading configuration files  
2024-11-08 21:27:55 IST [1457128-12] LOG: parameter "synchronous_standby_names" changed to "can-postgressdb1"  
2024-11-08 21:32:44 IST [1457137-3] LOG: checkpoint starting: time  
```
--

```
+ Cluster: on-canary (7365165270282575371) ---------------------------------+---------+
| Member           | Host                  | Role    | State    | TL | Lag in MB |
+------------------+-----------------------+---------+----------+----+-----------+
| can-postgressdb0 | can-postgressdb0       | Replica | streaming | 28 | 0         |
| can-postgressdb1 | can-postgressdb1       | Leader  | running   | 28 |           |
| can-postgressdb2 | can-postgressdb2       | Replica | streaming | 28 | 0         |
+------------------+-----------------------+---------+----------+----+-----------+

```

### How can we reproduce it (as minimally and precisely as possible)?

Not sure.

### What did you expect to happen?

sync standby should be another node name

### Patroni/PostgreSQL/DCS version

Patroni version: 3.3.0
PostgreSQL version: 14
DCS (and its version): consul and version v1.16.2

### Patroni configuration file

```yaml
scope: postgresql-patroni
name: postgresql-test1
namespace: /service

log:
  level: DEBUG
  traceback_level: ERROR
  format: '%(asctime)s %(levelname)s: %(message)s'
  dateformat: ''
  max_queue_size: 1000
  dir: /var/log/patroni
  file_num: 4
  file_size: 25000000
  loggers:
    patroni.postmaster: WARNING
    urllib3: WARNING

restapi:
  listen: localhost:8008
  connect_address: localhost:8008

consul:
  host: 127.0.0.1:8500
  token: 637cf05d-aad3-75b8-4851
  checks: []
  register_service: true

bootstrap:
  method: initdb
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: true
    synchronous_mode_strict: true
    synchronous_node_count: 1
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        max_connections: 100
        superuser_reserved_connections: 5
        max_locks_per_transaction: 512
        max_prepared_transactions: 0
        huge_pages: off
        shared_buffers: 1913MB
        effective_cache_size: 5739MB
        work_mem: 4MB
        maintenance_work_mem: 16MB
        checkpoint_timeout: 5min
        checkpoint_completion_target: 0.9
        min_wal_size: 80MB
        max_wal_size: 1GB
        wal_buffers: 4MB
        default_statistics_target: 100
        seq_page_cost: 1
        random_page_cost: 1.1
        effective_io_concurrency: 200
        synchronous_commit: on
        autovacuum: on
        autovacuum_max_workers: 3
        autovacuum_vacuum_threshold: 50
        autovacuum_vacuum_scale_factor: 0.2
        autovacuum_analyze_scale_factor: 0.1
        autovacuum_analyze_threshold: 50
        autovacuum_vacuum_cost_limit: -1
        autovacuum_vacuum_cost_delay: 2
        autovacuum_vacuum_insert_scale_factor: 0.2
        autovacuum_vacuum_insert_threshold: 1000
        autovacuum_naptime: 1min
        max_files_per_process: 4096
        archive_mode: on
        archive_timeout: 1800s
        archive_command: pgbackrest --stanza=pg_stanza archive-push %p
        wal_level: replica
        wal_keep_size: 2GB
        max_wal_senders: 10
        max_replication_slots: 10
        hot_standby: on
        wal_log_hints: on
        wal_compression: off
        shared_preload_libraries: pg_stat_statements
        pg_stat_statements.max: 10000
        pg_stat_statements.track: all
        pg_stat_statements.track_utility: false
        pg_stat_statements.save: true
        track_io_timing: on
        log_lock_waits: on
        log_temp_files: 0
        track_activities: on
        track_activity_query_size: 4096
        track_counts: on
        track_functions: all
        log_checkpoints: on
        logging_collector: on
        log_truncate_on_rotation: on
        log_rotation_age: 1d
        log_rotation_size: 0
        log_line_prefix: '%t [%p-%l] %r %q%u@%d '
        log_filename: postgresql-%a.log
        log_directory: /var/log/postgresql
        hot_standby_feedback: on
        max_standby_streaming_delay: 30s
        wal_receiver_status_interval: 10s
        idle_in_transaction_session_timeout: 0
        ssl: 'on'
        ssl_ca_file: /var/lib/pgsql/14/data/CA.crt
        ssl_cert_file: /var/lib/pgsql/14/data/wildcard.crt
        ssl_key_file: /var/lib/pgsql/14/data/wildcard.key
        jit: off
        max_worker_processes: 8
        max_parallel_workers: 8
        max_parallel_workers_per_gather: 2
        max_parallel_maintenance_workers: 2
    standby_cluster:
      host: 10.50.02.07
      port: 5432


  initdb:  # List options to be passed on to initdb
    - encoding: UTF8
    - locale: en_US.UTF-8
    - data-checksums

  pg_hba:  # Add following lines to pg_hba.conf after running 'initdb'
    - host replication replicator 127.0.0.1/32 scram-sha-256
    
postgresql:
  listen: 127.0.0.1:5432
  connect_address: localhost:5432
  use_unix_socket: true
  data_dir: /var/lib/pgsql/14/data
  bin_dir: /usr/pgsql-14/bin
  config_dir: /var/lib/pgsql/14/data
  pgpass: /var/lib/pgsql/
  authentication:
    replication:
      username: replicator
      password: 
    superuser:
      username: postgres
      password: 
  parameters:
    unix_socket_directories: /var/run/postgresql
    stats_temp_directory: /var/lib/pgsql_stats_tmp


  remove_data_directory_on_rewind_failure: true
  remove_data_directory_on_diverged_timelines: true

  create_replica_methods:
    - basebackup
    - pgbackrest
  pgbackrest:
    command: /usr/bin/pgbackrest --stanza=pg_stanza --log-level-file=detail --delta restore
    keep_data: true
    no_params: true
  basebackup:
    max-rate: '100M'
    checkpoint: 'fast'

  recovery_conf:
    restore_command: pgbackrest --stanza=pg_stanza archive-get %f %p

watchdog:
  mode: automatic  # Allowed values: off, automatic, required
  device: /dev/watchdog  # Path to the watchdog device
  safety_margin: 5

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false

  # specify a node to replicate from (cascading replication)
#  replicatefrom: (node name)
```

### patronictl show-config

```yaml
same as above
```

### Patroni log files

```shell
NA
```

### PostgreSQL log files

```shell
2024-11-08 21:27:47 IST [1457179-1] (57524) replicator@[unknown] LOG:  standby "can-postgressdb1" is now a synchronous standby with priority 1
2024-11-08 21:27:47 IST [1457179-2] (57524) replicator@[unknown] STATEMENT:  START_REPLICATION 21/CF000000 TIMELINE 27
2024-11-08 21:27:48 IST [1457184-1] (47536) replicator@[unknown] LOG:  standby "can-postgressdb2" is now a synchronous standby with priority 1
2024-11-08 21:27:48 IST [1457184-2] (47536) replicator@[unknown] STATEMENT:  START_REPLICATION SLOT "can_postgressdb2" 21/CF000000 TIMELINE 28
2024-11-08 21:27:55 IST [1457128-11]  LOG:  received SIGHUP, reloading configuration files
2024-11-08 21:27:55 IST [1457128-12]  LOG:  parameter "synchronous_standby_names" changed to ""can-postgressdb1""
2024-11-08 21:32:44 IST [1457137-3]  LOG:  checkpoint starting: time
```

### Have you tried to use GitHub issue search?

- [X] Yes
