### ISSUE TITLE
ERROR: [087]: archive_mode must be enabled

### ISSUE THREAD

**Issue by germebl** [patroni/patroni#3225]
### What happened?

The error `ERROR: [087]: archive_mode must be enabled` appears when trying to take a backup with `sudo -iu postgres pgbackrest --stanza=cluster_1 --type=full backup`

### How can we reproduce it (as minimally and precisely as possible)?

I followed the following instructions to setup a patroni cluster with pgbackrest on a dedicated backup server:
https://docs.percona.com/postgresql/17/solutions/ha-setup-apt.html
https://docs.percona.com/postgresql/17/solutions/pgbackrest.html

### What did you expect to happen?

The archive_mode is set correctly as set within the patroni static config.

### Patroni/PostgreSQL/DCS version

-   Patroni version: patroni 4.0.2
-   PostgreSQL version: psql (PostgreSQL) 17.0 - Percona Server for PostgreSQL 17.0.1
-   DCS (and its version): etcdctl version: 3.5.16 / API version: 3.5

### Patroni configuration file

```yaml
namespace: percona_lab
scope: cluster_1
name: pgsql-1

restapi:
    listen: 0.0.0.0:8008
    connect_address: 10.1.202.5:8008

etcd3:
    host: 10.1.202.5:2379

bootstrap:
  post_bootstrap: /opt/post_bootstrap.sh
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  dcs:
      ttl: 30
      loop_wait: 10
      retry_timeout: 10
      maximum_lag_on_failover: 1048576

      postgresql:
          use_pg_rewind: true
          use_slots: true
          parameters:
              wal_level: replica
              hot_standby: on
              wal_keep_segments: 10
              max_wal_senders: 5
              max_replication_slots: 10
              wal_log_hints: on
              logging_collector: 'on'
              max_wal_size: '10GB'
              archive_mode: on
              archive_timeout: 600s
              archive_command: pgbackrest --stanza=cluster_1 archive-push /var/lib/postgresql/17/main/pg_wal/%f
          recovery_conf:
            restore_command: pgbackrest --stanza=main archive-get %f %p

  # some desired options for 'initdb'
  initdb: # Note: It needs to be a list (some options need values, others are switches)
      - encoding: UTF8
      - data-checksums

  pg_hba: # Add following lines to pg_hba.conf after running 'initdb'
      - host replication replicator 127.0.0.1/32 trust
      - host replication replicator 0.0.0.0/0 md5
      - host all all 0.0.0.0/0 md5
      - host all all ::0/0 md5
      - hostssl  all  all  10.1.201.0/24  cert

postgresql:
    cluster_name: cluster_1
    listen: 0.0.0.0:5432
    connect_address: 10.1.202.5:5432
    data_dir: /var/lib/postgresql/17/main
    bin_dir: /usr/lib/postgresql/17/bin
    pgpass: /tmp/pgpass0
    authentication:
        replication:
            username: replicator
            password: 'hiengooziegaiv5doh5hu3ooBi0phahM'
        superuser:
            username: postgres
            password: heyday_r0ck
    parameters:
        unix_socket_directories: /var/run/postgresql/
    create_replica_methods:
        - basebackup
    basebackup:
        checkpoint: 'fast'

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

### patronictl show-config

```yaml
bootstrap:
  dcs:
    loop_wait: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      parameters:
        archive_command: pgbackrest --stanza=cluster_1 archive-push /var/lib/postgresql/17/main/pg_wal/%f
        archive_mode: true
        archive_timeout: 600s
        hot_standby: true
        logging_collector: 'on'
        max_replication_slots: 10
        max_wal_senders: 5
        max_wal_size: 10GB
        wal_keep_segments: 10
        wal_level: replica
        wal_log_hints: true
      recovery_conf:
        restore_command: pgbackrest --stanza=main archive-get %f %p
      use_pg_rewind: true
      use_slots: true
    retry_timeout: 10
    ttl: 30
  initdb:
  - encoding: UTF8
  - data-checksums
  pg_hba:
  - host replication replicator 127.0.0.1/32 trust
  - host replication replicator 0.0.0.0/0 md5
  - host all all 0.0.0.0/0 md5
  - host all all ::0/0 md5
  post_bootstrap: /opt/post_bootstrap.sh
etcd3:
  host: 10.1.202.5:2379
name: pgsql-1
namespace: percona_lab
postgresql:
  authentication:
    replication:
      password: bestpasswordintheworld
      username: replicator
    superuser:
      password: bestpasswordintheworld
      username: postgres
  basebackup:
    checkpoint: fast
  bin_dir: /usr/lib/postgresql/17/bin
  cluster_name: cluster_1
  connect_address: 10.1.202.5:5432
  create_replica_methods:
  - basebackup
  data_dir: /var/lib/postgresql/17/main
  listen: 0.0.0.0:5432
  parameters:
    unix_socket_directories: /var/run/postgresql/
  pgpass: /tmp/pgpass0
restapi:
  connect_address: 10.1.202.5:8008
  listen: 0.0.0.0:8008
scope: cluster_1
tags:
  clonefrom: false
  nofailover: false
  noloadbalance: false
  nosync: false
```

### Patroni log files

```shell
no relevant logs from patroni
```

### PostgreSQL log files

```shell
no relevant logs from postgresql
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

The issue happens when trying to run the following command on the pgbackrest backup server:
```
sudo -iu postgres pgbackrest --stanza=cluster_1 --type=full backup
```

Error that appears:
```
ERROR: [087]: archive_mode must be enabled
```

But when you check the patroni configuration, the archive_mode is set to `on` and there is no outstanding restart:
```
# patronictl -c /etc/patroni/patroni.yml list

+ Cluster: cluster_1 (7441327763677851860) --+----+-----------+
| Member  | Host       | Role    | State     | TL | Lag in MB |
+---------+------------+---------+-----------+----+-----------+
| pgsql-1 | 10.1.202.5 | Replica | streaming |  9 |         0 |
| pgsql-2 | 10.1.202.6 | Leader  | running   |  9 |           |
| pgsql-3 | 10.1.202.7 | Replica | streaming |  9 |         0 |
+---------+------------+---------+-----------+----+-----------+
```

When i check the postgresql.conf i can see, that it is not turned on:
```
#archive_mode = off		# enables archiving; off, on, or always
```

**Comment by CyberDem0n** [comment]
It is not a Patroni problem.
You have to properly configure PostgreSQL by setting archive_mode = on.

**Comment by CyberDem0n** [comment]
> So i would still say, it's a patroni thing.... If not, can you tell me what i'm getting wrong?

Lets start from `patronictl show-config` output.
Did you execute the command or just copy&paste patroni.yaml once again?
If the first one - the content is just wrong, because there should be just a subtree of `bootstrap.dcs`.

**Comment by germebl** [comment]
Thats the .yaml:
```
namespace: percona_lab
scope: cluster_1
name: pgsql-1

restapi:
    listen: 0.0.0.0:8008
    connect_address: 10.1.202.5:8008

etcd3:
    host: 10.1.202.5:2379

bootstrap:
  post_bootstrap: /opt/post_bootstrap.sh
  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  dcs:
      ttl: 30
      loop_wait: 10
      retry_timeout: 10
      maximum_lag_on_failover: 1048576

      postgresql:
          use_pg_rewind: true
          use_slots: true
          parameters:
              wal_level: replica
              hot_standby: on
              wal_keep_segments: 10
              max_wal_senders: 5
              max_replication_slots: 10
              wal_log_hints: on
              logging_collector: 'on'
              max_wal_size: '10GB'
              archive_mode: on
              archive_timeout: 600s
              archive_command: pgbackrest --stanza=cluster_1 archive-push /var/lib/postgresql/17/main/pg_wal/%f
          recovery_conf:
            restore_command: pgbackrest --stanza=main archive-get %f %p

  # some desired options for 'initdb'
  initdb: # Note: It needs to be a list (some options need values, others are switches)
      - encoding: UTF8
      - data-checksums

  pg_hba: # Add following lines to pg_hba.conf after running 'initdb'
      - host replication replicator 127.0.0.1/32 trust
      - host replication replicator 0.0.0.0/0 md5
      - host all all 0.0.0.0/0 md5
      - host all all ::0/0 md5
      - hostssl  all  all  10.1.201.0/24  cert

postgresql:
    cluster_name: cluster_1
    listen: 0.0.0.0:5432
    connect_address: 10.1.202.5:5432
    data_dir: /var/lib/postgresql/17/main
    bin_dir: /usr/lib/postgresql/17/bin
    pgpass: /tmp/pgpass0
    authentication:
        replication:
            username: replicator
            password: 'hiengooziegaiv5doh5hu3ooBi0phahM'
        superuser:
            username: postgres
            password: heyday_r0ck
    parameters:
        unix_socket_directories: /var/run/postgresql/
    create_replica_methods:
        - basebackup
    basebackup:
        checkpoint: 'fast'

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

Thats the show-config command:
```
root@pgsql-1:/etc/ssl/certs/pg_ha# patronictl show-config
Error: Can not find suitable configuration of distributed configuration store
Available implementations: etcd, etcd3, kubernetes, raft
root@pgsql-1:/etc/ssl/certs/pg_ha# patronictl -c /etc/patroni/patroni.yml show-config
bootstrap:
  dcs:
    loop_wait: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      parameters:
        archive_command: pgbackrest --stanza=cluster_1 archive-push /var/lib/postgresql/17/main/pg_wal/%f
        archive_mode: true
        archive_timeout: 600s
        hot_standby: true
        logging_collector: 'on'
        max_replication_slots: 10
        max_wal_senders: 5
        max_wal_size: 10GB
        wal_keep_segments: 10
        wal_level: replica
        wal_log_hints: true
      recovery_conf:
        restore_command: pgbackrest --stanza=main archive-get %f %p
      use_pg_rewind: true
      use_slots: true
    retry_timeout: 10
    ttl: 30
  initdb:
  - encoding: UTF8
  - data-checksums
  pg_hba:
  - host replication replicator 127.0.0.1/32 trust
  - host replication replicator 0.0.0.0/0 md5
  - host all all 0.0.0.0/0 md5
  - host all all ::0/0 md5
  post_bootstrap: /opt/post_bootstrap.sh
etcd3:
  host: 10.1.202.5:2379
name: pgsql-1
namespace: percona_lab
postgresql:
  authentication:
    replication:
      password: hiengooziegaiv5doh5hu3ooBi0phahM
      username: replicator
    superuser:
      password: heyday_r0ck
      username: postgres
  basebackup:
    checkpoint: fast
  bin_dir: /usr/lib/postgresql/17/bin
  cluster_name: cluster_1
  connect_address: 10.1.202.5:5432
  create_replica_methods:
  - basebackup
  data_dir: /var/lib/postgresql/17/main
  listen: 0.0.0.0:5432
  parameters:
    unix_socket_directories: /var/run/postgresql/
  pgpass: /tmp/pgpass0
restapi:
  connect_address: 10.1.202.5:8008
  listen: 0.0.0.0:8008
scope: cluster_1
tags:
  clonefrom: false
  nofailover: false
  noloadbalance: false
  nosync: false
```

While just `patronictl show config` ends in:
```
Error: Can not find suitable configuration of distributed configuration store
Available implementations: etcd, etcd3, kubernetes, raft
```

I need to run:
```
patronictl -c /etc/patroni/patroni.yml show-config
```

To get the output above.

**Comment by CyberDem0n** [comment]
> I need to run:

Right, and the documentation explains it: https://patroni.readthedocs.io/en/latest/patronictl.html

>Thats the show-config command:

As I said - this is wrong.
There should be only content of `bootstrap.dcs`, or the following:
```yaml
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: pgbackrest --stanza=cluster_1 archive-push /var/lib/postgresql/17/main/pg_wal/%f
    archive_mode: true
    archive_timeout: 600s
    hot_standby: true
    logging_collector: 'on'
    max_replication_slots: 10
    max_wal_senders: 5
    max_wal_size: 10GB
    wal_keep_segments: 10
    wal_level: replica
    wal_log_hints: true
  recovery_conf:
    restore_command: pgbackrest --stanza=main archive-get %f %p
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
ttl: 30
```
