### ISSUE TITLE
Patroni and pgBackRest: cannot restore a backup and reinit without a new backup

### ISSUE THREAD

**Issue by mmartinello** [patroni/patroni#3227]
### What happened?

I am making some tests on pgBackRest with Patroni running on a 3-node PostgreSQL 17 cluster, and I am hitting a couple of main problems:

## Reinit problem:

Patroni nodes are able to reinit themselves from pgBackRest, but only if the timeline has not been changed, else I need to make a new full or incremental backup on pgBackRest to have the reinit working again. I did not find any documentation which tells that this is expected. I don't think it is, so I wrote to the pgBackRest issue tracker (https://github.com/pgbackrest/pgbackrest/issues/2474) but they told me that this is not a problem related to pgBackRest but rather to PostgreSQL and/or Patroni.

## Restore problem:

When trying to restore a pgBackRest backup to a standalone PostgreSQL installation, the pgBackRest restore command finishes with no errors, but PostgreSQL does not start up at all and returns the following errors:

```
postgresql-1            |
postgresql-1            | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgresql-1            |
postgresql-1            | 2024-11-12 18:48:26.792 UTC [1] LOG:  starting PostgreSQL 17.0 (Debian 17.0-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgresql-1            | 2024-11-12 18:48:26.792 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgresql-1            | 2024-11-12 18:48:26.793 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgresql-1            | 2024-11-12 18:48:26.796 UTC [16] LOG:  database system was interrupted; last known up at 2024-11-12 17:15:37 UTC
postgresql-1            | 2024-11-12 18:48:26.896 UTC [16] LOG:  starting backup recovery with redo LSN 1A0/760000D8, checkpoint LSN 1A0/76000130, on timeline ID 6
postgresql-1            | 2024-11-12 18:48:26.896 UTC [16] LOG:  invalid checkpoint record
postgresql-1            | 2024-11-12 18:48:26.896 UTC [16] FATAL:  could not locate required checkpoint record at 1A0/76000130
postgresql-1            | 2024-11-12 18:48:26.896 UTC [16] HINT:  If you are restoring from a backup, touch "/var/lib/postgresql/patroni-pg17/data/recovery.signal" or "/var/lib/postgresql/patroni-pg17/data/standby.signal" and add required recovery options.
postgresql-1            | 	If you are not restoring from a backup, try removing the file "/var/lib/postgresql/patroni-pg17/data/backup_label".
postgresql-1            | 	Be careful: removing "/var/lib/postgresql/patroni-pg17/data/backup_label" will result in a corrupt cluster if restoring from a backup.
postgresql-1            | 2024-11-12 18:48:26.897 UTC [1] LOG:  startup process (PID 16) exited with exit code 1
postgresql-1            | 2024-11-12 18:48:26.897 UTC [1] LOG:  aborting startup due to startup process failure
postgresql-1            | 2024-11-12 18:48:26.898 UTC [1] LOG:  database system is shut down
Could you help me to figure out where I am going wrong, please?
```

## Reinit problem:

- Install Patroni, PostgreSQL and pgBackRest and configure them
- Start a full backup with pgBackRest and expect it to finish
- Execute a switchover on Patroni, wait the switchover to be executed, check the leader node to be changed, check the TL to be increased by 1
- Execute a reinit on one replica node
- See that the reinit will never complete and check errors in the Patroni log file
- Start a new full or incremental backup with pgBackRest and expect it to finish
- Execute a reinit on one replica node
- Check that the reinit will be completed correctly

# Restore problem:

- Restore a backup from pgBackRest to a new standalone single-node PostgreSQL 17 instance
- Start the new PostgreSQL 17 instance
- See the PosthreSQL shutdown and the error

## Reinit problem:

I expect that a reinit will complete successfully even if I do not execute a new full or incremental backup on pbBackRest after the TL to be increased.

## Restore problem:

I expect that a new single-node PostgreSQL instance would be able to start on the new datadir after the restore to be successfully completed.

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.3.4
-   PostgreSQL version: 17.0
-   DCS (and its version): etcd 3.4.34

### Patroni configuration file

```yaml
# Patroni configuration file

scope: dev_pg17
#namespace: /service/
name: postgres1

restapi:
  listen: 127.0.0.1:8008
  connect_address: 127.0.0.1:8008
#  cafile: /etc/ssl/certs/ssl-cacert-snakeoil.pem
#  certfile: /etc/ssl/certs/ssl-cert-snakeoil.pem
#  keyfile: /etc/ssl/private/ssl-cert-snakeoil.key
#  authentication:
#    username: username
#    password: password

#ctl:
#  insecure: false # Allow connections to Patroni REST API without verifying certificates
#  certfile: /etc/ssl/certs/ssl-cert-snakeoil.pem
#  keyfile: /etc/ssl/private/ssl-cert-snakeoil.key
#  cacert: /etc/ssl/certs/ssl-cacert-snakeoil.pem

#citus:
#  database: citus
#  group: 0  # coordinator

etcd:
  #Provide host to do the initial discovery of the cluster topology:
  #host: 127.0.0.1:2379
  #Or use "hosts" to provide multiple endpoints
  #Could be a comma separated string:
  #hosts: host1:port1,host2:port2
  #or an actual yaml list:
  #hosts:
  #- host1:port1
  #- host2:port2
  #Once discovery is complete Patroni will use the list of advertised clientURLs
  #It is possible to change this behavior through by setting:
  #use_proxies: true

#raft:
#  data_dir: .
#  self_addr: 127.0.0.1:2222
#  partner_addrs:
#  - 127.0.0.1:2223
#  - 127.0.0.1:2224

# The bootstrap configuration. Works only when the cluster is not yet initialized.
# If the cluster is already initialized, all changes in the `bootstrap` section are ignored!
bootstrap:
  # This section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  # and all other cluster members will use it as a `global configuration`.
  # WARNING! If you want to change any of the parameters that were set up
  # via `bootstrap.dcs` section, please use `patronictl edit-config`!
  dcs:
    ignore_slots:
    - name: barman
      type: physical
    slots:
      postgres1:
        type: physical
      postgres:
        type: physical
      postgres:
        type: physical
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
#    primary_start_timeout: 300
#    synchronous_mode: false
    #standby_cluster:
      #host: 127.0.0.1
      #port: 1111
      #primary_slot_name: patroni
    postgresql:
      use_pg_rewind: true
      pg_hba:
      - local all postgres peer
      - local replication all peer
      - host replication replication 127.0.0.1/32 md5
      - host replication replication postgres1.dev.dc.me.com md5
      - host replication replication postgres2.dev.dc.me.com md5
      - host replication replication postgres3.dev.dc.me.com md5
      - host all all 0.0.0.0/0 md5
      parameters:
        archive_command: "pgbackrest --stanza=dev_pg17 archive-push %p"
        archive_mode: "on"
        restore_command: "pgbackrest --stanza=dev_pg17 archive-get %f \"%p\""
      recovery_conf:
        recovery_target_timeline: latest
        restore_command: pgbackrest --stanza=dev_pg17 archive-get %f "%p"
      method: pgbackrest
      pgbackrest:
        command: pgbackrest --stanza=dev_pg17 restore
        keep_existing_recovery_conf: false
        recovery_conf:
          recovery_target_timeline: latest
          restore_command: pgbackrest --stanza=dev_pg17 archive-get %f "%p"

  # some desired options for 'initdb'
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums

  # Additional script to be launched after initial cluster creation (will be passed the connection URL as parameter)
# post_init: /usr/local/bin/setup_cluster.sh

postgresql:
  listen: 127.0.0.1:5432
  connect_address: 127.0.0.1:5432

#  proxy_address: 127.0.0.1:5433  # The address of connection pool (e.g., pgbouncer) running next to Patroni/Postgres. Only for service discovery.
  data_dir: data/postgresql0
#  bin_dir:
#  config_dir:
  pgpass: /tmp/pgpass0

  authentication:
    replication:
      username: replication
      password: replication
    superuser:
      username: postgres
      password: postgres
    rewind:  # Has no effect on postgres 10 and lower
      username: rewind_user
      password: rewind_password

  create_replica_methods:
    - pgbackrest
  pgbackrest:
    command: pgbackrest --stanza=dev_pg17 restore --delta --link-all
    keep_data: true
    no_params: true

  pg_hba:
  - local all postgres peer
  - local replication all peer
  - host replication replication 127.0.0.1/32 md5
  - host replication replication postgres1.dev.dc.me.com md5
  - host replication replication postgres2.dev.dc.me.com md5
  - host replication replication postgres3.dev.dc.me.com md5
  - host all all 0.0.0.0/0 md5

  # Server side kerberos spn
#  krbsrvname: postgres
  parameters:
    archive_command: "pgbackrest --stanza=dev_pg17 archive-push %p"
    archive_mode: "on"
    restore_command: "pgbackrest --stanza=dev_pg17 archive-get %f \"%p\""

#watchdog:
#  mode: automatic # Allowed values: off, automatic, required
#  device: /dev/watchdog
#  safety_margin: 5

tags:
    nofailover: False
    noloadbalance: False
    clonefrom: False
    nosync: False
```

### patronictl show-config

```yaml
2024-11-28 14:10:36,074 - DEBUG - Ignoring configuration file "/var/lib/postgresql/.config/patroni/patronictl.yaml". It does not exists or is not readable.
2024-11-28 14:10:36,109 - DEBUG - New etcd client created for http://127.0.0.1:4001
2024-11-28 14:10:36,110 - DEBUG - Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2024-11-28 14:10:36,110 - DEBUG - Starting new HTTP connection (1): etcd3.dev.dc.me.com:2379
2024-11-28 14:10:36,112 - DEBUG - http://etcd3.dev.dc.me.com:2379 "GET /version HTTP/11" 200 45
2024-11-28 14:10:36,112 - DEBUG - Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2024-11-28 14:10:36,157 - DEBUG - http://etcd3.dev.dc.me.com:2379 "POST /v3/cluster/member/list HTTP/11" 200 543
2024-11-28 14:10:36,158 - DEBUG - Retrieved list of machines: ['http://etcd3.dev.dc.me.com:2379', 'http://etcd1.dev.dc.me.com:2379', 'http://etcd2.dev.dc.me.com:2379']
2024-11-28 14:10:36,158 - INFO - Selected new etcd server http://etcd2.dev.dc.me.com:2379
2024-11-28 14:10:36,158 - DEBUG - Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=0, status=None)
2024-11-28 14:10:36,159 - DEBUG - Starting new HTTP connection (1): etcd2.dev.dc.me.com:2379
2024-11-28 14:10:36,163 - DEBUG - http://etcd2.dev.dc.me.com:2379 "POST /v3/kv/range HTTP/11" 200 None
ignore_slots:
- name: barman
  type: physical
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters: null
  pg_hba:
  - local all postgres peer
  - local replication all peer
  - host replication replication 127.0.0.1/32 md5
  - host replication replication postgres1.dev.dc.me.com md5
  - host replication replication postgres2.dev.dc.me.com md5
  - host replication replication postgres3.dev.dc.me.com md5
  - host all all 0.0.0.0/0 md5
  use_pg_rewind: true
retry_timeout: 10
ttl: 30
```

### Patroni log files

```shell
patroni-1  | 2024-10-24 16:14:20.320 UTC [2471] LOG:  started streaming WAL from primary at 1A0/28000000 on timeline 68
patroni-1  | 2024-10-24 16:14:20.315 P00   INFO: unable to find 00000044000001A000000028 in the archive
patroni-1  | 2024-10-24 16:14:20.331 P00   INFO: unable to find 00000047.history in the archive
```

### PostgreSQL log files

```shell
patroni-1  | 2024-10-24 16:14:15.312 UTC [2442] LOG:  started streaming WAL from primary at 1A0/28000000 on timeline 68
patroni-1  | 2024-10-24 16:14:15.312 UTC [2442] FATAL:  could not receive data from WAL stream: ERROR:  requested WAL segment 00000045000001A000000028 has already been removed
patroni-1  | P00   WARN: environment contains invalid option 'ssh-run'
patroni-1  | P00   WARN: environment contains invalid option 'host-repo-dir-path'
patroni-1  | P00   WARN: environment contains invalid option 'ssh-host-port'
patroni-1  | P00   WARN: environment contains invalid option 'host-log-dir-path'
patroni-1  | 2024-10-24 16:14:15.317 P00   INFO: archive-get command begin 2.53.1: [00000047.history, pg_wal/RECOVERYHISTORY] --exec-id=2444-287a8477 --log-level-console=info --log-level-file=debug --log-path=/var/log/pgbackrest --pg1-local --pg1-path=/var/lib/postgresql/data --process-max=2 --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/repo --repo1-s3-bucket=pgbackrest-dev --repo1-s3-endpoint=pgbackrest-minio --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=<my_minio_region> --repo1-s3-uri-style=path --no-repo1-storage-verify-tls --repo1-type=s3 --stanza=dev
patroni-1  | 2024-10-24 16:14:15.321 P00   INFO: unable to find 00000047.history in the archive
patroni-1  | 2024-10-24 16:14:15.321 P00   INFO: archive-get command end: completed successfully (5ms)
patroni-1  | P00   WARN: environment contains invalid option 'ssh-run'
patroni-1  | P00   WARN: environment contains invalid option 'host-repo-dir-path'
patroni-1  | P00   WARN: environment contains invalid option 'ssh-host-port'
patroni-1  | P00   WARN: environment contains invalid option 'host-log-dir-path'
patroni-1  | 2024-10-24 16:14:20.290 P00   INFO: archive-get command begin 2.53.1: [00000046000001A000000028, pg_wal/RECOVERYXLOG] --exec-id=2466-ace0eef4 --log-level-console=info --log-level-file=debug --log-path=/var/log/pgbackrest --pg1-local --pg1-path=/var/lib/postgresql/data --process-max=2 --repo1-cipher-pass=<redacted> --repo1-cipher-type=aes-256-cbc --repo1-path=/repo --repo1-s3-bucket=pgbackrest-dev --repo1-s3-endpoint=pgbackrest-minio --repo1-s3-key=<redacted> --repo1-s3-key-secret=<redacted> --repo1-s3-region=<my_minio_region> --repo1-s3-uri-style=path --no-repo1-storage-verify-tls --repo1-type=s3 --stanza=dev
patroni-1  | 2024-10-24 16:14:20.295 P00   INFO: unable to find 00000046000001A000000028 in the archive
patroni-1  | 2024-10-24 16:14:20.295 P00   INFO: archive-get command end: completed successfully (6ms)
```

### Have you tried to use GitHub issue search?

- [X] Yes

### Anything else we need to know?

I'm reporting both problems into this single issue because I think they could be related together and caused by the same problem, error or misconfiguration.

## Docker container:

Patroni and PostgreSQL are running into a Docker container with a custom build image which have both installed on it together with pgBackRest.
The pgBackRest repository is on a MinIO bucket.

## pgbackRest configuration on Patroni nodes:

```
[global]

#repo1-path=/mnt/pgbackrest
repo1-type=s3
repo1-path=/repo
repo1-s3-endpoint=pgbackrest-minio.dev.me.com
repo1-s3-bucket=pgbackrest-dev-pg17
repo1-s3-uri-style=path
repo1-s3-verify-tls=n
repo1-s3-key=mykey
repo1-s3-key-secret=mysecret
repo1-s3-region=my_minio_region
repo1-cipher-pass=mypass
repo1-cipher-type=aes-256-cbc

repo1-retention-full=14
repo1-retention-full-type=time
repo1-host-user=postgres

archive-check=n
process-max=2
log-level-console=info
log-path=/var/log/pgbackrest
log-level-file=debug
start-fast=y
delta=y

[dev_pg17]
pg1-local=y
pg1-path=/var/lib/postgresql/patroni-pg17/data
```
