### ISSUE TITLE
Logical replication slot is dropped which leads to the one's inoperability

### ISSUE THREAD

**Issue by akalgush** [patroni/patroni#3237]
### What happened?

Logical replication subscription create a permanent slot nowadays (since version 14) for sybcronization purposes. I met a scenario where logical replication was not functioning due to a deletion of a permanent inactive slot. To reproduce this there must be another slot - active and unknown to patroni (not being mentioned in section 'slots'). Turn patroni to pause mode then resume it back. Patroni starts to try to delete the unknown slot on constant basis. If any permanent inactive slot (like the ones for initial logical syncronization) is created at this moment, patroni just delete it.

It's not clear from docs, release notes and code what is the intended behaviour for patroni to manage slots. From one side any unknown slot (but temporary one) is about to be dropped, from another side it is often not dropped until restart. It is not clear at which moment a slot is expected to be dropped which is confusing. It would be great to clarify this.

### How can we reproduce it (as minimally and precisely as possible)?

-- create subscription on receiver side
CREATE SUBSCRIPTION test_sub1
CONNECTION 'host=source_host port=source_port user=postgres dbname=postgres sslmode=verify-ca sslcert=/pg_ssl/client.crt sslkey=/pg_ssl/client.key sslrootcert=/pg_ssl/root.crt'
PUBLICATION test_pub
WITH (copy_data = true, create_slot=true, enabled=true, slot_name=test_sub1);

postgres=# select * from pg_replication_slots;
 slot_name |  plugin  | slot_type | datoid | database | temporary | active | active_pid | xmin | catalog_xmin | restart_lsn | confirmed_flush_lsn | wal_status | safe_wal_size 
-----------+----------+-----------+--------+----------+-----------+--------+------------+------+--------------+-------------+---------------------+------------+---------------
 test_sub1 | pgoutput | logical   |  14422 | postgres | f         | t      |    2249639 |      |   2301612206 | 19/B2002108 | 19/B20021B8         | reserved   |              
(1 row)

$ patronictl -c /etc/patroni/postgres.yml pause
Success: cluster management is paused

-- restart is not needed, doing this to double-check that patroni does not delete it in pause-mode
$ pg_ctl restart
waiting for server to shut down.... done
server stopped
waiting for server to start....2024-12-04 10:45:08 MSK [2249602]: [1-1] app=,user=,db=,client=,type=postmaster LOG:  Default auto-detected value for pg_stat_kcache.linux_hz is 1000000
2024-12-04 10:45:08 MSK [2249602]: [2-1] app=,user=,db=,client=,type=postmaster LOG:  pg_ouline: outlines disabled
2024-12-04 10:45:08 MSK [2249602]: [3-1] app=,user=,db=,client=,type=postmaster LOG:  redirecting log output to logging collector process
2024-12-04 10:45:08 MSK [2249602]: [4-1] app=,user=,db=,client=,type=postmaster HINT:  Future log output will appear in directory "postgresql_log_dir".
 done
server started

$ patronictl -c /etc/patroni/postgres.yml resume
Success: cluster management is resumed

-- then patroni tries to delete the unknown slot test_sub1 every 10 sec (loop_wait)
Dec  4 10:46:12 source_host patroni.bin[1309802]: 2024-12-04 10:46:12,797 ERROR: Failed to drop replication slot 'test_sub1'
Dec  4 10:46:12 source_host patroni.bin[1309802]: 2024-12-04 10:46:12,861 INFO: no action. I am (source_host) the leader with the lock
Dec  4 10:46:22 source_host patroni.bin[1309802]: 2024-12-04 10:46:22,689 INFO: Lock owner: source_host; I am source_host
Dec  4 10:46:22 source_host patroni.bin[1309802]: 2024-12-04 10:46:22,757 ERROR: Failed to drop replication slot 'test_sub1'

-- create slot with the name like logical syncronization slot
postgres=# SELECT * FROM pg_create_logical_replication_slot('pg_19732_sync_17854_7442686389907653644', 'pgoutput', 'false');
                slot_name                |     lsn     
-----------------------------------------+-------------
 pg_19732_sync_17854_7442686389907653644 | 19/B2002228
(1 row)

-- then the logical syncronization slot was immediatelly dropped
postgres=# select * from pg_replication_slots;
 slot_name |  plugin  | slot_type | datoid | database | temporary | active | active_pid | xmin | catalog_xmin | restart_lsn | confirmed_flush_lsn | wal_status | safe_wal_size 
-----------+----------+-----------+--------+----------+-----------+--------+------------+------+--------------+-------------+---------------------+------------+---------------
 test_sub1 | pgoutput | logical   |  14422 | postgres | f         | t      |    2249639 |      |   2301612206 | 19/B20021F0 | 19/B2002228         | reserved   |              
(1 row)

### What did you expect to happen?

- logical replication syncronization slots must not be dropped
- unknown permanent slots must be dropped still it is not clear at which moment

### Patroni/PostgreSQL/DCS version

-   Patroni version: 2.1.1, 3.3.0
-   PostgreSQL version: 15 and higher
-   DCS (and its version): etcd v3.3.11

### Patroni configuration file

```yaml
$ cat postgres.yml 
scope: clustername
name: source_host

restapi:
...

etcd:
...

bootstrap:
    dcs:
        ttl: 135
        retry_timeout: 60
        loop_wait: 10
        maximum_lag_on_failover: 1048576
        synchronous_mode: true
        synchronous_mode_strict: false
        postgresql:
            parameters:
                max_connections: '110'
                max_locks_per_transaction: '64'
                max_worker_processes: '32'
                max_prepared_transactions: '12'
                wal_level: logical
                wal_log_hints: on
                track_commit_timestamp: off
                wal_keep_size: 256MB
                max_wal_senders: '10'
                max_replication_slots: '10'
                logical_decoding_work_mem: 64MB
                auth_activity_period: '60'
                authentication_max_workers: '16'
            use_pg_rewind: true
            use_slots: true
    initdb:
      - encoding: UTF8
      - data-checksums
postgresql:
...
    parameters:

#defaults

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
```

### patronictl show-config

```yaml
$ patronictl -c /etc/patroni/postgres.yml show-config
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    auth_activity_period: '60'
    authentication_max_workers: '16'
    logical_decoding_work_mem: 64MB
    max_connections: '110'
    max_locks_per_transaction: '64'
    max_prepared_transactions: '12'
    max_replication_slots: '2'
    max_wal_senders: '10'
    max_worker_processes: '32'
    track_commit_timestamp: false
    wal_keep_size: 64MB
    wal_level: logical
    wal_log_hints: true
  use_pg_rewind: true
  use_slots: true
retry_timeout: 60
synchronous_mode: true
synchronous_mode_strict: false
ttl: 135
```

### Patroni log files

```shell
-- patroni log: it does not inform that slot pg_19732_sync_17854_7442686389907653644 was deleted
Dec  4 10:50:52 source_host patroni.bin[1309802]: 2024-12-04 10:50:52,755 ERROR: Failed to drop replication slot 'test_sub1'
Dec  4 10:50:52 source_host patroni.bin[1309802]: 2024-12-04 10:50:52,819 INFO: no action. I am (srv-0-213.db.dev.sbt) the leader with the lock
```

### PostgreSQL log files

```shell
-- postgresql log: create slot by user and delete slot by patroni
2024-12-04 10:48:31 MSK [2249777]: [9-1] app=psql,user=postgres,db=postgres,client=source_host,type=client backend LOG:  duration: 10.285 ms  statement: SELECT * FROM pg_create_logical_replication_slot('pg_19732_sync_17854_7442686389907653644', 'pgoutput', 'false');
2024-12-04 10:48:32 MSK [2249641]: [57-1] app=Patroni,user=patroni,db=postgres,client=127.0.0.1,type=client backend LOG:  duration: 0.523 ms  statement: SELECT CASE WHEN pg_catalog.pg_is_in_recovery() THEN 0 ELSE ('x' || pg_catalog.substr(pg_catalog.pg_walfile_name(pg_catalog.pg_current_wal_lsn()), 1, 8))::bit(32)::int END, CASE WHEN pg_catalog.pg_is_in_recovery() THEN 0 ELSE pg_catalog.pg_wal_lsn_diff(pg_catalog.pg_current_wal_lsn(), '0/0')::bigint END, pg_catalog.pg_wal_lsn_diff(pg_catalog.pg_last_wal_replay_lsn(), '0/0')::bigint, pg_catalog.pg_wal_lsn_diff(COALESCE(pg_catalog.pg_last_wal_receive_lsn(), '0/0'), '0/0')::bigint, pg_catalog.pg_is_in_recovery() AND pg_catalog.pg_is_wal_replay_paused(), 0, CASE WHEN latest_end_lsn IS NULL THEN NULL ELSE received_tli END, slot_name, conninfo, NULL FROM pg_catalog.pg_stat_get_wal_receiver()
2024-12-04 10:48:32 MSK [2249641]: [58-1] app=Patroni,user=patroni,db=postgres,client=127.0.0.1,type=client backend LOG:  duration: 0.538 ms  statement: SELECT slot_name, slot_type, plugin, database, datoid, catalog_xmin, pg_catalog.pg_wal_lsn_diff(confirmed_flush_lsn, '0/0')::bigint FROM pg_catalog.pg_replication_slots
2024-12-04 10:48:32 MSK [2249641]: [59-1] app=Patroni,user=patroni,db=postgres,client=127.0.0.1,type=client backend LOG:  duration: 1.551 ms  statement: SELECT pg_catalog.pg_drop_replication_slot('pg_19732_sync_17854_7442686389907653644') WHERE EXISTS (SELECT 1 FROM pg_catalog.pg_replication_slots WHERE slot_name = 'pg_19732_sync_17854_7442686389907653644' AND NOT active)
```

### Have you tried to use GitHub issue search?

- [X] Yes
