### ISSUE TITLE
Failed to get list of machines

### ISSUE THREAD

**Issue by Wyphorn** [patroni/patroni#3242]
### What happened?

Hi,

my patroni cannot reach etcd. Patroni V4.0.4, ETCD V3.4.30, postgres14

My etcd config:
```
ETCD_NAME="node1"
ETCD_LISTEN_PEER_URLS  =  "http://10.1.1.10:2380"
ETCD_LISTEN_CLIENT_URLS  =  "http://10.1.1.10:2379,http://127.0.0.1:2379"
ETCD_INITIAL_ADVERTISE_PEER_URLS  =  "http://10.1.1.10:2380"
ETCD_INITIAL_CLUSTER  =  "node1=http://10.1.1.10:2380,node2=http://10.1.1.11:2380,node3=http://10.1.1.12:2380"
ETCD_ADVERTISE_CLIENT_URLS  =  "http://10.1.1.10:2379"
ETCD_INITIAL_CLUSTER_TOKEN  =  "my_cluster"
ETCD_INITIAL_CLUSTER_STATE  =  "new"
ETCD_DATA_DIR               =  "/data/etcd"
```

Etcd is runnig properly I think:
```
~`# sudo ETCDCTL_API=3 etcdctl endpoint status --write-out=table --endpoints=10.213.250.94:2379,10.213.250.93:2379,10.213.250.95:2379
+--------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
|      ENDPOINT      |        ID        | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+--------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| 10.1.1.11:2379 | a63b2cabb4c106f0 |  3.4.30 |   16 kB |      true |      false |      3632 |         51 |                 51 |        |
| 10.1.1.10:2379 | 2ff6793e3286585b |  3.4.30 |   20 kB |     false |      false |      3632 |         51 |                 51 |        |
| 10.1.1.12:2379 | 7c04c30cb66f24c8 |  3.4.30 |   20 kB |     false |      false |      3632 |         51 |                 51 |        |
+--------------------+------------------+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
```

I installed patroni on node1 and try to start the service:
```
Jan 09 17:32:53 system1 systemd[1]: Started patroni.service - Patroni Orchestration.
Jan 09 17:32:54 system1 patroni[3502943]: 2025-01-09 17:32:54,232 ERROR: Failed to get list of machines from http://10.1.1.10:2379/v2: EtcdException('Bad response : 404 page not found\n')
Jan 09 17:32:54 system1 patroni[3502943]: 2025-01-09 17:32:54,233 INFO: waiting on etcd
```

I added "export ETCDCTL_API=2" before, so my etcdctl commands look fine:
```
~# etcdctl --version
etcdctl version: 3.4.30
API version: 2
```

How can I get it run?

### How can we reproduce it (as minimally and precisely as possible)?

Install Patroni V4.0.4 and V3.4.30 and try to get it work

### What did you expect to happen?

start

### Patroni/PostgreSQL/DCS version

-   Patroni version: 4.0.4
-   PostgreSQL version: 14
-   DCS (and its version): ?

### Patroni configuration file

```yaml
scope: postgres
namespace: /db/
name: node1
restapi:
  listen: 0.0.0.0:8008
  connect_address: 10.1.1.10:8008
etcd:
  host: 10.1.1.10:2379
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
    use_pg_rewind: true
  initdb:
    - encoding: UTF8
    - data-checksums
  pg_hba:
    - host replication replicator   127.0.0.1/32 md5
    - host replication replicator   10.1.1.10/0   md5
    - host replication replicator   10.1.1.11/0   md5
    - host replication replicator   10.1.1.12/0   md5
    - host all all   0.0.0.0/0   md5
  users:
    admin:
       password: admin
       options:
       - createrole
       - createdb
postgresql:
   listen: 10.1.1.10:5432
   connect_address: 10.1.1.10:5432
   data_dir:     /data/patroni
   pgpass:     /tmp/pgpass
   authentication:
    replication:
      username:   replicator
      password:   "yyy"
    superuser:
      username:   postgres
      password:   "xxx"
      parameters:
      unix_socket_directories:  '.'
tags:
   nofailover:   false
   noloadbalance:   false
   clonefrom:   false
   nosync:   false
```

### patronictl show-config

```yaml
Error: Can not find suitable configuration of distributed configuration store
Available implementations: etcd, etcd3, kubernetes
```

### Patroni log files

```shell
Jan 09 17:32:53 system1 systemd[1]: Started patroni.service - Patroni Orchestration.
Jan 09 17:32:54 system1 patroni[3502943]: 2025-01-09 17:32:54,232 ERROR: Failed to get list of machines from http://10.1.1.10:2379/v2: EtcdException('Bad response : 404 page not found\n')
Jan 09 17:32:54 system1 patroni[3502943]: 2025-01-09 17:32:54,233 INFO: waiting on etcd
```

### PostgreSQL log files

```shell
-
```

### Have you tried to use GitHub issue search?

- [X] Yes
