### ISSUE TITLE
tags set in patroni config.yml is not visible in patronictl list

### ISSUE THREAD

**Issue by dibyanduroy** [patroni/patroni#3249]
### What happened?

tags:
      nofailover: false
      noloadbalance: false
      clonefrom: false
      nosync: true

any tags we set in patroni.yml is not visible in patronictl list command

patronictl -c /etc/patroni/config.yml list
+ Cluster: pg_cluster (7303561954310597033) ----+-----------+-----+-----------+
| Member         | Host          | Role         | State     |  TL | Lag in MB |
+----------------+---------------+--------------+-----------+-----+-----------+
| node1      | 192.168.0.151 | Leader       | running   | 117 |           |
| node2      | 192.168.0.152 | Sync Standby | streaming | 117 |         0 |
| node3      | 192.168.0.154 | Replica | streaming | 117 |         0 |
+----------------+---------------+--------------+-----------+-----+-----------+

we want to make sure node2 should never become sync standby node. but its not working.
we try to set any of the above tags in any node its not visible.

### How can we reproduce it (as minimally and precisely as possible)?

we are on 
ubuntu 22.04
etcdctl version: 3.3.25
API version: 2
patroni version 4.0.4

Also we try to only install patroni via postgres but same result

### What did you expect to happen?

we want tags to be appear

### Patroni/PostgreSQL/DCS version

-   Patroni version: 4.0.4
-   PostgreSQL version: psotgresql 14.15
-   DCS (and its version): 3.3.25

### Patroni configuration file

```yaml
scope: "pg_cluster"
namespace: "/dbservice/"
name: tst2jdc13
restapi:
  listen: 192.168.0.151:8008
  connect_address: 192.168.0.151:8008
etcd:
  hosts: 192.168.0.151:2379,192.168.0.152:2379,192.168.0.154:2379
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    synchronous_mode: true
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
      pg_hba:
      - local   all             all                                     peer
      - host    all             all             127.0.0.1/32            md5
      - host    all             all             samenet                 md5
      - host    replication     all             samenet                 md5
      - host    all             all             0.0.0.0/0               md5
      - host    replication     all             0.0.0.0/0               md5
  initdb:
  - encoding: UTF8
  - data-checksums
  users:
    admin:
      password: admin
      options:
        - createrole
        - createdb
postgresql:
  listen: "192.168.0.151:5432"
  connect_address: "192.168.0.151:5432"
  use_unix_socket: true
  data_dir: "/opt/postgresql/14/main"
  bin_dir: "/usr/lib/postgresql/14/bin"
  config_dir: "/etc/postgresql/14/main"
  pgpass: "/opt/postgresql/.pgpass"
  authentication:
    replication:
      username: "postgres"
      password: "<password>"
    superuser:
      username: "postgres"
      password: "<password>"
  parameters:
    unix_socket_directories: '/var/run/postgresql/'
    logging_collector: 'on'
    log_directory: '/var/log/postgresql'
    log_filename: 'postgresql-14-patroni.log'
  tags:
      nofailover: false
      noloadbalance: false
      clonefrom: false
      nosync: true
```

### patronictl show-config

```yaml
patronictl -c /etc/patroni/config.yml show-config
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    hot_standby_feedback: true
    log_timezone: PST8PDT
    max_connections: 1000
    max_wal_size: 100GB
    synchronous_commit: remote_apply
    synchronous_standby_names: ANY 1 ("node2","node3")
    timezone: PST8PDT
    wal_keep_size: 50GB
  pg_hba:
  - local   all             all                                     peer
  - host    all             all             127.0.0.1/32            md5
  - host    all             all             samenet                 md5
  - host    all             all             0.0.0.0/0               md5
  - host    replication     all             0.0.0.0/0               md5
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: true
synchronous_mode_strict: false
synchronous_node_count: 1
ttl: 30
```

### Patroni log files

```shell
Please share what logs entries you are looking for
```

### PostgreSQL log files

```shell
Please share what logs entries you are looking for
```

### Have you tried to use GitHub issue search?

- [x] Yes

**Comment by dibyanduroy** [comment]
We setup the etcd with lastest 3.5.17, still it didnt work.

**Comment by dibyanduroy** [comment]
cat etcd.yml
name: node1
data-dir: /opt/etcd/data
wal-dir: /opt/etcd/wal
listen-peer-urls: http://0.0.0.0:2380
listen-client-urls: http://0.0.0.0:2379
initial-advertise-peer-urls: http://192.168.0.151:2380
advertise-client-urls: http://192.168.0.151:2379
initial-cluster: prd1phyjdcdb01=http://192.168.0.151:2380
initial-cluster-token: etcd-cluster
initial-cluster-state: new
enable-v2: true
experimental-enable-v2v3: ''

**Comment by CyberDem0n** [comment]
patroni.yaml isn't correctly formatted:
```yaml
postgresql:
  tags:
      nofailover: false
      noloadbalance: false
      clonefrom: false
      nosync: true
```

Why `tags` is under `postgresql` section?
Please use https://github.com/patroni/patroni/blob/master/postgres0.yml#L134 as a reference.
