### ISSUE TITLE
Incorrect behavior on the consul tag - "replica" - is causing problems with the DNS.

### ISSUE THREAD

**Issue by 404notfoundhard** [patroni/patroni#3254]
### What happened?

I have 4 hosts in the cluster, 2 of which are in sync mode.
```yml
consul:
  host: consul:8500
  scheme: http
  token: ''
  dc: dc1
  register_service: true
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    synchronous_mode: true
    synchronous_node_count: 2
```

in patronictl list looks nice, and that's what I want.
```
+ Cluster: pg (7463465147890094100) -+-----------+----+-----------+----------------------+
| Member   | Host     | Role         | State     | TL | Lag in MB | Tags                 |
+----------+----------+--------------+-----------+----+-----------+----------------------+
| patroni1 | patroni1 | Leader       | running   |  2 |           | failover_priority: 3 |
| patroni2 | patroni2 | Sync Standby | streaming |  2 |         0 | failover_priority: 2 |
| patroni3 | patroni3 | Sync Standby | streaming |  2 |         0 | failover_priority: 1 |
| patroni4 | patroni4 | Replica      | streaming |  2 |         0 | failover_priority: 1 |
+----------+----------+--------------+-----------+----+-----------+----------------------+
```

### What did you expect to happen?

In consul i expected 3 tags - "replica","sync standby","leader", but there is only 2 
This is a problem because, in the DNS, i want to use the sync-standby hosts for RO. 
If we use the async replica , there will not be data consistency.

 
![Image](https://github.com/user-attachments/assets/87fdf653-74d6-4069-9d24-39f3be2bba1b)

### Patroni/PostgreSQL/DCS version

-   Patroni version: 4.0.4
-   PostgreSQL version: any
-   DCS (and its version):  consul

### Patroni configuration file

```yaml
scope: pg
name: patroni1
namespace: /service
restapi:
  listen: 0.0.0.0:8008
  connect_address: patroni1:8008
  authentication:
    username: patroni
    password: pass
watchdog:
  mode: false
tags:
  clonefrom: false
  noloadbalance: false
  nosync: false
  failover_priority: 3
log:
  level: INFO
  traceback_level: ERROR
  format: '[pg] %(asctime)s %(levelname)s: %(message)s'
  dateformat: '%Y-%m-%d %H:%M:%S'
  max_queue_size: 1000
  dir: /var/lib/pgsql
  file_num: 4
  file_size: 25000000
consul:
  host: consul:8500
  scheme: http
  token: ''
  dc: dc1
  register_service: true
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    synchronous_mode: true
    synchronous_node_count: 2
    synchronous_mode_strict: false
    member_slots_ttl: 5min
    maximum_lag_on_syncnode: 26214400
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        archive_mode: 'off'
        synchronous_commit: remote_apply
      pg_hba:
      - host replication all 0.0.0.0/0 md5
      - host all all 0.0.0.0/0 md5
  initdb:
  - encoding: UTF8
  - data-checksums
postgresql:
  listen: 0.0.0.0:5432
  connect_address: patroni1:5432
  use_unix_socket: false
  bin_dir: /usr/bin
  data_dir: /var/lib/pgsql/data
  config_dir: /var/lib/pgsql/data
  basebackup:
    checkpoint: fast
  parameters:
    unix_socket_directories: /tmp
  authentication:
    superuser:
      username: patroni_admin_pgpro
      password: pass
    replication:
      username: patroni_replication_pgpro
      password: pass
    rewind:
      username: patroni_rewind_pgpro
      password: pass

changes only in name/hosts
```

### patronictl show-config

```yaml
loop_wait: 10
maximum_lag_on_syncnode: 26214400
member_slots_ttl: 5min
postgresql:
  parameters:
    some_pg_param: true
  pg_hba:
  - host replication all 0.0.0.0/0 md5
  - host all all 0.0.0.0/0 md5
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: true
synchronous_mode_strict: false
synchronous_node_count: 2
ttl: 30
```

### Have you tried to use GitHub issue search?

- [x] Yes
