### ISSUE TITLE
Patroni fails to start up with etcd 3.4 server attached to etcd 3.2 cluster ("404 page not found")

### ISSUE THREAD

**Issue by bjh21** [patroni/patroni#3279]
### What happened?

I'm upgrading a Patroni cluster from Ubuntu 20.04 LTS to Ubuntu 24.04 LTS by replacing each node in turn. For simplicity, each host is a node of the etcd cluster, and Patroni just talks to etcd on the local node. The upgrade replaces etcd 3.2.26 with etcd 3.4.30. When a replaced node is added to the etcd cluster, etcd seems to be happy, saying in syslog:

```
2025-02-14T17:37:54.030366+00:00 moa-dev-patroni1 etcd[11682]: Running http and grpc server on single port. This is not recommended for production.
2025-02-14T17:37:54.030393+00:00 moa-dev-patroni1 etcd[11682]: etcd Version: 3.4.30
2025-02-14T17:37:54.030419+00:00 moa-dev-patroni1 etcd[11682]: Git SHA: Not provided (use ./build instead of go build)
2025-02-14T17:37:54.030446+00:00 moa-dev-patroni1 etcd[11682]: Go Version: go1.22.2
2025-02-14T17:37:54.030470+00:00 moa-dev-patroni1 etcd[11682]: Go OS/Arch: linux/amd64
...
2025-02-14T17:37:54.205410+00:00 moa-dev-patroni1 etcd[11682]: set the initial cluster version to 3.2
2025-02-14T17:37:54.205557+00:00 moa-dev-patroni1 etcd[11682]: enabled capabilities for version 3.2
```
However, when Patroni starts, it's not happy:
```
2025-02-14T17:40:00.789438+00:00 moa-dev-patroni1 patroni@17-main[16561]: 2025-02-14 17:40:00,788 ERROR: Failed to get list of machines from http://127.0.0.1:2379/v3alpha: <Unknown error: '404 page not found', code: 2>
2025-02-14T17:40:00.789528+00:00 moa-dev-patroni1 patroni@17-main[16561]: 2025-02-14 17:40:00,788 INFO: waiting on etcd
```
This means that the new node does not usefully become part of the cluster.

### How can we reproduce it (as minimally and precisely as possible)?

Create an etcd 3.2 cluster where each member's client URL is `http://localhost:2379`. Add a node running etcd 3.4. Configure Patroni to use that node:
```yaml
etcd3:
  host: 127.0.0.1:2379
```
Start up Patroni.

### What did you expect to happen?

I expected that Patroni on the new node would successfully join the cluster and replicate the database.

### Patroni/PostgreSQL/DCS version

-   Patroni version: 4.0.4 (PGDG package 4.0.4-2.pgdg24.04+1)
-   PostgreSQL version: 17.3 (PGDG package 17.3-1.pgdg24.04+1)
-   DCS (and its version): etcd 3.4.30 (Ubuntu package 3.4.30-1ubuntu0.24.04.2)

### Patroni configuration file

```yaml
# WARNING: File managed by Ansible: https://wiki.cam.ac.uk/uis/Platforms_Ansible
scope: "17-main"
namespace: "/postgresql-common/"
name: "moa-dev-patroni1"

etcd3:
  host: 127.0.0.1:2379

restapi:
  listen: :::8008
  connect_address: 172.28.208.105:8008
  certfile: /etc/moa-tls/patroni.crt
  keyfile: /etc/moa-tls/patroni.key
  cafile: /etc/moa-tls/ca/ca.crt
  verify_client: optional

ctl:
  cacert: /etc/moa-tls/ca/ca.crt
  certfile: /etc/moa-tls/patroni.crt
  keyfile: /etc/moa-tls/patroni.key

bootstrap:
  # Custom bootstrap method
  method: pg_createcluster
  pg_createcluster:
    command: /usr/share/patroni/pg_createcluster_patroni
  post_init: /etc/patroni/post-init

  # this section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  # and all other cluster members will use it as a `global configuration`
  dcs: {"ttl": 30, "loop_wait": 10, "retry_timeout": 10, "master_stop_timeout": 30, "maximum_lag_on_failover": 1048576, "synchronous_mode": true, "postgresql": {"use_pg_rewind": false, "remove_data_directory_on_rewind_failure": true, "remove_data_directory_on_diverged_timelines": true, "use_slots": false, "parameters": {"ssl_cert_file": "/etc/moa-tls/postgresql.crt", "ssl_key_file": "/etc/moa-tls/postgresql.key", "ssl_min_protocol_version": "TLSv1", "password_encryption": "scram-sha-256", "wal_level": "logical", "log_connections": true, "log_disconnections": true, "log_destination": "syslog", "log_min_messages": "log", "logging_collector": false, "shared_buffers": "256MB", "unix_socket_directories": "/var/run/postgresql"}, "pg_hba": ["local      all,replication  all                  peer map=local", "hostssl    replication      moa_replicator  all  scram-sha-256", "hostssl    postgres         moa_rewind      all  scram-sha-256", "hostssl    all,replication  all             all  md5", "hostnossl  all,replication  +moa_nossl      all  md5"], "pg_ident": ["local root moa_superuser", "local postgres moa_superuser", "local postgres moa_replicator", "local postgres moa_rewind", "local root moa_collectd", "local dump moa_superuser"]}}

postgresql:
  # Custom clone method
  create_replica_method:
    - pg_clonecluster
  pg_clonecluster:
    command: /usr/share/patroni/pg_clonecluster_patroni

  # Listen on all local addresses.  Note that Patroni extracts the port
  # number by looking for the last ':', so the IPv6 address won't
  # confuse it.
  listen: "::,0.0.0.0:5432"
  connect_address: 172.28.208.105:5432
  use_unix_socket: true
  data_dir: /var/lib/postgresql/17/main
  bin_dir: /usr/lib/postgresql/17/bin
  config_dir: /etc/postgresql/17/main
  pgpass: /var/lib/postgresql/17-main.pgpass
  authentication:
    replication:
      username: moa_replicator
      password: "<removed>"
      sslmode: verify-ca
    rewind:
      username: moa_rewind
      password: "<removed>"
      sslmode: verify-ca
# A superuser role is required in order for Patroni to manage the local
# Postgres instance.  If the option `use_unix_socket' is set to `true', then
# specifying an empty password results in no md5 password for the superuser
# being set and sockets being used for authentication. The `password:' line is
# nevertheless required.  Note that pg_rewind will not work if no md5 password
# is set.
    superuser:
      username: moa_superuser
      password:
```

### patronictl show-config

```yaml
loop_wait: 10
master_stop_timeout: 30
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    log_connections: true
    log_destination: syslog
    log_disconnections: true
    log_min_messages: log
    logging_collector: false
    password_encryption: scram-sha-256
    shared_buffers: 256MB
    ssl_cert_file: /etc/moa-tls/postgresql.crt
    ssl_key_file: /etc/moa-tls/postgresql.key
    ssl_min_protocol_version: TLSv1
    unix_socket_directories: /var/run/postgresql
    wal_level: logical
  pg_hba:
  - local      all,replication  all                  peer map=local
  - hostssl    replication      moa_replicator  all  scram-sha-256
  - hostssl    postgres         moa_rewind      all  scram-sha-256
  - hostssl    all,replication  all             all  md5
  - hostnossl  all,replication  +moa_nossl      all  md5
  pg_ident:
  - local root moa_superuser
  - local postgres moa_superuser
  - local postgres moa_replicator
  - local postgres moa_rewind
  - local root moa_collectd
  - local dump moa_superuser
  remove_data_directory_on_diverged_timelines: true
  remove_data_directory_on_rewind_failure: true
  use_pg_rewind: false
  use_slots: false
retry_timeout: 10
synchronous_mode: true
ttl: 30
```

### Patroni log files

```shell
2025-02-14T17:39:40.610368+00:00 moa-dev-patroni1 patroni@17-main[16561]: 2025-02-14 17:39:40,609 ERROR: Failed to get list of machines from http://127.0.0.1:2379/v3alpha: <Unknown error: '404 page not found', code: 2>
2025-02-14T17:39:40.611726+00:00 moa-dev-patroni1 patroni@17-main[16561]: 2025-02-14 17:39:40,611 INFO: waiting on etcd
```

### PostgreSQL log files

```shell
<Not relevant; PostgreSQL never starts>
```

### Have you tried to use GitHub issue search?

- [x] Yes

### Anything else we need to know?

I think the problem is that the correct URL for the etcd gRPC gateway depends on the version of the etcd server, because it's a feature of the individual server and not of the cluster. But Patroni chooses which URL to use [based on the cluster version](https://github.com/patroni/patroni/blob/master/patroni/dcs/etcd3.py#L251-L276). I hacked my copy of Patroni to use the server version instead, and then it worked properly, with Patroni joining the cluster, replicating the database, and starting streaming.

Specifically, this is the change I made. I'm not certain it's correct, but it worked for me:
```diff
--- patroni/dcs/etcd3.py.orig   2024-11-22 13:29:59.000000000 +0000
+++ patroni/dcs/etcd3.py        2025-02-14 18:12:11.230898850 +0000
@@ -261,16 +261,16 @@
             if self._cluster_version < (3, 0) or server_version < (3, 0, 4):
                 raise UnsupportedEtcdVersion('Detected Etcd version {0} is lower than 3.0.4'.format(server_version_str))

-            if self._cluster_version < (3, 3):
+            if server_version < (3, 3):
                 if self.version_prefix != '/v3alpha':
-                    if self._cluster_version < (3, 1):
+                    if server_version < (3, 1):
                         logger.warning('Detected Etcd version %s is lower than 3.1.0, watches are not supported',
                                        cluster_version_str)
                     if self.username and self.password:
                         logger.warning('Detected Etcd version %s is lower than 3.3.0, authentication is not supported',
                                        cluster_version_str)
                     self.version_prefix = '/v3alpha'
-            elif self._cluster_version < (3, 4):
+            elif server_version < (3, 4):
                 self.version_prefix = '/v3beta'
             else:
                 self.version_prefix = '/v3'
```
I applied the same change on one of the Ubuntu 20.04 LTS nodes (running etcd 3.2.26) and it still works.
