### ISSUE TITLE
Configuring one patroni node as archive node

### ISSUE THREAD

**Issue by pensnarik** [patroni/patroni#3281]
### What happened?

I have a cluster of 3 patroni nodes (patroni version == 4.0.2). One node is a leader, the second one is a standby. I want to configure the third node so that it fetches WALs from WAL archive (via pgbackrest) but it looks like it's not possible because settings in patroni.yml are overwritten by dynamic configuration which is shared among the whole cluster.

The reason I want to do that is I want to have one node which is decoupled from the leader node so that it's not affecting the leader.

### How can we reproduce it (as minimally and precisely as possible)?

Set up a cluster of 3 nodes. For "archive node" define use_slots = False,  primary_slot_name == null, define restore_command: pgbackrest --stanza=... archive-get %f "%p". Reload patroni configuration for node #3.

### What did you expect to happen?

I expect node 3 is switching to archive recovery mode and not using a slot to stream WALs from the leader.

### Patroni/PostgreSQL/DCS version

-   Patroni version: 4.0.2
-   PostgreSQL version: 15.10
-   DCS (and its version): etcd 3.x

### Patroni configuration file

```yaml
---
name: node3
namespace: /service/
scope: stanza
restapi:
  listen: 0.0.0.0:8008
  connect_address: ***:8008
  authentication:
    username: patroni
    password: "*"
  request_queue_size: 128
bootstrap:
  post_init: "/opt/patroni/post_init.sh stanza"
  dcs:
    ttl: 60
    loop_wait: 10
    retry_timeout: 20
    maximum_lag_on_failover: 1048576
    master_start_timeout: 60
    synchronous_mode: True
    postgresql:
      use_pg_rewind: True
      use_slots: False
      primary_slot_name: null
      parameters:
        archive_mode: 'on'
        archive_command: 'pgbackrest --stanza=stanza archive-push %p'
        restore_command: 'pgbackrest --stanza=stanza archive-get archive-get %f "%p"'
        archive_timeout: '1800s'
        wal_level: logical
        hot_standby: 'on'
        max_wal_senders: 12
        max_replication_slots: 12
        wal_log_hints: 'on'
        max_connections: '2000'
        shared_buffers: '4GB'
        effective_cache_size: '1GB'
        work_mem: '6MB'
        maintenance_work_mem: '64MB'
        autovacuum_analyze_scale_factor: '0.01'
        autovacuum_vacuum_scale_factor: '0.02'
        autovacuum_max_workers: '4'
        autovacuum_vacuum_cost_delay: '5ms'
        autovacuum_vacuum_cost_limit: '1000'
        max_wal_size: '2GB'
        local_preload_libraries: ''
        pg_stat_statements.max: '3000'
        pg_stat_statements.track: 'all'
        log_min_duration_statement: '3000'
        ssl: 'off'
        geqo: 'off'
        track_io_timing: 'on'
        log_line_prefix: '%t [%p] => [%l-1] client=%h,db=%d,user=%u '
        jit: 'off'
        random_page_cost: '4.0'
        log_connections: 'off'
        log_disconnections: 'off'
        log_duration: 'off'
        log_lock_waits: 'on'
        log_statement: 'ddl'
        vacuum_cost_page_dirty: '1'
        checkpoint_timeout: '30min'
        idle_in_transaction_session_timeout: '0'
  initdb: ['encoding=UTF8', 'data-checksums', 'auth-local=trust', 'locale=C.UTF-8', 'auth-host=md5', 'auth-local=trust', 'username=postgres']
postgresql:
  basebackup:
    {'max-rate': '1024M', 'checkpoint': 'fast'}
  listen: 0.0.0.0:5432
  connect_address: ***:5432
  data_dir: "/var/lib/pgsql/data"
  config_dir: "/var/lib/pgsql/data"
  bin_dir: "/usr/lib/postgresql/15/bin"
  use_unix_socket: True
  use_slots: False
  primary_slot_name: null
  create_replica_methods:
    - pgbackrest
  pgbackrest:
    command: "pgbackrest --stanza=stanza restore --delta"
  recovery_conf:
    restore_command: 'pgbackrest --stanza=stanza archive-get archive-get %f "%p"'
  parameters:
    shared_preload_libraries: "pg_stat_statements, pglogical"
    unix_socket_directories: "/var/run/postgresql"
    data_directory: "/var/lib/pgsql/data"
    port: "5432"
    hba_file: "/var/lib/pgsql/data/pg_hba.conf"
    ident_file: "/var/lib/pgsql/data/pg_ident.conf"
    log_autovacuum_min_duration: "50"
    log_checkpoints: "on"
    log_directory: "/var/log/postgresql"
    log_filename: "postgresql.log"
    log_file_mode: "0644"
    log_rotation_age: "1h"
    log_rotation_size: "100MB"
    log_truncate_on_rotation: "on"
    logging_collector: "on"
    superuser_reserved_connections: "10"
    vacuum_cost_delay: "1"
    wal_compression: "on"
    wal_sender_timeout: "5min"
    hot_standby_feedback: "on"
    tcp_keepalives_idle: "0"
    tcp_keepalives_interval: "0"
    tcp_keepalives_count: "0"
    shared_buffers: "4GB"
    work_mem: "6MB"
    maintenance_work_mem: "64MB"
    max_parallel_maintenance_workers: "2"
    idle_in_transaction_session_timeout: "0"
    statement_timeout: "0"
    log_min_duration_statement: "3000"
    log_lock_waits: "on"
    max_prepared_transactions: "0"
    pg_stat_statements.max: "3000"
    plan_cache_mode: "auto"
  pg_hba: [...]
  authentication:
    replication:
      username: "*"
      password: "*"
    superuser:
      username: "postgres"
      password: "*"
  callbacks:
    on_restart: "/etc/patroni/scripts/on-patroni-restart.sh"

etcd3:
  protocol: http
  username: "patroni"
  password: ""
  hosts: "..."
watchdog:
  mode: "off"
  device: "/dev/watchdog"
  safety_margin: 5
log:
  level: "INFO"
  dir: "/var/log/patroni"
  file_num: "2"
tags:
  nofailover: False
  noloadbalance: False
  clonefrom: False
  nosync: True
```

### patronictl show-config

```yaml
loop_wait: 10
master_start_timeout: 60
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_mode: 'on'
    archive_timeout: 1800s
    autovacuum_analyze_scale_factor: '0.01'
    autovacuum_max_workers: '6'
    autovacuum_vacuum_cost_delay: 5ms
    autovacuum_vacuum_cost_limit: '1300'
    autovacuum_vacuum_scale_factor: '0.02'
    checkpoint_timeout: 30min
    effective_cache_size: 45200MB
    geqo: 'off'
    hot_standby: 'on'
    idle_in_transaction_session_timeout: '0'
    jit: 'off'
    local_preload_libraries: ''
    log_connections: 'off'
    log_disconnections: 'off'
    log_duration: 'off'
    log_line_prefix: '%t [%p] => [%l-1] client=%h,db=%d,user=%u '
    log_lock_waits: 'on'
    log_min_duration_statement: '3000'
    log_statement: ddl
    maintenance_work_mem: 64MB
    max_connections: '2000'
    max_replication_slots: 12
    max_wal_senders: 12
    max_wal_size: 2GB
    max_worker_processes: 16
    pg_stat_statements.max: '3000'
    pg_stat_statements.track: all
    random_page_cost: '1.0'
    restore_command: pgbackrest --stanza=stanza archive-get %f "%p"
    shared_buffers: 14GB
    ssl: 'off'
    track_io_timing: 'on'
    vacuum_cost_page_dirty: '1'
    wal_level: logical
    wal_log_hints: 'on'
    work_mem: 64MB
  use_pg_rewind: true
  use_slots: true
retry_timeout: 20
synchronous_mode: true
tags:
  nofailover: true
ttl: 60
```

### Patroni log files

```shell
Feb 18 13:36:05 node3 systemd[1]: patroni.service: Consumed 1.717s CPU time.
Feb 18 13:37:44 node3 systemd[1]: Started Runners to orchestrate a high-availability PostgreSQL.
Feb 18 13:37:45 node3 patroni[3148]: /var/run/postgresql:5432 - no response
Feb 18 13:37:45 node3 patroni[3147]: 2025-02-18 13:37:45 MSK [3147] => [1-1] client=,db=,user= LOG:  redirecting log output to logging collector process
Feb 18 13:37:45 node3 patroni[3147]: 2025-02-18 13:37:45 MSK [3147] => [2-1] client=,db=,user= HINT:  Future log output will appear in directory "/var/log/postgresql".
Feb 18 13:37:46 node3 patroni[3159]: /var/run/postgresql:5432 - rejecting connections
Feb 18 13:37:46 node3 patroni[3161]: /var/run/postgresql:5432 - rejecting connections
Feb 18 13:37:47 node3 patroni[3170]: /var/run/postgresql:5432 - rejecting connections
Feb 18 13:37:48 node3 patroni[3175]: /var/run/postgresql:5432 - rejecting connections
Feb 18 13:37:49 node3 patroni[3183]: /var/run/postgresql:5432 - accepting connections
```

### PostgreSQL log files

```shell
2025-02-18 13:27:07 MSK [2607] => [6-1] client=,db=,user= LOG:  database system is ready to accept read-only connections
2025-02-18 13:27:07 MSK [2669] => [1-1] client=,db=,user= LOG:  started streaming WAL from primary at FB6/7F000000 on timeline 6
```

### Have you tried to use GitHub issue search?

- [x] Yes
