### ISSUE TITLE
Patroni removed the restore_command in postgresql.auto.conf generated by pgbackrest

### ISSUE THREAD

**Issue by XiuhuaRuan** [patroni/patroni#3291]
### What happened?

We want to recover a patroni cluster with pgbackrest backup data. But after running pgbackrest restore command, patroni failed to start postgres. 
If after running pgbackrest restore command, start postgres manually, then there is no issue to start patroni. 

### How can we reproduce it (as minimally and precisely as possible)?

1. setup patroni cluster with archive_command
2. exectute pgbackrest backup successfully
3. stop patroni cluster, remove postgres data directory
4. exectute pgbackrest restore successfully
```
[postgres@host107 ~]$ pgbackrest --stanza=postgres --log-level-console=info restore
2025-02-24 16:25:06.711 P00   INFO: restore command begin 2.48: --exec-id=9688-d58f9f80 --log-level-console=info --pg1-path=/usr/local/pgsql/data --repo1-path=/var/lib/pgbackrest --stanza=postgres
2025-02-24 16:25:06.717 P00   INFO: repo1: restore backup set 20250224-135216F, recovery will start at 2025-02-24 13:52:16
2025-02-24 16:25:07.759 P00   INFO: write updated /usr/local/pgsql/data/postgresql.auto.conf
2025-02-24 16:25:07.762 P00   INFO: restore global/pg_control (performed last to ensure aborted restores cannot be started)
2025-02-24 16:25:07.762 P00   INFO: restore size = 26.6MB, file total = 984
2025-02-24 16:25:07.763 P00   INFO: restore command end: completed successfully (1052ms)
```
6. start patroni, but patroni failed to start postgres.

### What did you expect to happen?

 After running pgbackrest restore command, patroni should start postgres successfully.

### Patroni/PostgreSQL/DCS version

-   Patroni version: 4.0.5
-   PostgreSQL version: 14.0
-   DCS (and its version): etcd-v3.5.9

### Patroni configuration file

```yaml
[postgres@host107 patroni]$ cat patroni.yml
scope: postgres-cluster
namespace: /service/
name: postgres_03

restapi:
  listen: 192.168.31.107:8008
  connect_address: 192.168.31.107:8008

etcd3:
  hosts: 192.168.31.105:2379,192.168.31.106:2379,192.168.31.107:2379

#zookeeper:
#  hosts: ['192.168.31.101:2181', '192.168.31.102:2181', '192.168.31.103:2181']

log:
  level: INFO
  traceback_level: INFO
  dir: /home/postgres/patroni
  file_num: 10
  file_size: 104857600

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    master_start_timeout: 300
    synchronous_mode: false
    postgresql:
      use_pg_rewind: true
      parameters:
        listen_addresses: "*"
        port: 5432
        wal_level: replica
        hot_standby: "on"
        wal_keep_size: 100
        max_wal_senders: 10
        max_replication_slots: 10
        wal_log_hints: "on"
        archive_mode: "off"
        archive_timeout: 1800s
 #------------log---------------------#
        logging_collector: on
        log_destination: 'stderr'
        log_truncate_on_rotation: on
        log_checkpoints: on
        log_connections: on
        log_disconnections: on
        log_error_verbosity: default
        log_lock_waits: on
        log_temp_files: 0
        log_autovacuum_min_duration: 0
        log_min_duration_statement: 50
        log_timezone: 'PRC'
        log_filename: postgresql-%Y-%m-%d_%H.log
        log_line_prefix: '%t [%p]: db=%d,user=%u,app=%a,client=%h '
#-----------------------------------

postgresql:
  database: postgres
  listen: 0.0.0.0:5432
  connect_address: 192.168.31.107:5432
  bin_dir: /usr/local/pgsql/bin
  data_dir: /usr/local/pgsql/data
  pgpass: /home/postgres/tmp/.pgpass

  authentication:
    replication:
      username: postgres
      password: postgres
    superuser:
      username: postgres
      password: postgres
    rewind:
      username: postgres
      password: postgres

tags:
    noloadbalance: false
    clonefrom: false
    nosync: false

[postgres@host107 patroni]$
```

### patronictl show-config

```yaml
[postgres@host107 patroni]$ patronictl -c patroni.yml show-config
loop_wait: 10
master_start_timeout: 300
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    archive_command: /bin/pgbackrest --config=/etc/pgbackrest/pgbackrest.conf --stanza=postgres --pg1-path=/usr/local/pgsql/data archive-push %p
    archive_mode: 'on'
    archive_timeout: 1800s
    hot_standby: 'on'
    listen_addresses: '*'
    log_autovacuum_min_duration: 0
    log_checkpoints: true
    log_connections: true
    log_destination: stderr
    log_disconnections: true
    log_error_verbosity: default
    log_filename: postgresql-%Y-%m-%d_%H.log
    log_line_prefix: '%t [%p]: db=%d,user=%u,app=%a,client=%h '
    log_lock_waits: true
    log_min_duration_statement: 50
    log_temp_files: 0
    log_timezone: PRC
    log_truncate_on_rotation: true
    logging_collector: true
    max_replication_slots: 10
    max_wal_senders: 10
    port: 5432
    wal_keep_size: 100
    wal_level: replica
    wal_log_hints: 'on'
  use_pg_rewind: true
retry_timeout: 10
synchronous_mode: false
ttl: 30

[postgres@host107 patroni]$
```

### Patroni log files

```shell
2025-02-24 16:36:12,621 INFO: Selected new etcd server http://192.168.31.107:2379
2025-02-24 16:36:12,665 INFO: No PostgreSQL configuration items changed, nothing to reload.
2025-02-24 16:36:12,716 WARNING: Postgresql is not running.
2025-02-24 16:36:12,716 INFO: Lock owner: None; I am postgres_03
2025-02-24 16:36:12,718 INFO: pg_controldata:
  pg_control version number: 1300
  Catalog version number: 202107181
  Database system identifier: 7474899660945323604
  Database cluster state: in production
  pg_control last modified: Mon Feb 24 16:33:40 2025
  Latest checkpoint location: 0/3000060
  Latest checkpoint's REDO location: 0/3000028
  Latest checkpoint's REDO WAL file: 000000010000000000000003
  Latest checkpoint's TimeLineID: 1
  Latest checkpoint's PrevTimeLineID: 1
  Latest checkpoint's full_page_writes: on
  Latest checkpoint's NextXID: 0:736
  Latest checkpoint's NextOID: 13893
  Latest checkpoint's NextMultiXactId: 1
  Latest checkpoint's NextMultiOffset: 0
  Latest checkpoint's oldestXID: 727
  Latest checkpoint's oldestXID's DB: 1
  Latest checkpoint's oldestActiveXID: 736
  Latest checkpoint's oldestMultiXid: 1
  Latest checkpoint's oldestMulti's DB: 1
  Latest checkpoint's oldestCommitTsXid: 0
  Latest checkpoint's newestCommitTsXid: 0
  Time of latest checkpoint: Mon Feb 24 16:33:40 2025
  Fake LSN counter for unlogged rels: 0/3E8
  Minimum recovery ending location: 0/0
  Min recovery ending loc's timeline: 0
  Backup start location: 0/0
  Backup end location: 0/0
  End-of-backup record required: no
  wal_level setting: replica
  wal_log_hints setting: on
  max_connections setting: 100
  max_worker_processes setting: 8
  max_wal_senders setting: 10
  max_prepared_xacts setting: 0
  max_locks_per_xact setting: 64
  track_commit_timestamp setting: off
  Maximum data alignment: 8
  Database block size: 8192
  Blocks per segment of large relation: 131072
  WAL block size: 8192
  Bytes per WAL segment: 16777216
  Maximum length of identifiers: 64
  Maximum columns in an index: 32
  Maximum size of a TOAST chunk: 1996
  Size of a large-object chunk: 2048
  Date/time type storage: 64-bit integers
  Float8 argument passing: by value
  Data page checksum version: 0
  Mock authentication nonce: f5b67a9992c63dfa3ce1da3e38f5d11add748ec4a5ffb79c5fd46a2703f46100

2025-02-24 16:36:12,775 INFO: doing crash recovery in a single user mode
2025-02-24 16:36:12,784 ERROR: Error when reading postmaster.opts
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/patroni/postgresql/rewind.py", line 546, in read_postmaster_opts
    with open(os.path.join(self._postgresql.data_dir, 'postmaster.opts')) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/pgsql/data/postmaster.opts'
2025-02-24 16:36:13,015 ERROR: Crash recovery finished with code=1
2025-02-24 16:36:13,015 INFO:  stdout=
2025-02-24 16:36:13,015 INFO:  stderr=2025-02-24 16:36:12 CST [10080]: db=,user=,app=,client= LOG:  database system was interrupted; last known up at 2025-02-24 16:33:40 CST
2025-02-24 16:36:13 CST [10080]: db=,user=,app=,client= LOG:  invalid checkpoint record
2025-02-24 16:36:13 CST [10080]: db=,user=,app=,client= FATAL:  could not locate required checkpoint record
2025-02-24 16:36:13 CST [10080]: db=,user=,app=,client= HINT:  If you are restoring from a backup, touch "/usr/local/pgsql/data/recovery.signal" and add required recovery options.
        If you are not restoring from a backup, try removing the file "/usr/local/pgsql/data/backup_label".
        Be careful: removing "/usr/local/pgsql/data/backup_label" will result in a corrupt cluster if restoring from a backup.

2025-02-24 16:36:22,671 WARNING: Postgresql is not running.
```

### PostgreSQL log files

```shell
2025-02-24 16:36:23 CST [10096]: db=,user=,app=,client= LOG:  starting PostgreSQL 14.0 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit
2025-02-24 16:36:23 CST [10096]: db=,user=,app=,client= LOG:  listening on IPv4 address "0.0.0.0", port 5432
2025-02-24 16:36:23 CST [10096]: db=,user=,app=,client= LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2025-02-24 16:36:23 CST [10098]: db=,user=,app=,client= LOG:  database system was interrupted; last known up at 2025-02-24 16:33:40 CST
2025-02-24 16:36:23 CST [10100]: db=[unknown],user=[unknown],app=[unknown],client=127.0.0.1 LOG:  connection received: host=127.0.0.1 port=38094
2025-02-24 16:36:23 CST [10100]: db=postgres,user=postgres,app=[unknown],client=127.0.0.1 FATAL:  the database system is starting up
2025-02-24 16:36:23 CST [10102]: db=[unknown],user=[unknown],app=[unknown],client=127.0.0.1 LOG:  connection received: host=127.0.0.1 port=38098
2025-02-24 16:36:23 CST [10102]: db=postgres,user=postgres,app=[unknown],client=127.0.0.1 FATAL:  the database system is starting up
2025-02-24 16:36:23 CST [10098]: db=,user=,app=,client= WARNING:  specified neither primary_conninfo nor restore_command
```

### Have you tried to use GitHub issue search?

- [x] Yes

### Anything else we need to know?

After running  pgbackrest restore command, pgbackrest generated restore_command in postgresql.auto.conf.
```
[postgres@host107 data]$ cat postgresql.auto.conf
# Do not edit this file manually!
# It will be overwritten by the ALTER SYSTEM command.

# Recovery settings generated by pgBackRest restore on 2025-02-24 16:34:29
restore_command = 'pgbackrest --stanza=postgres archive-get %f "%p"'
[postgres@host107 data]$
```
But after starting patroni, the restore_command line was removed from postgresql.auto.conf.
Patroni written recovery.conf just with recovery_target_timeline = 'latest'. 
```
[postgres@host107 data]$ cat postgresql.conf
# Do not edit this file manually!
# It will be overwritten by Patroni!
include 'postgresql.base.conf'

archive_command = '/bin/pgbackrest --config=/etc/pgbackrest/pgbackrest.conf --stanza=postgres --pg1-path=/usr/local/pgsql/data archive-push %p'
archive_mode = 'on'
archive_timeout = '1800s'
cluster_name = 'postgres-cluster'
hot_standby = 'on'
listen_addresses = '0.0.0.0'
log_autovacuum_min_duration = '0'
log_checkpoints = 'True'
log_connections = 'True'
log_destination = 'stderr'
log_disconnections = 'True'
log_error_verbosity = 'default'
log_filename = 'postgresql-%Y-%m-%d_%H.log'
log_line_prefix = '%t [%p]: db=%d,user=%u,app=%a,client=%h '
log_lock_waits = 'True'
log_min_duration_statement = '50'
log_temp_files = '0'
log_timezone = 'PRC'
log_truncate_on_rotation = 'True'
logging_collector = 'True'
max_connections = '100'
max_locks_per_transaction = '64'
max_prepared_transactions = '0'
max_replication_slots = '10'
max_wal_senders = '10'
max_worker_processes = '8'
port = '5432'
track_commit_timestamp = 'off'
wal_keep_size = '100'
wal_level = 'replica'
wal_log_hints = 'on'
hba_file = '/usr/local/pgsql/data/pg_hba.conf'
ident_file = '/usr/local/pgsql/data/pg_ident.conf'

# recovery.conf
recovery_target = ''
recovery_target_lsn = ''
recovery_target_name = ''
recovery_target_time = ''
recovery_target_timeline = 'latest'
recovery_target_xid = ''
```

Will patroni remove the restore command line from postgresql.auto.conf? Suppose patroni will not touch postgresql.auto.conf, right?
