### ISSUE TITLE
Need for different restore_command settings during pg_rewind and recovery phases in failback scenarios

### ISSUE THREAD

**Issue by arunkumarvgk** [patroni/patroni#3298]
### What happened?

When performing a failback operation from a split-brain scenario, Patroni's standby cluster configuration only allows for a single restore_command setting. This command is used both during pg_rewind execution and during the subsequent recovery phase.

In a cross-datacenter or multi-cluster Kubernetes setup with separate DCS scopes, when a split-brain occurs and both clusters have accumulated data, the failback process requires access to WAL files from two different archive locations:

During pg_rewind phase: Need WALs from the target (old primary) archive
During recovery phase: Need WALs from the source (new primary) archive

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a split-brain by manually promoting standby (removing standby_cluster config)
2. Add data to both old primary and new primary
3. Attempt failback to old primary
4. pg_rewind fails if old primary WALs are archived and restore_command points to new primary
5. Or recovery fails if new primary WALs are needed and restore_command points to old primary

### What did you expect to happen?

Need a way to change the restore_command after pg_rewind finishes, or want to know if there is a way to do this.

### Patroni/PostgreSQL/DCS version

-   Patroni version: 4.0.4
-   PostgreSQL version: 13+
-   DCS (and its version): 

### Patroni configuration file

```yaml
bootstrap:
  dcs:
    standby_cluster:
      host: <standby-cluster-host>
      port: <standby-cluster-port>
      primary_slot_name: <slot-name>
      create-replica-methods:
        - <pgbackrest>
      restore-command:
```

### patronictl show-config

```yaml
NA
```

### Patroni log files

```shell
If target cluster wal are archived, and restore_command is pointing to source's archive.

fails during pg_rewind:
stderr=pg_rewind: servers diverged at WAL location 0/D75F0D8 on timeline 3
pg_rewind: error: could not restore file "00000003000000000000000D" from archive
pg_rewind: error: could not find previous WAL record at 0/D75F0D8
```

### PostgreSQL log files

```shell
If source cluster wal are archived, and restore_command is pointing to target's archive.

fails to get wal from source archive location
```

### Have you tried to use GitHub issue search?

- [x] Yes

**Comment by CyberDem0n** [comment]
`standby_cluster.restore_command` in the global configuration does exactly that.

**Comment by arunkumarvgk** [comment]
I Agree with you it works well to pull the WALs from remote primary(source/new primary), but during pg_rewind process if it requires some of the archived WALs of the target(old primary), it still uses the restore command to fetch which is failing

**Current Setup**

In the standby cluster configuration, I've specified the pgBackRest stanza name of the remote primary (source cluster/ new primary)
This allows WAL records not available in the remote primary to be pulled from the remote primary's archive

**Problem**
The same restore_command is being used during the pg_rewind process to pull missing WAL from the old primary (target)

patronictl -c pgsql/patroni.yaml show-config
```
postgresql:
  parameters:
    archive_command: pgbackrest --stanza=cluster_a archive-push %p
    archive_mode: 'on'
    . . .
  use_pg_rewind: true
  use_slots: true
slots:
  dr_slot:
    type: physical
standby_cluster:
  archive_cleanup_command: pg_archivecleanup -d ${PGDATA}/pg_wal %r
  create_replica_methods:
  - pgbackrest
  host: vm-520.dr.svc.cluster.local
  port: 5432
  primary_slot_name: dr_slot
  restore_command: pgbackrest --stanza=cluster_b archive-get %f %p
```


> running pg_rewind from remote_member:<id>
> 2025-02-27 17:34:54,910 INFO: running pg_rewind from dbname=postgres user=replication host=vm-520.dr.svc.cluster.local port=5432 sslmode=verify-ca sslcert=/etc/replication_ssl/tls.crt sslkey=/etc/replication_ssl/tls.key sslrootcert=/etc/replication_ssl/ca.crt target_session_attrs=read-write
> 2025-02-27 17:34:55,437 INFO: pg_rewind exit code=1
> 2025-02-27 17:34:55,437 INFO:  stdout=2025-02-27 17:34:55.120 P00   INFO: archive-get command begin 2.51: [000000010000000000000010, /pgsql/data/pg_wal/000000010000000000000010] --archive-async --config=/etc/pgbackrest/pgbackrest.conf --repo1-s3-endpoint=minio.minio.svc.cluster.local:9000  --repo1-type=s3 --spool-path=/pgsql/spool **--stanza=cluster_b**
> 2025-02-27 17:34:55.427 P00   INFO: unable to find 000000010000000000000010 in the archive asynchronously
> 2025-02-27 17:34:55.427 P00   INFO: archive-get command end: completed successfully (316ms)
> 
> 2025-02-27 17:34:55,437 INFO:  stderr=pg_rewind: servers diverged at WAL location 0/10289610 on timeline 1
> pg_rewind: error: could not restore file "000000010000000000000010" from archive
> pg_rewind: error: could not find previous WAL record at 0/10289610

WAL files of the old primary(target) are in stanza **cluster_a**, but since the same restore_command used in pg_rewind process it is trying to find missing WALs in the remote primary archive stanza **cluster_b**
