### ISSUE TITLE
Out-of-pgdata postgresql.conf gets created with 600 permissions

### ISSUE THREAD

**Issue by mbanck-ntap** [patroni/patroni#3302]
### What happened?

Even if the old `postgresql.conf`/new `postgresql.base.conf` has 660 permissions, Patroni creates the new `postgresql.conf` with 600 permissions. I guess what actually happens is that the umask Patroni sets is more restrictive than what is expected and as `set_file_permissions()` only touches files in `PGDATA`, it does not fix this up. This seems to be a behavior change since #2781.

This is especially problematic on Debian, as `pg_lsclusters` reads the `postgresql.conf` and for regular users only displays garbage for Patroni-created instances:

```
Ver Cluster         Port      Status Owner     Data directory              Log file
15  example_cluster <unknown> down   <unknown> <unknown>                   <unknown>
```

I guess `write_postgresql_conf()` should record the file permissions of `postgresql.base.conf` (maybe only if it is not in `PGDATA`?) and then set the file permissions of `postgresql.conf` accordingly. However, that latter part is pretty much abstracted away in the `pg_perm` class so not sure whether we could/should just paper over it from `patroni/postgresql/config.py`

### How can we reproduce it (as minimally and precisely as possible)?

On Debian:
1. Create a Patroni config file with `pg_createconfig_patroni <ver> <instance>` or set `config_dir: /etc/postgresql/<ver>/<instance>` manually
2. Run `systemctl start patroni@<ver>-<instance>`
3. Observe that `/etc/postgresql/<ver>/<instance>/postgresql.conf` has 600 permissions

### What did you expect to happen?

`postgresql.conf` is world-readable, like `postgresql.base.conf`.

### Patroni/PostgreSQL/DCS version

-   Patroni version: master
-   PostgreSQL version: n/a
-   DCS (and its version): n/a

### Patroni configuration file

```yaml
bootstrap:
  method: pg_createcluster
  pg_createcluster:
    command: /usr/share/patroni/pg_createcluster_patroni
postgresql:
  create_replica_method:
    - pg_clonecluster
  pg_clonecluster:
    command: /usr/share/patroni/pg_clonecluster_patroni
  data_dir: /var/lib/postgresql/15/example_cluster
  bin_dir: /usr/lib/postgresql/15/bin
  config_dir: /etc/postgresql/15/example_cluster
```

### patronictl show-config

```yaml
n/a
```

### Patroni log files

```shell
n/a
```

### PostgreSQL log files

```shell
n/a
```

### Have you tried to use GitHub issue search?

- [x] Yes
