### ISSUE TITLE
Set loop_wait=0 via `edit-config`, the log indicates that it has been adjusted, but the `show-config` result is still 0.

### ISSUE THREAD

**Issue by zhaowcheng** [patroni/patroni#3311]
### What happened?

Set loop_wait=0 via `edit-config`, the log indicates that it has been adjusted, but the `show-config` result is still 0.

### How can we reproduce it (as minimally and precisely as possible)?

1. Set loop_wait=0 via `edit-config`:
```
[highgo@node1 ~]$ patronictl edit-config -s "loop_wait=0"
--- 
+++ 
@@ -1,4 +1,4 @@
-loop_wait: 10
+loop_wait: 0
 maximum_lag_on_failover: 1048576
 postgresql:
   parameters:

Apply these changes? [y/N]: y
Configuration changed
```

2. The log indicates that the invalid loop_wait value has been adjusted
```
[highgo@node1 logs]$ cat patroni.log | grep loop_wait
2025-03-14 16:28:38,171 WARNING: loop_wait=0 can't be smaller than 1, adjusting...
```

3. But the `show-config` result is still 0.
```
[highgo@node1 ~]$ patronictl show-config | grep loop_wait
loop_wait: 0
```

### What did you expect to happen?

The result of `show-config` should be the adjusted value.

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.3.2
-   PostgreSQL version: 14.6
-   DCS (and its version): etcd 3.5.9

### Patroni configuration file

```yaml
scope: highgo
namespace: /service
name: node1

restapi:
  listen: 0.0.0.0:8008
  connect_address: 192.168.1.101:8008
#  cafile: /etc/ssl/certs/ssl-cacert-snakeoil.pem
#  certfile: /etc/ssl/certs/ssl-cert-snakeoil.pem
#  keyfile: /etc/ssl/private/ssl-cert-snakeoil.key
#  authentication:
#    username: username
#    password: password

#ctl:
#  insecure: false # Allow connections to Patroni REST API without verifying certificates
#  certfile: /etc/ssl/certs/ssl-cert-snakeoil.pem
#  keyfile: /etc/ssl/private/ssl-cert-snakeoil.key
#  cacert: /etc/ssl/certs/ssl-cacert-snakeoil.pem

#citus:
#  database: citus
#  group: 0  # coordinator

# etcd:
  #Provide host to do the initial discovery of the cluster topology:
  # host: 127.0.0.1:2379
  #Or use "hosts" to provide multiple endpoints
  #Could be a comma separated string:
  #hosts: host1:port1,host2:port2
  #or an actual yaml list:
  #hosts:
  #- host1:port1
  #- host2:port2
  #Once discovery is complete Patroni will use the list of advertised clientURLs
  #It is possible to change this behavior through by setting:
  #use_proxies: true

#raft:
#  data_dir: .
#  self_addr: 127.0.0.1:2222
#  partner_addrs:
#  - 127.0.0.1:2223
#  - 127.0.0.1:2224

# The bootstrap configuration. Works only when the cluster is not yet initialized.
# If the cluster is already initialized, all changes in the `bootstrap` section are ignored!
bootstrap:
  # This section will be written into Etcd:/<namespace>/<scope>/config after initializing new cluster
  # and all other cluster members will use it as a `global configuration`.
  # WARNING! If you want to change any of the parameters that were set up
  # via `bootstrap.dcs` section, please use `patronictl edit-config`!
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
#    primary_start_timeout: 300
#    synchronous_mode: false
    #standby_cluster:
      #host: 127.0.0.1
      #port: 1111
      #primary_slot_name: patroni
    postgresql:
      use_pg_rewind: true
      # pg_hba:
      # For kerberos gss based connectivity (discard @.*$)
      #- host replication replicator 127.0.0.1/32 gss include_realm=0
      #- host all all 0.0.0.0/0 gss include_realm=0
      # - host replication replicator 127.0.0.1/32 md5
      # - host all all 0.0.0.0/0 md5
      #  - hostssl all all 0.0.0.0/0 md5
#      use_slots: true
      parameters:
        wal_level: replica
#        hot_standby: "on"
#        max_connections: 100
#        max_worker_processes: 8
#        wal_keep_segments: 8
#        max_wal_senders: 10
#        max_replication_slots: 10
#        max_prepared_transactions: 0
#        max_locks_per_transaction: 64
#        wal_log_hints: "on"
#        track_commit_timestamp: "off"
#        archive_mode: "on"
#        archive_timeout: 1800s
#        archive_command: mkdir -p ../wal_archive && test ! -f ../wal_archive/%f && cp %p ../wal_archive/%f
#      recovery_conf:
#        restore_command: cp ../wal_archive/%f %p

  # some desired options for 'initdb'
        max_connections: '100'
        max_locks_per_transaction: '64'
        max_worker_processes: '8'
        max_prepared_transactions: '0'
        track_commit_timestamp: "off"
        max_wal_senders: '10'
        max_replication_slots: '10'
        wal_keep_size: '0'
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums

  # Additional script to be launched after initial cluster creation (will be passed the connection URL as parameter)
# post_init: /usr/local/bin/setup_cluster.sh

postgresql:
  listen: '*:5432'
  connect_address: 192.168.1.101:5432

#  proxy_address: 127.0.0.1:5433  # The address of connection pool (e.g., pgbouncer) running next to Patroni/Postgres. Only for service discovery.
  data_dir: /home/highgo/pgsql/data
#  bin_dir:
#  config_dir:
  pgpass: /home/highgo/patroni/.pgpass
  authentication:
    replication:
      username: replica
      password: replica
    superuser:
      username: highgo
      password: highgo
    rewind:  # Has no effect on postgres 10 and lower
      username: rewind
      password: rewind
  # Server side kerberos spn
#  krbsrvname: postgres
  # parameters:
    # Fully qualified kerberos ticket file for the running user
    # same as KRB5CCNAME used by the GSS
#   krb_server_keyfile: /var/spool/keytabs/postgres
    # unix_socket_directories: '..'  # parent directory of data_dir
  # Additional fencing script executed after acquiring the leader lock but before promoting the replica
  #pre_promote: /path/to/pre_promote.sh

#watchdog:
#  mode: automatic # Allowed values: off, automatic, required
#  device: /dev/watchdog
#  safety_margin: 5

  database: highgo
  bin_dir: /home/highgo/pgsql/bin
tags:
    # failover_priority: 1
  noloadbalance: false
  clonefrom: false
  nosync: false
  nostream: false
etcd3:
  username: highgo
  password: highgo
  hosts: 127.0.0.1:2379
  protocol: http
log:
  dir: /home/highgo/patroni/logs
```

### patronictl show-config

```yaml
loop_wait: 0
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    max_connections: '100'
    max_locks_per_transaction: '64'
    max_prepared_transactions: '0'
    max_replication_slots: '10'
    max_wal_senders: '10'
    max_worker_processes: '8'
    track_commit_timestamp: 'off'
    wal_keep_size: '0'
    wal_level: replica
  use_pg_rewind: true
retry_timeout: 10
ttl: 30
```

### Patroni log files

```shell
2025-03-14 16:28:38,171 WARNING: loop_wait=0 can't be smaller than 1, adjusting...
```

### PostgreSQL log files

```shell
N/A
```

### Have you tried to use GitHub issue search?

- [x] Yes
