### ISSUE TITLE
Reinit fails to clone from leader when sync standbys lack required WAL segments

### ISSUE THREAD

**Issue by mirai280535831** [patroni/patroni#3320]
### What happened?

After prolonged shutdown of sync standbys (test-2/test-3), they cannot re-establish replication due to missing WAL segments. The `patronictl reinit` operation fails because clones are attempted from outdated sync standbys instead of the leader.

[patroni reinit failed problem.md](https://github.com/user-attachments/files/19446033/patroni.reinit.failed.problem.md)

### How can we reproduce it (as minimally and precisely as possible)?

1. 2sync standby shutdown for a long time
2. leader produce many WAL files and remove old files which sync standby still needed
3. leader switch times some times
4. power on sync  stanby ,patronictl list show the two sync became replica
5. patronictl reinit coun't rebuild syanc standby successfully

### What did you expect to happen?

When replicas are significantly behind (different timeline), reinit should prioritize cloning from the leader rather than outdated peers.

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.0.2
-   PostgreSQL version: 14.14
-   DCS (and its version): Consul v1.15.10

### Patroni configuration file

```yaml
#!/usr/bin/env patroni
#==============================================================#
# File      :   patroni.yml
# Desc      :   patroni cluster definition for test (crit)
# Path      :   /pg/bin/patroni.yml
# Real Path :   /pg/conf/test-2.yml
# Link      :   /pg/bin/patroni.yml -> /pg/conf/test-2.yml
# Doc       :   https://patroni.readthedocs.io/en/latest/SETTINGS.html
# Copyright (C) 2018-2023 H3C
#==============================================================#

# CRIT database are optimized for security, integrity, RPO

---
#------------------------------------------------------------------------------
# identity
#------------------------------------------------------------------------------
namespace: /pg/          # namespace
scope: test                 # cluster name
name: test-2                 # instance name

#------------------------------------------------------------------------------
# log
#------------------------------------------------------------------------------
log:
  level: INFO                           #  NOTEST|DEBUG|INFO|WARNING|ERROR|CRITICAL
  dir: /pg/log/                         #  default log file: /pg/log/patroni.log
  file_size: 33554432                   #  32MB log triggers log rotation
  file_num: 20                          #  keep at most 30x32MB = 1GB log
  dateformat: '%Y-%m-%d %H:%M:%S %z'    #  IMPORTANT: discard milli timestamp
  format: '%(asctime)s %(levelname)s: %(message)s'

#------------------------------------------------------------------------------
# dcs
#------------------------------------------------------------------------------
consul:
  host: 127.0.0.1:8500
  consistency: default         # default|consistent|stale
  register_service: true
  service_check_interval: 15s
  service_tags:
    - test


#------------------------------------------------------------------------------
# api
#------------------------------------------------------------------------------
# how to expose patroni service
# listen on all ipv4, connect via public ip, use same credential as dbuser_monitor
restapi:
  listen: 0.0.0.0:8008
  connect_address: 10.121.123.152:8008


#------------------------------------------------------------------------------
# ctl
#------------------------------------------------------------------------------
ctl:
  optional:
    insecure: true
    # cacert: '/path/to/ca/cert'
    # certfile: '/path/to/cert/file'
    # keyfile: '/path/to/key/file'

#------------------------------------------------------------------------------
# tags
#------------------------------------------------------------------------------
tags:
  nofailover: false
  clonefrom: true
  noloadbalance: false
  nosync: false
watchdog:
  mode: False
  device: /dev/watchdog
bootstrap:
  method: initdb
  initdb:
    - data-checksums
    - encoding: UTF8
    - locale: C
    - lc-collate: C
    - lc-ctype: en_US.UTF8

  pg_hba:
    - local   all             ssadmin                                ident
    - local   all             all                                     md5
    - host    all             all            0.0.0.0/0                md5
    - host    all             all            ::/0                     md5
    - local   replication     ssadmin                                ident
    - local   replication     all                                     md5
    - host    replication     all            0.0.0.0/0                md5
    - host    replication     all            ::/0                     md5

  dcs:
    loop_wait: 10
    ttl: 30
    retry_timeout: 10
    master_start_timeout: 120   # more patient on critical database
    maximum_lag_on_failover: 0
    master_stop_timeout: 10   # more patient on critical database
    synchronous_mode: true  # use sync replication on critical database
    synchronous_mode_strict: false

    failsafe_mode: true
    postgresql:
      use_slots: true
      use_pg_rewind: true
      remove_data_directory_on_rewind_failure: true

      parameters:
        max_connections: 800                    # 100 -> 800
        superuser_reserved_connections: 10      # reserve 10 connection for su
        max_prepared_transactions: 0            # 0 disable 2PC
        track_commit_timestamp: on              # enabled xact timestamp
        wal_level: logical                      # logical
        wal_log_hints: on                       # wal log hints to support rewind
        wal_keep_size: 1GB                      # keep at least 100GB WAL
        password_encryption: md5                # use traditional md5 auth
        unix_socket_directories: /tmp

        vacuum_defer_cleanup_age: 50000         # 0->50000 last 50000 xact changes will not be vacuumed
        promote_trigger_file: promote.signal    # default promote trigger file path
        max_standby_archive_delay: 10min        # max delay before canceling queries when reading WAL from archiv
e;
        max_standby_streaming_delay: 3min       # max delay before canceling queries when reading streaming WAL; 
        wal_receiver_status_interval: 1s        # send replies at least this often
        hot_standby_feedback: on                # send info from standby to prevent query conflicts
        wal_receiver_timeout: 60s               # time that receiver waits for
        max_logical_replication_workers: 8      # 4 -> 8, 6 sync worker + 1~2 apply worker
        max_sync_workers_per_subscription: 6    # 2 -> 6, 6 sync worker


        #----------------------------------------------------------------------
        # REPORTING AND LOGGING
        #----------------------------------------------------------------------
        log_destination: csvlog                 # use standard csv log
        logging_collector: on                   # enable csvlog
        log_directory: log                      # default log dir: /pg/data/log
        # log_filename: 'seasql-%a.log'         # weekly auto-recycle
        log_filename: 'seasql-%m-%d.log'        # MM-DD year auto-recycle
        log_checkpoints: on                     # log checkpoint info
        log_lock_waits: on                      # log lock wait info
        log_replication_commands: on            # log replication info
        log_statement: ddl                      # log ddl change
        log_min_duration_statement: 100         # log slow query (>100ms)


postgresql:
  bin_dir: /usr/seasql/bin
  data_dir: /pg/data
  config_dir: /pg/data
  database: seasql
  pgpass: /var/lib/seasql/.pgpass
  listen: '*:1524'
  connect_address: 10.121.123.152:1524
  use_unix_socket: true # default: /tmp


  authentication:
    superuser:
      username: ssadmin
      password: 'md52be06bf5c77d0a59a9de6981d44bcc20'
    replication:
      username: replicator
    rewind:
      username: replicator
  callbacks:
    on_start: /pg/bin/pg-failover-callback
    on_stop: /pg/bin/pg-failover-callback
    on_reload: /pg/bin/pg-failover-callback
    on_restart: /pg/bin/pg-failover-callback
    on_role_change: /pg/bin/pg-failover-callback


  use_pg_rewind: true
  remove_data_directory_on_rewind_failure: true
  remove_data_directory_on_diverged_timelines: false

  create_replica_methods:
    - basebackup
  basebackup:
    - max-rate: '1000M'
    - checkpoint: fast
    - status-interva: 1s
    - verbose
    - progress

...
```

### patronictl show-config

```yaml
failsafe_mode: true
loop_wait: 10
master_start_timeout: 120
master_stop_timeout: 10
maximum_lag_on_failover: 0
postgresql:
  parameters:
    hot_standby_feedback: true
    log_checkpoints: true
    log_destination: csvlog
    log_directory: log
    log_filename: seasql-%m-%d.log
    log_lock_waits: true
    log_min_duration_statement: 100
    log_replication_commands: true
    log_statement: ddl
    logging_collector: true
    max_connections: 800
    max_logical_replication_workers: 8
    max_prepared_transactions: 0
    max_standby_archive_delay: 10min
    max_standby_streaming_delay: 3min
    max_sync_workers_per_subscription: 6
    password_encryption: md5
    promote_trigger_file: promote.signal
    superuser_reserved_connections: 10
    track_commit_timestamp: true
    unix_socket_directories: /tmp
    vacuum_defer_cleanup_age: 50000
    wal_keep_size: 1GB
    wal_level: logical
    wal_log_hints: true
    wal_receiver_status_interval: 1s
    wal_receiver_timeout: 60s
  remove_data_directory_on_rewind_failure: true
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: true
synchronous_mode_strict: false
synchronous_node_count: 2
ttl: 30
```

### Patroni log files

```shell
2025-03-21 11:19:08 +0800 INFO: Removing data directory: /pg/data
2025-03-21 11:19:08 +0800 INFO: replica has been created using basebackup
2025-03-21 11:19:08 +0800 INFO: bootstrapped from replica 'test-2'
2025-03-21 11:19:08 +0800 INFO: closed patroni connection to the postgresql cluster
2025-03-21 11:19:08 +0800 INFO: postmaster pid=64142
2025-03-21 11:19:08 +0800 INFO: Lock owner: test-1; I am test-3
2025-03-21 11:19:08 +0800 INFO: reinitialize in progress
2025-03-21 11:19:10 +0800 INFO: Lock owner: test-1; I am test-3
2025-03-21 11:19:10 +0800 INFO: establishing a new patroni connection to the postgres cluster
2025-03-21 11:19:10 +0800 INFO: Register service test, params {'service_id': 'test/test-3', 'address'
: '10.121.123.153', 'port': 1524, 'check': {'http': 'http://10.121.123.153:8008/replica', 'interval':
 '15s', 'DeregisterCriticalServiceAfter': '150.0s'}, 'tags': ['test', 'replica'], 'enable_tag_overrid
e': True}
```

### PostgreSQL log files

```shell
2025-03-21 10:45:46.701 CST,,,63040,,67dcd2da.f640,2,,2025-03-21 10:45:46 CST,,0,FATAL,08P01,"could not receive data from WAL stream: ERROR:  requested WAL seg
ment 000000010000000000000004 has already been removed",,,,,,,,,"","walreceiver",,0
2025-03-21 10:45:48.161 CST,"replicator","",63051,"::1:56850",67dcd2dc.f64b,1,"idle",2025-03-21 10:45:48 CST,3/0,0,LOG,00000,"received replication command: IDE
NTIFY_SYSTEM",,,,,,"IDENTIFY_SYSTEM",,,"","walsender",,0
2025-03-21 10:45:49.050 CST,"replicator","",63052,"::1:56864",67dcd2dd.f64c,1,"idle",2025-03-21 10:45:49 CST,3/0,0,LOG,00000,"received replication command: IDE
NTIFY_SYSTEM",,,,,,"IDENTIFY_SYSTEM",,,"","walsender",,0
2025-03-21 10:45:51.704 CST,,,63080,,67dcd2df.f668,1,,2025-03-21 10:45:51 CST,,0,LOG,00000,"started streaming WAL from primary at 0/4000000 on timeline 1",,,,,
,,,,"","walreceiver",,0
2025-03-21 10:45:51.704 CST,,,63080,,67dcd2df.f668,2,,2025-03-21 10:45:51 CST,,0,FATAL,08P01,"could not receive data from WAL stream: ERROR:  requested WAL seg
ment 000000010000000000000004 has already been removed",,,,,,,,,"","walreceiver",,0
```

### Have you tried to use GitHub issue search?

- [x] Yes

### Anything else we need to know?

**Current Clone Logic (Problem Area)**:
The [`get_clone_member`](https://github.com/patroni/patroni/blob/master/patroni/dcs/__init__.py) function prioritizes random `clonefrom` members over the leader:
```python
candidates = [m for m in self.members if m.clonefrom and m.is_running...]
return candidates[randint(...)] if candidates else self.leader
```
**Proposed Solution**:
Modify candidate selection to,for example:
```python
    def get_clone_member(self, exclude_name: str) -> Union[Member, Leader, None]:
        exclude = [exclude_name] + ([self.leader.name] if self.leader else [])
        candidates = [m for m in self.members if m.clonefrom and m.is_running  and m.data['timeline'] >= self.leader.timeline and m.name not in exclude]
        return candidates[randint(0, len(candidates) - 1)] if candidates else self.leader
```
This would ensure clone sources have sufficient WAL history for recovery.
