### ISSUE TITLE
Undocumented max_connections lower value

### ISSUE THREAD

**Issue by javicane** [patroni/patroni#3323]
### What happened?

max_connections is set to a minimum value of 25 in patroni repo but this is not documented. When you try to set this setting to a value lower than 25, the change is ignored with no error message. 
Please include this limit in the documentation. 

### How can we reproduce it (as minimally and precisely as possible)?

1. patronictl edit-config <cluster name>
2. set max_connections to a value lower than 25
3. patronictl restart leader, patronictl restart replicas
4. connect to leader, show max_connections and the old value will be still there

### What did you expect to happen?

Please include this lower limit in the documentation. 

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.2.2
-   PostgreSQL version: 16.2
-   DCS (and its version): 3.5.12

### Patroni configuration file

```yaml
# Ansible managed

scope: postgresql-dbe-settings
namespace: /db/
name: postgresql-dbe-settings-1.dldz.internal
restapi:
  listen: 10.184.40.19:8008
  connect_address: 10.184.40.19:8008
  authentication:
    username: restuser
    password: zK692-VOUqJa8iHS2SGird0FP2qU8ou1f4zg9EnLI9g
etcd3:
  hosts:
    - postgresql-dbe-settings-1.dldz.internal:2379
    - postgresql-dbe-settings-2.dldz.internal:2379
    - postgresql-dbe-settings-3.dldz.internal:2379
  protocol: https
  username: patroni
  password: oJYRUbgmp1lxjE8ZpP4DJIPlrxlsI93vz9NFsq-Lipw
  cacert: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal-ca.crt
  cert: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal.crt
  key: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal.key
bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    synchronous_mode: true
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_level: 'replica'
        hot_standby: "on"
        wal_keep_segments: 4GB
        max_wal_senders: 10
        max_replication_slots: 10
        wal_log_hints: "on"
        archive_mode: "on"
        archive_timeout: "1800s"
        log_filename: postgresql-%d.log
        default_text_search_config: 'pg_catalog.english'
        log_directory: 'log'
        logging_collector: 'on'
        log_line_prefix: '%m [%p]: user=%u, db=%d, app=%a, client=%h '
        log_rotation_age: 1d
        log_rotation_size: 0
        log_timezone: 'UTC'
        log_truncate_on_rotation: on
        max_connections: 25
        shared_buffers: 979MB
        log_min_duration_statement: 1000
        shared_preload_libraries: 'pg_partman_bgw,pgaudit,pg_stat_statements,pgauditlogtofile,pg_cron'
        log_connections: "on"
        log_disconnections: "on"
        pgaudit.log: "role,ddl"
        pg_partman_bgw.interval: 3600
        pg_partman_bgw.dbname: test_db,db1,db2
        unix_socket_directories: '/var/run/postgresql/'
        huge_pages: try
        #this was in patroni template
        archive_command: pgbackrest --stanza=main archive-push %p
        restore_command: pgbackrest --stanza=main archive-get %f %p
        ssl: true
        ssl_cert_file: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal.crt
        ssl_key_file: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal.key
        ssl_ca_file: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal-ca.crt
        log_lock_waits: "on"
        log_temp_files: 0
        log_autovacuum_min_duration: "1min"
        cron.use_background_workers: 'on'
        effective_cache_size: 2937MB
        work_mem: 16MB
        maintenance_work_mem: 195MB
        max_worker_processes: 8
        max_parallel_workers: 2
        max_parallel_workers_per_gather: 1
        max_parallel_maintenance_workers: 1
        random_page_cost: 1.1
        effective_io_concurrency: 200
        checkpoint_timeout: 15min
        wal_segsize: 256
        wal_buffers: 64MB
        min_wal_size: 2GB
        max_wal_size: 4GB
        wal_keep_size: 4GB


  initdb:
    - auth-host: scram-sha-256
    - auth-local: peer
    - locale: en_US.UTF-8
    - encoding: UTF8
    - data-checksums
    - wal-segsize: 256

  pg_hba:
    - local all all peer
    - host all all 127.0.0.1/32 scram-sha-256
    - host all all ::1/128 scram-sha-256
    - host    all postgres 0.0.0.0/0 reject
    - hostssl all postgres 0.0.0.0/0 reject
    - hostssl replication replicator localhost scram-sha-256
    - hostssl replication replicator 10.184.40.19/32 scram-sha-256
    - hostssl replication replicator 10.184.40.53/32 scram-sha-256
    - hostssl replication replicator 10.184.41.167/32 scram-sha-256
    - hostssl all all 0.0.0.0/0 scram-sha-256

#end of bootstrap
postgresql:
  listen: 0.0.0.0:5432
  connect_address: 10.184.40.19:5432
  data_dir: /var/lib/pgsql/16/data
  bin_dir: /usr/lib/postgresql/16/bin
  config_dir: /var/lib/pgsql/16/data
  pgpass: /var/lib/pgsql/16/.pgpass
  authentication:
    replication:
      username: replicator
      password: zljA-leLvgqRiqGKvGnC-94kGUGzSuyriWWSXA1g1A4
      sslkey: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal.key
      sslcert: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal.crt
      sslrootcert: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal-ca.crt
    superuser:
      username: postgres
      password: Ga_wg4dzxep9nrP8tXn301wh1and7oBV3i_pXby4ZTs
      sslkey: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal.key
      sslcert: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal.crt
      sslrootcert: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal-ca.crt
    rewind:  # Has no effect on postgres 10 and lower
      username: rewind_user
      password: oNe_BmvDoCrNg-xX98H-NL61-JgY6n_HXNTw2SoFMJA
      sslkey: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal.key
      sslcert: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal.crt
      sslrootcert: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal-ca.crt
  parameters:
    wal_level: 'replica'
    hot_standby: "on"
    wal_keep_segments: 4GB
    max_wal_senders: 10
    max_replication_slots: 10
    wal_log_hints: "on"
    archive_mode: "on"
    archive_timeout: "1800s"
    log_filename: postgresql-%d.log
    default_text_search_config: 'pg_catalog.english'
    log_directory: 'log'
    logging_collector: 'on'
    log_line_prefix: '%m [%p]: user=%u, db=%d, app=%a, client=%h '
    log_rotation_age: 1d
    log_rotation_size: 0
    log_timezone: 'UTC'
    log_truncate_on_rotation: on
    max_connections: 25
    shared_buffers: 979MB
    log_min_duration_statement: 1000
    shared_preload_libraries: 'pg_partman_bgw,pgaudit,pg_stat_statements,pgauditlogtofile,pg_cron'
    log_connections: "on"
    log_disconnections: "on"
    pgaudit.log: "role,ddl"
    pg_partman_bgw.interval: 3600
    pg_partman_bgw.dbname: test_db,db1,db2
    unix_socket_directories: '/var/run/postgresql/'
    huge_pages: try
    #this was in patroni template
    archive_command: pgbackrest --stanza=main archive-push %p
    restore_command: pgbackrest --stanza=main archive-get %f %p
    ssl: true
    ssl_cert_file: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal.crt
    ssl_key_file: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal.key
    ssl_ca_file: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal-ca.crt
    log_lock_waits: "on"
    log_temp_files: 0
    log_autovacuum_min_duration: "1min"
    cron.use_background_workers: 'on'
    effective_cache_size: 2937MB
    work_mem: 16MB
    maintenance_work_mem: 195MB
    max_worker_processes: 8
    max_parallel_workers: 2
    max_parallel_workers_per_gather: 1
    max_parallel_maintenance_workers: 1
    random_page_cost: 1.1
    effective_io_concurrency: 200
    checkpoint_timeout: 15min
    wal_segsize: 256
    wal_buffers: 64MB
    min_wal_size: 2GB
    max_wal_size: 4GB
    wal_keep_size: 4GB


  pg_hba:
    - local all all peer
    - host all all 127.0.0.1/32 scram-sha-256
    - host all all ::1/128 scram-sha-256
    - host    all postgres 0.0.0.0/0 reject
    - hostssl all postgres 0.0.0.0/0 reject
    - hostssl replication replicator localhost scram-sha-256
    - hostssl replication replicator 10.184.40.19/32 scram-sha-256
    - hostssl replication replicator 10.184.40.53/32 scram-sha-256
    - hostssl replication replicator 10.184.41.167/32 scram-sha-256
    - hostssl all all 0.0.0.0/0 scram-sha-256



 #watchdog:
 #  mode: automatic # Allowed values: off, automatic, required
 #  device: /dev/watchdog
 #  safety_margin: 5

tags:
  nofailover: False
  noloadbalance: False
  clonefrom: False
  nosync: False

log:
  dir: /var/log/pgsql/16
  level: INFO
  file_num: 10
```

### patronictl show-config

```yaml
bootstrap:
  dcs:
    loop_wait: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      parameters:
        archive_command: pgbackrest --stanza=main archive-push %p
        archive_mode: 'on'
        archive_timeout: 1800s
        checkpoint_timeout: 15min
        cron.use_background_workers: 'on'
        default_text_search_config: pg_catalog.english
        effective_cache_size: 2937MB
        effective_io_concurrency: 200
        hot_standby: 'on'
        huge_pages: try
        log_autovacuum_min_duration: 1min
        log_connections: 'on'
        log_directory: log
        log_disconnections: 'on'
        log_filename: postgresql-%d.log
        log_line_prefix: '%m [%p]: user=%u, db=%d, app=%a, client=%h '
        log_lock_waits: 'on'
        log_min_duration_statement: 1000
        log_rotation_age: 1d
        log_rotation_size: 0
        log_temp_files: 0
        log_timezone: UTC
        log_truncate_on_rotation: true
        logging_collector: 'on'
        maintenance_work_mem: 195MB
        max_connections: 25
        max_parallel_maintenance_workers: 1
        max_parallel_workers: 2
        max_parallel_workers_per_gather: 1
        max_replication_slots: 10
        max_wal_senders: 10
        max_wal_size: 4GB
        max_worker_processes: 8
        min_wal_size: 2GB
        pg_partman_bgw.dbname: test_db,db1,db2
        pg_partman_bgw.interval: 3600
        pgaudit.log: role,ddl
        random_page_cost: 1.1
        restore_command: pgbackrest --stanza=main archive-get %f %p
        shared_buffers: 979MB
        shared_preload_libraries: pg_partman_bgw,pgaudit,pg_stat_statements,pgauditlogtofile,pg_cron
        ssl: true
        ssl_ca_file: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal-ca.crt
        ssl_cert_file: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal.crt
        ssl_key_file: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal.key
        unix_socket_directories: /var/run/postgresql/
        wal_buffers: 64MB
        wal_keep_segments: 4GB
        wal_keep_size: 4GB
        wal_level: replica
        wal_log_hints: 'on'
        wal_segsize: 256
        work_mem: 16MB
      use_pg_rewind: true
      use_slots: true
    retry_timeout: 10
    synchronous_mode: true
    ttl: 30
  initdb:
  - auth-host: scram-sha-256
  - auth-local: peer
  - locale: en_US.UTF-8
  - encoding: UTF8
  - data-checksums
  - wal-segsize: 256
  pg_hba:
  - local all all peer
  - host all all 127.0.0.1/32 scram-sha-256
  - host all all ::1/128 scram-sha-256
  - host    all postgres 0.0.0.0/0 reject
  - hostssl all postgres 0.0.0.0/0 reject
  - hostssl replication replicator localhost scram-sha-256
  - hostssl replication replicator 10.184.40.19/32 scram-sha-256
  - hostssl replication replicator 10.184.40.53/32 scram-sha-256
  - hostssl replication replicator 10.184.41.167/32 scram-sha-256
  - hostssl all all 0.0.0.0/0 scram-sha-256
etcd3:
  cacert: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal-ca.crt
  cert: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal.crt
  hosts:
  - postgresql-dbe-settings-1.dldz.internal:2379
  - postgresql-dbe-settings-2.dldz.internal:2379
  - postgresql-dbe-settings-3.dldz.internal:2379
  key: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal.key
  password: oJYRUbgmp1lxjE8ZpP4DJIPlrxlsI93vz9NFsq-Lipw
  protocol: https
  username: patroni
log:
  dir: /var/log/pgsql/16
  file_num: 10
  level: INFO
loop_wait: 10
maximum_lag_on_failover: 1048576
name: postgresql-dbe-settings-1.dldz.internal
namespace: /db/
postgresql:
  authentication:
    replication:
      password: zljA-leLvgqRiqGKvGnC-94kGUGzSuyriWWSXA1g1A4
      sslcert: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal.crt
      sslkey: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal.key
      sslrootcert: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal-ca.crt
      username: replicator
    rewind:
      password: oNe_BmvDoCrNg-xX98H-NL61-JgY6n_HXNTw2SoFMJA
      sslcert: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal.crt
      sslkey: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal.key
      sslrootcert: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal-ca.crt
      username: rewind_user
    superuser:
      password: Ga_wg4dzxep9nrP8tXn301wh1and7oBV3i_pXby4ZTs
      sslcert: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal.crt
      sslkey: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal.key
      sslrootcert: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal-ca.crt
      username: postgres
  bin_dir: /usr/lib/postgresql/16/bin
  config_dir: /var/lib/pgsql/16/data
  connect_address: 10.184.40.19:5432
  data_dir: /var/lib/pgsql/16/data
  listen: 0.0.0.0:5432
  parameters:
    archive_command: pgbackrest --stanza=main archive-push %p
    archive_mode: 'on'
    archive_timeout: 1800s
    checkpoint_timeout: 15min
    cron.use_background_workers: 'on'
    default_text_search_config: pg_catalog.english
    effective_cache_size: 2937MB
    effective_io_concurrency: 200
    hot_standby: 'on'
    huge_pages: try
    log_autovacuum_min_duration: 1min
    log_connections: 'on'
    log_directory: log
    log_disconnections: 'on'
    log_filename: postgresql-%d.log
    log_line_prefix: '%m [%p]: user=%u, db=%d, app=%a, client=%h '
    log_lock_waits: 'on'
    log_min_duration_statement: 1000
    log_rotation_age: 1d
    log_rotation_size: 0
    log_temp_files: 0
    log_timezone: UTC
    log_truncate_on_rotation: true
    logging_collector: 'on'
    maintenance_work_mem: 195MB
    max_connections: 25
    max_parallel_maintenance_workers: 1
    max_parallel_workers: 2
    max_parallel_workers_per_gather: 1
    max_replication_slots: 10
    max_wal_senders: 10
    max_wal_size: 4GB
    max_worker_processes: 8
    min_wal_size: 2GB
    pg_partman_bgw.dbname: test_db,db1,db2
    pg_partman_bgw.interval: 3600
    pgaudit.log: role,ddl
    random_page_cost: 1.1
    restore_command: pgbackrest --stanza=main archive-get %f %p
    shared_buffers: 979MB
    shared_preload_libraries: pg_partman_bgw,pgaudit,pg_stat_statements,pgauditlogtofile,pg_cron
    ssl: true
    ssl_ca_file: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal-ca.crt
    ssl_cert_file: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal.crt
    ssl_key_file: /etc/ssl/certs/bigbot/postgresql-dbe-settings.dldz.internal.key
    unix_socket_directories: /var/run/postgresql/
    wal_buffers: 64MB
    wal_keep_segments: 4GB
    wal_keep_size: 4GB
    wal_level: replica
    wal_log_hints: 'on'
    wal_segsize: 256
    work_mem: 16MB
  pg_hba:
  - local all all peer
  - host all all 127.0.0.1/32 scram-sha-256
  - host all all ::1/128 scram-sha-256
  - host    all postgres 0.0.0.0/0 reject
  - hostssl all postgres 0.0.0.0/0 reject
  - hostssl replication replicator localhost scram-sha-256
  - hostssl replication replicator 10.184.40.19/32 scram-sha-256
  - hostssl replication replicator 10.184.40.53/32 scram-sha-256
  - hostssl replication replicator 10.184.41.167/32 scram-sha-256
  - hostssl all all 0.0.0.0/0 scram-sha-256
  pgpass: /var/lib/pgsql/16/.pgpass
  use_pg_rewind: true
  use_slots: true
restapi:
  authentication:
    password: zK692-VOUqJa8iHS2SGird0FP2qU8ou1f4zg9EnLI9g
    username: restuser
  connect_address: 10.184.40.19:8008
  listen: 10.184.40.19:8008
retry_timeout: 10
scope: postgresql-dbe-settings
synchronous_mode: true
tags:
  clonefrom: false
  nofailover: false
  noloadbalance: false
  nosync: false
ttl: 30
```

### Patroni log files

```shell
no error message
```

### PostgreSQL log files

```shell
no error message
```

### Have you tried to use GitHub issue search?

- [x] Yes
