### ISSUE TITLE
Patroni 4.0.5 fails connecting to etcd v3 (keeps checking v2 endpoint) on FreeBSD 14.2 / Python 3.11

### ISSUE THREAD

**Issue by satriani-vai** [patroni/patroni#3337]
### What happened?

Hello Patroni Developers and Community,

I am encountering a persistent issue trying to configure Patroni 4.0.5 to use etcd v3 as its DCS on a FreeBSD 14.2 system running within Jails. Despite configuring `version: 3` in `patroni.yml` and ensuring etcd v3 Python libraries (`grpcio`, `protobuf`, etc.) are installed, Patroni consistently fails during startup by attempting to check the etcd v2 API endpoint (`/v2/machines`), which results in a 404 error against my etcd 3.4 server.

**Environment:**

*   **Operating System:** FreeBSD 14.2-RELEASE (running inside a FreeBSD Jail)
*   **Patroni Version:** 4.0.5
*   **Python Version:** 3.11
*   **etcd Version:** 3.4.18 (running in a separate Jail on the same host)
*   **Installation Method:** `pip install`
*   **Relevant Python Packages (after attempting manual dependency installation):**
    ```
    google-api-core          2.24.2
    google-api-python-client 2.167.0
    google-auth              2.39.0
    google-auth-httplib2     0.2.0
    googleapis-common-protos 1.70.0
    grpcio                   1.71.0
    patroni                  4.0.5
    proto-plus               1.26.1
    protobuf                 6.30.2
    # Note: python-etcd 0.4.5 was also present during some tests (see below)
    # Other dependencies like PyYAML, psycopg, etc., are also installed.
    ```

**Patroni Configuration (`/usr/local/etc/patroni.yml` - relevant parts):**

```yaml
scope: mycluster
name: DB1 # (or DB2 on the other node)
namespace: /patroni

restapi:
  listen: 0.0.0.0:8008
  connect_address: 10.0.0.2:8008 # (or 10.0.0.3 for DB2)

etcd:
  host: 10.0.0.6:2379 # IP of the Jail running etcd
  protocol: http
  version: 3         # Explicitly configured for v3

# bootstrap section exists with postgresql parameters...

postgresql:
  listen: '0.0.0.0:5432, /var/run/postgresql/.s.PGSQL.5432'
  connect_address: 10.0.0.2:5432 # (or 10.0.0.3 for DB2)
  data_dir: /var/db/postgresql/data
  # pg_hba and authentication sections configured...
```

**Problem Description:**

When starting Patroni, it fails to connect to etcd and logs the following repeating error, indicating it's trying to use the v2 API:

```
ERROR: Failed to get list of machines from http://10.0.0.6:2379/v2: EtcdException('Bad response : 404 page not found\n')
INFO: waiting on etcd
```

My etcd 3.4 server is running correctly, is reachable via the network, and responds successfully to etcd v3 client commands (tested using `ETCDCTL_API=3 etcdctl --endpoints=http://10.0.0.6:2379 endpoint health` from the etcd host). The v2 API is not enabled on the etcd server.

**Troubleshooting Steps Taken & Observations:**

1.  **Initial State:** Installed `patroni` via `pip`. Configured `etcd:` block with `version: 3`. -> Result: `/v2` error (404).
2.  **Install with `[etcd3]` extra:** Ran `pip install --no-cache-dir 'patroni[etcd3]'`. -> Result: `pip` installed `python-etcd 0.4.5` as a dependency, but *not* `grpcio`. The `/v2` error (404) persisted. It seems the `[etcd3]` extra definition for 4.0.5 might be incorrect in my environment, pulling the v2 client library.
3.  **Manual v3 Dependencies:** Uninstalled `patroni` and `python-etcd`. Manually installed `grpcio`, `protobuf`, `google-api-python-client`. Then installed `patroni` *without* extras (`pip install patroni==4.0.5`). -> Result: Patroni failed to start with a different error:
    ```
    INFO: Failed to import patroni.dcs.etcd3
    ...
    patroni.exceptions.PatroniFatalException: Can not find suitable configuration of distributed configuration store
    Available implementations: kubernetes
    ```
    This suggests that `patroni.dcs.etcd3` in v4.0.5 has an implicit dependency on `python-etcd` just to be *imported*, even if `grpcio` is present.
4.  **Both v2 and v3 Libraries Present:** Re-installed `python-etcd==0.4.5` alongside `grpcio` and the other v3 libraries. -> Result: The `Failed to import patroni.dcs.etcd3` error disappeared, but Patroni immediately reverted to the original `/v2` error (404), apparently ignoring the `version: 3` setting or performing a mandatory v2 check first.

**Conclusion & Question:**

It appears that Patroni 4.0.5, in my environment (FreeBSD 14.2 / Python 3.11), has issues with etcd v3 connectivity:
*   The `[etcd3]` installation extra incorrectly pulls the `python-etcd` (v2) library.
*   The `patroni.dcs.etcd3` module seems to require `python-etcd` to be present merely for the module import to succeed, even if v3 communication via `grpcio` is intended.
*   Even with `version: 3` configured and `grpcio` present (and `python-etcd` also present to allow the import), Patroni still attempts a failing v2 API check (`/v2/machines`) which prevents startup.

Is this a known issue with Patroni 4.0.5, potentially specific to FreeBSD or Python 3.11? Is there a workaround other than enabling the v2 API emulation in etcd? Could the dependency definition or the etcd client selection logic in 4.0.5 be revisited?

Any help or guidance would be greatly appreciated.

Thank you!

### How can we reproduce it (as minimally and precisely as possible)?

1.  **Set up Environment:**
    *   OS: FreeBSD 14.2 (tested within a Jail, but might occur on base system too)
    *   Python: 3.11
    *   etcd: Version 3.4.x (e.g., using `pkg install coreos-etcd34`)

2.  **Start etcd v3 (without v2 API):**
    *   Ensure etcd is running and listening on a network address (e.g., `10.0.0.6:2379` or `127.0.0.1:2379`).
    *   **Crucially, ensure the v2 API emulation is *disabled* (default for etcd 3.4).** Do *not* use the `--enable-v2=true` flag.
    *   Verify etcd v3 is working: `ETCDCTL_API=3 etcdctl --endpoints=<your_etcd_ip>:2379 endpoint health`

3.  **Install Patroni and Dependencies:**
    *   Install Patroni 4.0.5: `pip install patroni==4.0.5`
    *   Install etcd v3 libraries: `pip install grpcio protobuf google-api-python-client`
    *   **Install the etcd v2 library (needed for `patroni.dcs.etcd3` import in 4.0.5, even if not used for communication):** `pip install python-etcd==0.4.5`
    *   *(Verify final state: `pip list` should show `patroni==4.0.5`, `grpcio`, `protobuf`, and `python-etcd==0.4.5`)*

4.  **Create Minimal Patroni Configuration (`repro_patroni.yml`):**
    ```yaml
    scope: repro_cluster
    name: test_node
    namespace: /repro

    restapi:
      listen: 127.0.0.1:8008 # Keep simple for repro
      connect_address: 127.0.0.1:8008

    etcd:
      host: <your_etcd_ip>:2379 # Point to your running etcd
      protocol: http
      version: 3         # Explicitly configure v3

    # Minimal necessary PostgreSQL section (Patroni expects it)
    postgresql:
      listen: 127.0.0.1:5432 # Dummy listener
      connect_address: 127.0.0.1:5432
      data_dir: /tmp/pgdata_repro # Dummy path
      # Minimal dummy auth section
      authentication:
        superuser:
          username: postgres
          password: test
        replication:
          username: replicator
          password: test
    ```

5.  **Run Patroni:**
    ```bash
    patroni /path/to/repro_patroni.yml
    ```

6.  **Observe Output:**
    *   **Expected behavior (according to config):** Patroni should connect to etcd using the v3 API (gRPC) without errors related to `/v2`.
    *   **Actual behavior (the bug):** Patroni outputs repeating errors indicating it's trying to access the v2 API, which fails with a 404:
        ```
        ERROR: Failed to get list of machines from http://<your_etcd_ip>:2379/v2: EtcdException('Bad response : 404 page not found\n')
        INFO: waiting on etcd
        ```

This procedure isolates the issue to Patroni 4.0.5's interaction with etcd v3 when configured explicitly, demonstrating the unexpected attempt to use the v2 API despite the configuration and presence of v3 libraries. The prerequisite of having `python-etcd` installed *just to load the module* is also highlighted by step 3.

### What did you expect to happen?

Based on the configuration provided in `patroni.yml`, specifically setting `version: 3` within the `etcd:` block, I expected the following:

1.  **Honor Configuration:** Patroni should strictly adhere to the `version: 3` configuration setting.
2.  **Use v3 API Exclusively:** Patroni should utilize the installed etcd v3 client libraries (like `grpcio` and `protobuf`) to communicate with the specified etcd server (`http://10.0.0.6:2379` in my setup) solely via the etcd v3 (gRPC) protocol.
3.  **No v2 API Calls:** Patroni should **not** attempt to make any calls to etcd v2 API endpoints, especially not the `/v2/machines` endpoint that caused the `404 Not Found` error.
4.  **Successful Connection & Startup:** Consequently, Patroni should successfully establish a connection with the etcd v3 cluster, read/write cluster state information, and proceed with its normal startup process (e.g., initializing the PostgreSQL cluster if bootstrapping, or joining as a leader/replica).
5.  **Correct Dependencies:** Ideally, when configured for `version: 3`, Patroni should only depend on the necessary v3 client libraries (`grpcio` etc.) and should *not* require the presence of the v2 client library (`python-etcd`) even for internal module imports (`patroni.dcs.etcd3`).

In summary, I expected a clean startup sequence where Patroni connects to etcd using the configured v3 API without falling back to or attempting any v2 API interactions.

### Patroni/PostgreSQL/DCS version

-   Patroni version: 4.0.5
-   PostgreSQL version: 17.4_1
-   DCS (and its version): 

### Patroni configuration file

```yaml
# This is the configuration from one of the nodes (e.g., DB1).
# The configuration on the second node (DB2) is identical except for the 'name'
# and the IP addresses in 'restapi.connect_address' and 'postgresql.connect_address'.

scope: mycluster
name: DB1 # Changed to DB2 on the other node
namespace: /patroni

restapi:
  listen: 0.0.0.0:8008
  connect_address: 10.0.0.2:8008 # Changed to 10.0.0.3 on the other node

# --- Critical Section ---
etcd:
  host: 10.0.0.6:2379 # IP of the etcd server (running v3.4)
  protocol: http
  version: 3         # <<<<<<<< Explicitly configured to use etcd v3
# --- End Critical Section ---

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    # max_tries: 3 # Present in user config, often default
  postgresql:
    use_pg_rewind: true
    parameters:
      wal_level: replica
      max_wal_senders: 10
      wal_keep_size: 256MB # Example value
      unix_socket_directories: '/var/run/postgresql' # Example value
      max_connections: 100 # Example value

postgresql:
  listen: '0.0.0.0:5432, /var/run/postgresql/.s.PGSQL.5432' # Listening on external IP + socket
  connect_address: 10.0.0.2:5432 # Changed to 10.0.0.3 on the other node
  data_dir: /var/db/postgresql/data # Ensure this matches your setup
  # Basic pg_hba settings (adjust for security in real setup)
  pg_hba: |
    local  all             all                                     trust # Or md5/scram
    host   all             all             127.0.0.1/32            trust # Or md5/scram
    host   all             all             ::1/128                 trust # Or md5/scram
    host   all             all             10.0.0.0/24             trust # Or md5/scram, allow Jails network
    host   replication     replicator      10.0.0.0/24             trust # Or md5/scram, allow replication
  # Authentication credentials (use secure methods in production)
  authentication:
    superuser:
      username: postgres
      password: 'mypassword' # Replace with placeholder or note env var usage
    replication:
      username: replicator
      password: 'mypassword' # Replace with placeholder or note env var usage

# Optional log section (might be useful for debugging if requested by devs)
# log:
#   level: INFO # Set to DEBUG for more details
#   dir: /var/log/patroni
#   file: patroni.log
```

### patronictl show-config

```yaml
The `patronictl show-config` command cannot be executed successfully because Patroni fails to start and connect to the etcd cluster due to the v2 API issue described above.

This command requires an active connection to the Distributed Configuration Store (etcd) to retrieve the configuration currently managed by the Patroni cluster. Since Patroni never reaches the state where it can register itself or store its configuration in etcd, there is no configuration available for `patronictl` to show.

The intended static configuration is provided in the **"Patroni configuration file"** section of this report, which includes the `etcd:` block specifying `version: 3`.
```

### Patroni log files

```shell
Here are the relevant log snippets observed during startup attempts (Log level: INFO).

**Scenario 1: When `python-etcd` is installed (alongside `grpcio`, `protobuf` etc.)**

Patroni fails to start and continuously repeats the following errors, indicating it's attempting to use the v2 API despite `version: 3` in the configuration:


# Timestamps and exact repetition count may vary
2025-04-21 04:25:51,837 ERROR: Failed to get list of machines from http://10.0.0.6:2379/v2: EtcdException('Bad response : 404 page not found\n')
2025-04-21 04:25:51,837 INFO: waiting on etcd
2025-04-21 04:25:56,985 ERROR: Failed to get list of machines from http://10.0.0.6:2379/v2: EtcdException('Bad response : 404 page not found\n')
2025-04-21 04:25:56,985 INFO: waiting on etcd
# This pattern repeats indefinitely...


**Scenario 2: When `python-etcd` is *NOT* installed (but `grpcio`, `protobuf` etc. are present)**

Patroni fails immediately during initialization because it cannot import its own etcd3 DCS module, suggesting an unexpected dependency on `python-etcd` for the module import itself:


# Timestamps may vary
2025-04-21 04:20:44,304 INFO: Failed to import patroni.dcs.consul
2025-04-21 04:20:44,305 INFO: Failed to import patroni.dcs.etcd
2025-04-21 04:20:44,305 INFO: Failed to import patroni.dcs.etcd3  # <<<<< Critical Failure
2025-04-21 04:20:44,305 INFO: Failed to import patroni.dcs.exhibitor
2025-04-21 04:20:44,306 INFO: Failed to import patroni.dcs.raft
2025-04-21 04:20:44,306 INFO: Failed to import patroni.dcs.zookeeper
Traceback (most recent call last):
  File "/usr/local/bin/patroni", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/patroni/__main__.py", line 362, in main
    return patroni_main(args.configfile)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/patroni/__main__.py", line 243, in patroni_main
    abstract_main(Patroni, configfile)
  File "/usr/local/lib/python3.11/site-packages/patroni/daemon.py", line 172, in abstract_main
    controller = cls(config)
                 ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/patroni/__main__.py", line 64, in __init__
    self.dcs = get_dcs(self.config)
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/patroni/dcs/__init__.py", line 140, in get_dcs
    raise PatroniFatalException("Can not find suitable configuration of distributed configuration store\n"
patroni.exceptions.PatroniFatalException: Can not find suitable configuration of distributed configuration store
Available implementations: kubernetes


These logs demonstrate the core problem: Patroni 4.0.5 either fails to import its etcd3 module without the v2 library present, or it falls back to using the v2 API endpoint even when configured for v3 if the v2 library *is* present.

*(Note: DEBUG level logs can be provided if required.)*
```

### PostgreSQL log files

```shell
No relevant PostgreSQL log entries are generated related to this issue.

Patroni fails during its initial startup phase while attempting to connect to the Distributed Configuration Store (etcd). Because it cannot successfully connect to etcd (either due to the `/v2` API error or the `Failed to import patroni.dcs.etcd3` error), Patroni never reaches the stage where it initiates actions like `initdb`, `pg_basebackup`, or starting the PostgreSQL server process (`postmaster`).

Therefore, the PostgreSQL logs remain empty or only contain entries from previous, unrelated runs (if any). The problem occurs entirely within Patroni's DCS interaction layer, before PostgreSQL management begins.
```

### Have you tried to use GitHub issue search?

- [x] Yes

### Anything else we need to know?

*   **Environment:** The setup is running within standard FreeBSD 14.2 Jails. While jails are generally transparent environments, it's worth noting this specific OS context.
*   **etcd v3 Confirmed Working:** We have verified using `etcdctl` (setting `ETCDCTL_API=3`) from the etcd host jail that the etcd v3 API on `http://10.0.0.6:2379` is functional, reachable, and responds correctly to health checks and other commands.
*   **Python/OS Combination:** The specific combination of Patroni 4.0.5, Python 3.11, and FreeBSD 14.2 might be relevant to reproducing the issue.
*   **Core Dilemma Summary:** The key problem seems to be a dependency/logic conflict within Patroni 4.0.5 in this environment:
    1.  Its `patroni.dcs.etcd3` module fails to import *without* the `python-etcd` (v2 client) package being installed.
    2.  Once `python-etcd` *is* installed (to satisfy the import requirement), Patroni ignores the `version: 3` configuration during startup and makes a failing call to the v2 API endpoint (`/v2/machines`).
*   **Alternative Test Planned:** We are planning to test the latest Patroni 3.x release next as a potential workaround, to see if it handles etcd v3 dependencies and API selection differently.
*   **Goal:** The primary objective is to use etcd v3 as the DCS *without* needing to enable the v2 compatibility API (`--enable-v2=true`) on the etcd server, which feels like a workaround rather than a proper solution.
*   **Availability:** We are happy to provide further logs (e.g., with `log.level: DEBUG` enabled), perform specific diagnostic steps, or provide more system details if it helps in resolving this issue.
