### ISSUE TITLE
Patroni 4.0.5 Corrupts pg_hba.conf (Character per Line) using YAML Multiline String on FreeBSD/Python 3.11

### ISSUE THREAD

**Issue by satriani-vai** [patroni/patroni#3343]
### What happened?

Hello Patroni Developers and Community,
I am experiencing a critical issue with Patroni 4.0.5 on FreeBSD 14.2 / Python 3.11 where it fails to bootstrap a new cluster because it writes a corrupted pg_hba.conf file. The resulting file has each character (including spaces and newlines from the YAML source) placed on its own line, making it unparsable by PostgreSQL.

When attempting to bootstrap a new cluster (empty data directory, empty etcd namespace), Patroni runs `initdb` successfully (as seen in Patroni logs), but then writes a malformed `pg_hba.conf` based on the `postgresql.pg_hba` multi-line YAML block. PostgreSQL subsequently fails to start, logging `FATAL: could not load /path/to/data/pg_hba.conf` (exact path confirmed). Patroni detects the PostgreSQL startup failure (usually via `localhost:5432 - no response`), cancels the bootstrap, renames the data directory to `.failed`, and exits or enters a failed state.

The file `/var/db/postgres/data17/pg_hba.conf` gets written with each character from the YAML block appearing on a new line, including the initial comment marker `#` and spaces. Example snippet of the corrupted file:
```
# <-- First character '#' on its own line
 <-- Space on its own line
D <-- Character 'D' on its own line
o <-- Character 'o' on its own line
  <-- Space on its own line
n <-- Character 'n' on its own line
... etc ...
```
PostgreSQL fails to load this file, causing the bootstrap to fail. Patroni logs show `initdb` success, then `Starting postgres`, then often `localhost:5432 - no response`, followed by `Failed to bootstrap cluster`. PostgreSQL logs show `FATAL: could not load ... pg_hba.conf`.

If the entire `postgresql.pg_hba` block is removed from `patroni.yml`, Patroni successfully bootstraps the cluster using the default `pg_hba.conf` created by `initdb`. This strongly suggests the issue lies specifically in how Patroni 4.0.5 writes the file based on the YAML multi-line string in this environment.

Is this a known bug in Patroni 4.0.5 related to writing multi-line YAML strings, possibly specific to FreeBSD or Python 3.11 / PyYAML interaction?

### How can we reproduce it (as minimally and precisely as possible)?

1.  Set up the environment as described above.
2.  Ensure PostgreSQL data directory (e.g., `/var/db/postgres/data17`) and the Patroni etcd namespace (e.g., `/patroni/mycluster`) are empty/deleted.
3.  Use the following `patroni.yml` (relevant parts):
    ```yaml
    scope: mycluster
    name: DB1
    # ... (restapi, etcd3 sections) ...
    bootstrap:
      initdb:
        - encoding: UTF8
        - locale: C
    postgresql:
      use_pg_rewind: true
      listen: '0.0.0.0:5432'
      connect_address: 10.0.0.2:5432
      data_dir: /var/db/postgres/data17 # Use correct FreeBSD default path
      bin_dir: /usr/local/bin
      pgpass: /var/db/postgres/data17/.pgpass
      # --- This block causes the issue ---
      pg_hba: |
        local   all             postgres                                peer
        host    all             postgres        127.0.0.1/32            md5
        host    all             postgres        ::1/128                 md5
        local   all             all                                     md5
        host    all             all             10.0.0.6/32             md5
        host    replication     replicator      10.0.0.3/32             md5
      # --- End problematic block ---
      authentication:
        # ... (superuser, replication credentials) ...
      parameters:
        # ... (wal_level, etc.) ...
        hot_standby: "on"
    log:
      level: DEBUG
    ```
4.  Start Patroni using the rc.d script (or manually as `postgres` user): `service patroni start` (or `su -m postgres -c "patroni patroni.yml"`)
5.  Observe Patroni logs, PostgreSQL logs (`/var/log/messages`), and the generated `pg_hba.conf` file in the data directory.

### What did you expect to happen?

Patroni should write the content of the `postgresql.pg_hba` YAML block into `/var/db/postgres/data17/pg_hba.conf` as a standard, correctly formatted text file, preserving line breaks and spaces as defined in the YAML. PostgreSQL should then be able to load this file and start successfully.

### Patroni/PostgreSQL/DCS version

*   OS: FreeBSD 14.2-RELEASE (inside a Jail)
*   Patroni Version: 4.0.5
*   Python Version: 3.11
*   PostgreSQL Version: 17.4 (from `pkg`)
*   etcd Version: 3.4.18
*   Installation: `pip install patroni==4.0.5 python-etcd==0.4.5 grpcio protobuf google-api-python-client psycopg`

### Patroni configuration file

```yaml
See above
```

### patronictl show-config

```yaml
See above
```

### Patroni log files

```shell
See above
```

### PostgreSQL log files

```shell
See above
```

### Have you tried to use GitHub issue search?

- [x] Yes
