### ISSUE TITLE
Demoting self when failsafe mode is enabled and got ReadTimeoutError from k8s api.

### ISSUE THREAD

**Issue by shmelevall** [patroni/patroni#3344]
### What happened?

failsafe_mode don't work when got ReadTimeoutError from k8s api.

### How can we reproduce it (as minimally and precisely as possible)?

 maybe k8s is overload

### What did you expect to happen?

failsafe_mode could work 

### Patroni/PostgreSQL/DCS version

-   Patroni version: 4.0.4
-   PostgreSQL version: 
-   DCS (and its version): k8s

### Patroni configuration file

```yaml
bootstrap:
  dcs:
    failsafe_mode: true
    loop_wait: 10
    maximum_lag_on_failover: 33554432
    postgresql:
      parameters:
        archive_mode: 'on'
        archive_timeout: 1800s
        auto_explain.log_analyze: 'true'
        auto_explain.log_buffers: 'true'
        auto_explain.log_min_duration: 1000ms
        auto_explain.log_nested_statements: 'true'
        auto_explain.log_timing: 'true'
        auto_explain.log_triggers: 'true'
        auto_explain.log_wal: 'true'
        autovacuum_analyze_scale_factor: '0.01'
        autovacuum_max_workers: '8'
        autovacuum_multixact_freeze_max_age: '200000000'
        autovacuum_vacuum_cost_limit: '10000'
        autovacuum_vacuum_insert_scale_factor: '0.01'
        autovacuum_vacuum_scale_factor: '0.01'
        checkpoint_completion_target: '0.9'
        checkpoint_timeout: 20min
        effective_cache_size: 96GB
        effective_io_concurrency: '200'
        fsync: 'on'
        hot_standby: 'on'
        jit: 'on'
        log_autovacuum_min_duration: 0
        log_checkpoints: 'on'
        log_connections: 'on'
        log_disconnections: 'on'
        log_line_prefix: '%t [%p]: [%l-1] %c %x %d %u %a %h '
        log_lock_waits: 'on'
        log_min_duration_statement: 1000ms
        log_statement: ddl
        log_temp_files: 0
        maintenance_work_mem: 2GB
        max_connections: 1000
        max_parallel_maintenance_workers: '8'
        max_parallel_workers: '16'
        max_parallel_workers_per_gather: '8'
        max_prepared_transactions: '200'
        max_replication_slots: 10
        max_wal_senders: 10
        max_wal_size: 50GB
        max_worker_processes: '16'
        min_wal_size: 2GB
        random_page_cost: '1.1'
        session_preload_libraries: auto_explain
        tcp_keepalives_idle: 900
        tcp_keepalives_interval: 100
        track_functions: all
        track_io_timing: 'true'
        vacuum_multixact_freeze_min_age: '2000000'
        vacuum_multixact_freeze_table_age: '100000000'
        wal_buffers: 64MB
        wal_compression: 'on'
        wal_level: hot_standby
        wal_log_hints: 'on'
        work_mem: 32MB
      use_pg_rewind: true
      use_slots: true
    retry_timeout: 10
    synchronous_mode: true
    synchronous_node_count: 2
    ttl: 30
  initdb:
  - auth-host: md5
  - auth-local: trust
  - data-checksums
  - encoding: UTF8
  - locale: en_US.UTF-8
  post_init: /scripts/post_init.sh "zalandos"
kubernetes:
  bypass_api_service: true
  labels:
    application: spilo
  leader_label_value: master
  pod_ip: 2a02:5501:26:807::2032
  port: tcp://[fd00::1]:443
  port_443_tcp: tcp://[fd00::1]:443
  port_443_tcp_addr: fd00::1
  port_443_tcp_port: '443'
  port_443_tcp_proto: tcp
  ports:
  - name: postgresql
    port: 5432
  - name: odyssey
    port: 6432
  role_label: spilo-role
  scope_label: cluster-name
  service_host: fd00::1
  service_port: '443'
  service_port_https: '443'
  standby_leader_label_value: master
  use_endpoints: true
log:
  format:
  - asctime: '@timestamp'
  - levelname: level
  - message
  - module
  static_fields:
    app: patroni
  type: json
namespace:
postgresql:
  authentication:
    replication:
      password: password
      username: standby
    superuser:
      password: password
      username: postgres
  basebackup_fast_xlog:
    command: /scripts/basebackup.sh
    retries: 2
  bin_dir: /usr/lib/postgresql/16/bin
  callbacks:
    on_role_change: /scripts/on_role_change.sh zalandos true
  connect_address: 2a02:5501:26:807::2032:5432
  create_replica_method:
  - basebackup_fast_xlog
  data_dir: /home/postgres/pgdata/pgroot/data
  listen: '*:5432'
  name: 
  parameters:
    archive_command: /bin/true
    bg_mon.history_buckets: 120
    bg_mon.listen_address: '::'
    extwlist.custom_path: /scripts
    extwlist.extensions: btree_gin,btree_gist,citext,extra_window_functions,first_last_agg,hll,hstore,hypopg,intarray,ltree,pgcrypto,pgq,pgq_node,pg_trgm,postgres_fdw,tablefunc,uuid-ossp,timescaledb,pg_partman
    log_destination: csvlog, jsonlog
    log_directory: ../pg_log
    log_file_mode: '0644'
    log_filename: postgresql-%u.log
    log_rotation_age: 1d
    log_truncate_on_rotation: 'on'
    logging_collector: 'on'
    pg_stat_kcache.track_planning: 'on'
    pg_stat_statements.track_planning: 'on'
    pg_stat_statements.track_utility: 'off'
    shared_buffers: 32GB
    shared_preload_libraries: pg_qualstats,pg_wait_sampling,bg_mon,pg_stat_statements,pgextwlist,pg_auth_mon,set_user,timescaledb,pg_cron,pg_stat_kcache
    ssl: 'on'
    ssl_cert_file: /run/certs/server.crt
    ssl_key_file: /run/certs/server.key
  pg_hba:
  - local   all             all                                   trust
  - host    all             pgwatch2                127.0.0.1/32       trust
  - hostssl all             +zalandos    127.0.0.1/32       pam
  - host    all             all                127.0.0.1/32       md5
  - hostssl all             +zalandos    ::1/128            pam
  - host    all             all                ::1/128            md5
  - local   replication     standby                    trust
  - hostssl replication     standby all                md5
  - hostssl template1       pooler    all   reject
  - hostnossl all           all                all                reject
  - hostssl all             +zalandos    all                pam
  - hostssl all             all                all                md5
  pgpass: /run/postgresql/pgpass
  use_unix_socket: true
  use_unix_socket_repl: true
restapi:
  connect_address: 2a02:5501:26:807::2032:8008
  listen: :8008
scope: 
```

### patronictl show-config

```yaml
failsafe_mode: true
loop_wait: 10
maximum_lag_on_failover: 33554432
pause: false
pg_hba:
- local   all             all                                   trust
- host    all             pgwatch2                127.0.0.1/32       trust
- hostssl all             +zalandos    127.0.0.1/32       pam
- host    all             all                127.0.0.1/32       md5
- hostssl all             +zalandos    ::1/128            pam
- host    all             all                ::1/128            md5
- local   replication     standby                    trust
- hostssl replication     standby all                md5
- hostssl template1       pooler    all   reject
- hostnossl all           all                all                reject
- hostssl all             +zalandos    all                pam
- hostssl all             all                all                md5
postgresql:
  parameters:
    archive_mode: 'on'
    archive_timeout: 1800s
    auto_explain.log_analyze: 'true'
    auto_explain.log_buffers: 'true'
    auto_explain.log_min_duration: 1000ms
    auto_explain.log_nested_statements: 'true'
    auto_explain.log_timing: 'true'
    auto_explain.log_triggers: 'true'
    auto_explain.log_wal: 'true'
    autovacuum_analyze_scale_factor: '0.01'
    autovacuum_max_workers: '8'
    autovacuum_multixact_freeze_max_age: '200000000'
    autovacuum_vacuum_cost_limit: '10000'
    autovacuum_vacuum_insert_scale_factor: '0.01'
    autovacuum_vacuum_scale_factor: '0.01'
    checkpoint_completion_target: '0.9'
    checkpoint_timeout: 20min
    effective_cache_size: 96GB
    effective_io_concurrency: '200'
    fsync: 'on'
    hot_standby: 'on'
    jit: 'on'
    log_autovacuum_min_duration: 0
    log_checkpoints: 'on'
    log_connections: 'on'
    log_disconnections: 'on'
    log_line_prefix: '%t [%p]: [%l-1] %c %x %d %u %a %h '
    log_lock_waits: 'on'
    log_min_duration_statement: 1000ms
    log_statement: ddl
    log_temp_files: 0
    maintenance_work_mem: 2GB
    max_connections: 1000
    max_parallel_maintenance_workers: '8'
    max_parallel_workers: '16'
    max_parallel_workers_per_gather: '8'
    max_prepared_transactions: '200'
    max_replication_slots: 10
    max_wal_senders: 10
    max_wal_size: 50GB
    max_worker_processes: '16'
    min_wal_size: 2GB
    random_page_cost: '1.1'
    session_preload_libraries: auto_explain
    tcp_keepalives_idle: 900
    tcp_keepalives_interval: 100
    track_functions: all
    track_io_timing: 'true'
    vacuum_multixact_freeze_min_age: '2000000'
    vacuum_multixact_freeze_table_age: '100000000'
    wal_buffers: 64MB
    wal_compression: 'on'
    wal_level: hot_standby
    wal_log_hints: 'on'
    work_mem: 32MB
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
synchronous_mode: true
synchronous_node_count: 2
ttl: 30

```

### Patroni log files

```shell
{  "@timestamp": "2025-04-15 12:38:11,931", "level": "ERROR", "message": "Request to server https://[fd00::1]:443 failed: MaxRetryError(\"HTTPSConnectionPool(host='fd00::1', port=443): Max retries exceeded with url: /api/v1/namespaces/stg-s3-services/pods?labelSelector=application%3Dspilo%2Ccluster-name%3Ddb-0 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcb25499d80>: Failed to establish a new connection: [Errno 111] Connection refused'))\")", "module": "kubernetes", "app": "patroni"}
{ "@timestamp": "2025-04-15 12:38:12,932", "level": "ERROR", "message": "ObjectCache.run K8sConnectionFailed('No more API server nodes in the cluster')", "module": "kubernetes", "app": "patroni"}
{ "@timestamp": "2025-04-15 12:38:12,935", "level": "WARNING", "message": "Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcb2435c880>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v1/namespaces/stg-s3-services/pods?labelSelector=application%3Dspilo%2Ccluster-name%3Ddb-0", "module": "connectionpool", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:15,440", "level": "ERROR", "message": "Request to server https://[fd00::1]:443 failed: MaxRetryError('HTTPSConnectionPool(host=\\'fd00::1\\', port=443): Max retries exceeded with url: /api/v1/namespaces/stg-s3-services/pods?labelSelector=application%3Dspilo%2Ccluster-name%3Ddb-0 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host=\\'fd00::1\\', port=443): Read timed out. (read timeout=2.5)\"))')", "module": "kubernetes", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:16,441", "level": "ERROR", "message": "ObjectCache.run K8sConnectionFailed('No more API server nodes in the cluster')", "module": "kubernetes", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:16,442", "level": "WARNING", "message": "Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcb25489060>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v1/namespaces/stg-s3-services/pods?labelSelector=application%3Dspilo%2Ccluster-name%3Ddb-0", "module": "connectionpool", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:16,443", "level": "ERROR", "message": "Request to server https://[fd00::1]:443 failed: MaxRetryError(\"HTTPSConnectionPool(host='fd00::1', port=443): Max retries exceeded with url: /api/v1/namespaces/stg-s3-services/pods?labelSelector=application%3Dspilo%2Ccluster-name%3Ddb-0 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcb2548aad0>: Failed to establish a new connection: [Errno 111] Connection refused'))\")", "module": "kubernetes", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:17,445", "level": "ERROR", "message": "ObjectCache.run K8sConnectionFailed('No more API server nodes in the cluster')", "module": "kubernetes", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:17,657", "level": "ERROR", "message": "get_cluster", "module": "log", "app": "patroni", "exc_info": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/patroni/dcs/kubernetes.py\", line 980, in __load_cluster\n    self._wait_caches(stop_time)\n  File \"/usr/local/lib/python3.10/dist-packages/patroni/dcs/kubernetes.py\", line 860, in _wait_caches\n    raise RetryFailedError('Exceeded retry deadline')\npatroni.utils.RetryFailedError: Exceeded retry deadline"}
{  "@timestamp": "2025-04-15 12:38:17,658", "level": "ERROR", "message": "Error communicating with DCS", "module": "ha", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:17,661", "level": "INFO", "message": "Got response from db-0-3 http://[*:*:*:806::b980]:8008/failsafe: Accepted", "module": "ha", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:17,664", "level": "INFO", "message": "Got response from db-0-2 http://[*:*:*:801::dd3b]:8008/failsafe: Accepted", "module": "ha", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:17,664", "level": "INFO", "message": "Got response from db-0-1 http://[*:*:*:803::1aa]:8008/failsafe: Accepted", "module": "ha", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:17,665", "level": "INFO", "message": "continue to run as a leader because failsafe mode is enabled and all members are accessible", "module": "__main__", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:17,666", "level": "WARNING", "message": "Loop time exceeded, rescheduling immediately.", "module": "__main__", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:19,949", "level": "WARNING", "message": "Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'ReadTimeoutError(\"HTTPSConnectionPool(host='fd00::1', port=443): Read timed out. (read timeout=2.5)\")': /api/v1/namespaces/stg-s3-services/pods?labelSelector=application%3Dspilo%2Ccluster-name%3Ddb-0", "module": "connectionpool", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:22,454", "level": "ERROR", "message": "Request to server https://[fd00::1]:443 failed: MaxRetryError('HTTPSConnectionPool(host=\\'fd00::1\\', port=443): Max retries exceeded with url: /api/v1/namespaces/stg-s3-services/pods?labelSelector=application%3Dspilo%2Ccluster-name%3Ddb-0 (Caused by ReadTimeoutError(\"HTTPSConnectionPool(host=\\'fd00::1\\', port=443): Read timed out. (read timeout=2.5)\"))')", "module": "kubernetes", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:23,455", "level": "ERROR", "message": "ObjectCache.run K8sConnectionFailed('No more API server nodes in the cluster')", "module": "kubernetes", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:25,960", "level": "WARNING", "message": "Retrying (Retry(total=0, connect=None, read=None, redirect=0, status=None)) after connection broken by 'ReadTimeoutError(\"HTTPSConnectionPool(host='fd00::1', port=443): Read timed out. (read timeout=2.5)\")': /api/v1/namespaces/stg-s3-services/pods?labelSelector=application%3Dspilo%2Ccluster-name%3Ddb-0", "module": "connectionpool", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:27,667", "level": "ERROR", "message": "get_cluster", "module": "log", "app": "patroni", "exc_info": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/patroni/dcs/kubernetes.py\", line 980, in __load_cluster\n    self._wait_caches(stop_time)\n  File \"/usr/local/lib/python3.10/dist-packages/patroni/dcs/kubernetes.py\", line 860, in _wait_caches\n    raise RetryFailedError('Exceeded retry deadline')\npatroni.utils.RetryFailedError: Exceeded retry deadline"}
{  "@timestamp": "2025-04-15 12:38:27,668", "level": "ERROR", "message": "Error communicating with DCS", "module": "ha", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:27,673", "level": "INFO", "message": "Got response from db-0-3 http://[*:*:*:806::b980]:8008/failsafe: Accepted", "module": "ha", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:27,676", "level": "INFO", "message": "Got response from db-0-1 http://[*:*:*:803::1aa]:8008/failsafe: Accepted", "module": "ha", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:27,676", "level": "INFO", "message": "Got response from db-0-2 http://[*:*:*:801::dd3b]:8008/failsafe: Accepted", "module": "ha", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:27,677", "level": "INFO", "message": "continue to run as a leader because failsafe mode is enabled and all members are accessible", "module": "__main__", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:27,678", "level": "WARNING", "message": "Loop time exceeded, rescheduling immediately.", "module": "__main__", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:32,933", "level": "ERROR", "message": "Request to server https://[fd00::1]:443 failed: ReadTimeoutError(\"HTTPSConnectionPool(host='fd00::1', port=443): Read timed out. (read timeout=2.5)\")", "module": "kubernetes", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:34,135", "level": "INFO", "message": "Could not take out TTL lock", "module": "kubernetes", "app": "patroni"}
{ "@timestamp": "2025-04-15 12:38:34,135", "level": "INFO", "message": "Demoting self (immediate-nolock)", "module": "ha", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:34,136", "level": "ERROR", "message": "ObjectCache.run ProtocolError(\"Connection broken: InvalidChunkLength(got length b'', 0 bytes read)\", InvalidChunkLength(got length b'', 0 bytes read))", "module": "kubernetes", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:34,136", "level": "ERROR", "message": "ObjectCache.run ProtocolError(\"Connection broken: InvalidChunkLength(got length b'', 0 bytes read)\", InvalidChunkLength(got length b'', 0 bytes read))", "module": "kubernetes", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:38,504", "level": "INFO", "message": "demoted self after trying and failing to obtain lock", "module": "__main__", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:38,505", "level": "INFO", "message": "closed patroni connections to postgres", "module": "connection", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:38,506", "level": "WARNING", "message": "Loop time exceeded, rescheduling immediately.", "module": "__main__", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:38,746", "level": "INFO", "message": "postmaster pid=39961", "module": "postmaster", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:38,506", "level": "INFO", "message": "Lock owner: db-0-0; I am db-0-0", "module": "ha", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:39,687", "level": "INFO", "message": "updated leader lock during starting after demotion", "module": "__main__", "app": "patroni"}
{ "@timestamp": "2025-04-15 12:38:48,505", "level": "INFO", "message": "Lock owner: db-0-0; I am db-0-0", "module": "ha", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:48,859", "level": "INFO", "message": "updated leader lock during starting after demotion", "module": "__main__", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:55,851", "level": "INFO", "message": "Lock owner: db-0-0; I am db-0-0", "module": "ha", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:55,851", "level": "INFO", "message": "establishing a new patroni heartbeat connection to postgres", "module": "connection", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:57,017", "level": "INFO", "message": "promoted self to leader because I had the session lock", "module": "__main__", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:58,333", "level": "INFO", "message": "establishing a new patroni restapi connection to postgres", "module": "connection", "app": "patroni"}
{  "@timestamp": "2025-04-15 12:38:59,477", "level": "INFO", "message": "no action. I am (db-0-0), the leader with the lock", "module": "__main__", "app": "patroni"}

```

### PostgreSQL log files

```shell
no need
```

### Have you tried to use GitHub issue search?

- [x] Yes
