### ISSUE TITLE
When using synchronous_mode on, failover_priority is sometime not respected

### ISSUE THREAD

**Issue by ywh-jmorillo** [patroni/patroni#3351]
### What happened?

In a 3 nodes cluster, when using  `synchronous_mode: on` and `synchronous_node_count: 1`, `failover_priority` is sometime not respected after a HA switchover

### How can we reproduce it (as minimally and precisely as possible)?

Given I have a 3 nodes cluster with `synchronous_mode: on` and `synchronous_node_count: 1`
- patroni-node01 (`failover_priority: 2`)
- patroni-node02 (`failover_priority: 3`)
- patroni-backup00 (`failover_priority: 1`)

Initial state:
- patroni-node02 is Leader
- patroni-backup00 is Replica
- patroni-node01 is Sync Standby

If patroni-node01 is shutdown, patroni-backup00 become `Sync Standby`
If patroni-node01 is up again, it become `Replica` and patroni-backup00 remains in `Sync Standby` mode

### What did you expect to happen?

I expect that when patroni-node01 is up again, due to higher priority than patroni-backup00, the leader (node02) update his config:
synchronous_standby_names = '"patroni-backup00"' ->  '"patroni-node01"
So node01 become `Sync Standby` again and backup00 become `Replica` due to lower priority

### Patroni/PostgreSQL/DCS version

-   Patroni version: 4.0.5
-   PostgreSQL version: postgres (PostgreSQL) 16.9 (Debian 16.9-1.pgdg120+1)
-   DCS (and its version): 3.3.13

### Patroni configuration file

```yaml
# Config from git clone, only failover_priority, synchronous_mode and synchronous_node_count where changed
restapi:
  listen: 0.0.0.0:8008

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      pg_hba:
      - local all all trust
      - host replication replicator all md5
      - host all all all md5
      parameters:
        max_connections: 100
    synchronous_mode: on
    synchronous_node_count: 1

  initdb:
  - locale: en_US.UTF-8
  - encoding: UTF8
  - data-checksums

postgresql:
  listen: 0.0.0.0:5432
  data_dir: /home/postgres/data
  pgpass: /tmp/pgpass0

tags:
    failover_priority: 1 # backup00 is 1, node01 is 2 and node03 is 3
    noloadbalance: false
    clonefrom: false
    nostream: false
```

### patronictl show-config

```yaml
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters:
    max_connections: 100
  pg_hba:
  - local all all trust
  - host replication replicator all md5
  - host all all all md5
  use_pg_rewind: true
retry_timeout: 10
synchronous_mode: true
synchronous_node_count: 1
ttl: 30
```

### Patroni log files

```shell
patroni-node02    | 2025-05-12 07:39:03,402 INFO: no action. I am (patroni-node02), the leader with the lock
patroni-node02    | 2025-05-12 07:39:13,407 INFO: no action. I am (patroni-node02), the leader with the lock
patroni-node02    | 2025-05-12 07:39:23,293 INFO: Lock owner: patroni-node02; I am patroni-node02
patroni-node02    | 2025-05-12 07:39:23,343 INFO: Updating synchronous privilege temporarily from ['patroni-node01'] to []
patroni-node02    | 2025-05-12 07:39:23,401 INFO: Assigning synchronous standby status to ['patroni-backup00']
patroni-node02    | server signaled
patroni-node02    | 2025-05-12 07:39:23.404 UTC [38] LOG:  received SIGHUP, reloading configuration files
patroni-node02    | 2025-05-12 07:39:23.405 UTC [38] LOG:  parameter "synchronous_standby_names" changed to ""patroni-backup00""
patroni-node02    | 2025-05-12 07:39:23.513 UTC [214] LOG:  standby "patroni-backup00" is now a synchronous standby with priority 1
patroni-node02    | 2025-05-12 07:39:23.513 UTC [214] STATEMENT:  START_REPLICATION SLOT "patroni_backup00" 0/5000000 TIMELINE 1
patroni-node02    | 2025-05-12 07:39:25,567 INFO: Synchronous standby status assigned to ['patroni-backup00']
patroni-node02    | 2025-05-12 07:39:25,614 INFO: no action. I am (patroni-node02), the leader with the lock
patroni-node02    | 2025-05-12 07:39:33,458 INFO: no action. I am (patroni-node02), the leader with the lock
patroni-node02    | 2025-05-12 07:39:43,448 INFO: no action. I am (patroni-node02), the leader with the lock
patroni-node02    | 2025-05-12 07:39:53,388 INFO: no action. I am (patroni-node02), the leader with the lock
```

### PostgreSQL log files

```shell
#
```

### Have you tried to use GitHub issue search?

- [x] Yes
