### ISSUE TITLE
The key /failsave doesn't remove from DCS after set failsafe_mode: false in Dynamic configuration

### ISSUE THREAD

**Issue by VladislavVdovkin** [patroni/patroni#3363]
### What happened?

When we set **failsafe_mode: false** in dynamic configuration the key **/failsafe** doesn't remove from DCS, and requests return incorrect results 

### How can we reproduce it (as minimally and precisely as possible)?

make request to **/failsafe** endpoint until activate **failsafe_mode** for the first time, or if we deleted the key from DCS manually :

```
root@patroni-srv1:~# curl -v -s http://192.168.22.96:8008/failsafe | jq
*   Trying 192.168.22.96:8008...
* Connected to 192.168.22.96 (192.168.22.96) port 8008 (#0)
> GET /failsafe HTTP/1.1
> Host: 192.168.22.96:8008
> User-Agent: curl/7.88.1
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 502 Bad Gateway
< Server: BaseHTTP/0.6 Python/3.11.2
< Date: Tue, 27 May 2025 04:48:05 GMT
< Connection: close
< Content-Type: text/html;charset=utf-8
< Content-Length: 346
< 
{ [346 bytes data]
* Closing connection 0
parse error: Invalid numeric literal at line 1, column 10

```
We see that request didn't return a result.

Then we change dynamic configuration and activate failsafe_mode **(failsafe_mode: true)** and repeat request :

```
root@patroni-srv1:~# curl -v -s http://192.168.22.96:8008/failsafe | jq
*   Trying 192.168.22.96:8008...
* Connected to 192.168.22.96 (192.168.22.96) port 8008 (#0)
> GET /failsafe HTTP/1.1
> Host: 192.168.22.96:8008
> User-Agent: curl/7.88.1
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Server: BaseHTTP/0.6 Python/3.11.2
< Date: Tue, 27 May 2025 05:00:42 GMT
< Content-Type: application/json
< 
{ [160 bytes data]
* Closing connection 0
{
  "patroni-srv1": "http://192.168.22.96:8008/patroni",
  "patroni-srv2": "http://192.168.21.57:8008/patroni",
  "patroni-srv3": "http://192.168.23.119:8008/patroni"
}

```
Now request return normal result and we see that **failsafe_mode** is work. But now if we disable **failsafe_mode** in dynamic configuration **(failsafe_mode: false)** and repeat request again, the result will not change. It means that the key was not deleted from the DSC:

```
root@patroni-srv1:~# patronictl -c /etc/patroni.yml show-config | grep failsafe
failsafe_mode: false

root@patroni-srv1:~# curl -v -s http://192.168.22.96:8008/failsafe | jq
*   Trying 192.168.22.96:8008...
* Connected to 192.168.22.96 (192.168.22.96) port 8008 (#0)
> GET /failsafe HTTP/1.1
> Host: 192.168.22.96:8008
> User-Agent: curl/7.88.1
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Server: BaseHTTP/0.6 Python/3.11.2
< Date: Tue, 27 May 2025 05:10:08 GMT
< Content-Type: application/json
< 
{ [160 bytes data]
* Closing connection 0
{
  "patroni-srv1": "http://192.168.22.96:8008/patroni",
  "patroni-srv2": "http://192.168.21.57:8008/patroni",
  "patroni-srv3": "http://192.168.23.119:8008/patroni"
}
```

### What did you expect to happen?

In my opinion after disabling **failsafe_mode** the key **/failsave** must be deleted from **DCS**, because when working with API we should get correct results

### Patroni/PostgreSQL/DCS version

-   Patroni version: 4.0.5 , 3.0.2
-   PostgreSQL version: 17
-   DCS (and its version): etcd `3.4.23`

### Patroni configuration file

```yaml
scope: pgpro
#namespace: /service/
name: patroni-srv1

restapi:
  listen: 192.168.22.96:8008
  connect_address: 192.168.22.96:8008

etcd3:
  hosts: 192.168.22.96:2379, 192.168.21.57:2379, 192.168.23.119:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    primary_start_timeout: 300
    synchronous_mode: on
    postgresql:
      use_pg_rewind: true
      pg_hba:
      - host replication all 127.0.0.1/32 trust
      - host replication all 192.168.0.0/16 trust
      - host all all 192.168.0.0/16 trust
      - host all all 127.0.0.1/32 trust
      parameters:
  initdb:  # Note: It needs to be a list (some options need values, others are switches)
  - encoding: UTF8
  - data-checksums
postgresql:
  listen: 192.168.22.96:5432
  connect_address: 192.168.22.96:5432
  data_dir: /var/lib/pgpro/ent-17/data
  bin_dir: /opt/pgpro/ent-17/bin
  pgpass: /tmp/pgpass
  authentication:
    replication:
      username: postgres
      password: postgres
    superuser:
      username: postgres
      password: postgres
    rewind:  # Has no effect on postgres 10 and lower
      username: postgres
      password: postgres
  parameters:
    unix_socket_directories: '..'  # parent directory of data_dir

tags:
    noloadbalance: false
    clonefrom: false
    nostream: false
```

### patronictl show-config

```yaml
failsafe_mode: false
loop_wait: 10
maximum_lag_on_failover: 1048576
postgresql:
  parameters: null
  pg_hba:
  - host replication all 127.0.0.1/32 trust
  - host replication all 192.168.0.0/16 trust
  - host all all 192.168.0.0/16 trust
  synchronous_mode: true
  synchronous_mode_strict: true
  synchronous_node_count: 1
  use_pg_rewind: true
  use_slots: true
retry_timeout: 10
ttl: 30
```

### Patroni log files

```shell
may 27 08:35:45 patroni-srv1 patroni[500]: 2025-05-27 08:35:45,430 INFO: no action. I am (patroni-srv1), the leader with the lock
may 27 08:35:55 patroni-srv1 patroni[500]: 2025-05-27 08:35:55,426 INFO: no action. I am (patroni-srv1), the leader with the lock
may 27 08:36:05 patroni-srv1 patroni[500]: 2025-05-27 08:36:05,426 INFO: no action. I am (patroni-srv1), the leader with the lock
may 27 08:36:15 patroni-srv1 patroni[500]: 2025-05-27 08:36:15,425 INFO: no action. I am (patroni-srv1), the leader with the lock
may 27 08:36:25 patroni-srv1 patroni[500]: 2025-05-27 08:36:25,470 INFO: no action. I am (patroni-srv1), the leader with the lock
may 27 08:36:35 patroni-srv1 patroni[500]: 2025-05-27 08:36:35,426 INFO: no action. I am (patroni-srv1), the leader with the lock
may 27 08:36:45 patroni-srv1 patroni[500]: 2025-05-27 08:36:45,425 INFO: no action. I am (patroni-srv1), the leader with the lock
```

### PostgreSQL log files

```shell
N\A
```

### Have you tried to use GitHub issue search?

- [x] Yes
