### ISSUE TITLE
Patroni 4.0.5 Cascade Replication Configuration with Synchronous Standby Recovery Causes Write Blocking

### ISSUE THREAD

**Issue by zourenli** [patroni/patroni#3369]
### What happened?

Description

Scenario Configuration
Three-node Patroni cluster setup:
Node1, Node2, Node3 (primary)
Node2 configured as synchronous standby
Node1 tagged with replicatefrom: node2 (cascade replication)
Global Patroni configuration:
synchronous_mode: true
synchronous_node_count: 2

Steps to Reproduce
Shutdown Node2 server (hard stop)
Patroni detects Node2 failure, demotes it to asynchronous, and eventually removes it from the cluster
Node1 is promoted to synchronous standby for Node3 (primary)
Start Node2 server and Patroni service
Node1 rejoins the cluster and follows Node2 per tag configuration (cascade replication restored)
Node2 is re-established as synchronous standby for Node3

Issue: PostgreSQL primary (Node3) incorrectly configures both Node1 and Node2 as synchronous standbys, causing write transactions to block indefinitely
synchronous_standby_names = '2 (node1,node2)'
Expected Behavior
When Node1 is configured as a cascade standby of Node2, PostgreSQL primary should only consider Node2 as a synchronous standby to maintain consistency in the replication path. Synchronous replication configuration should reflect the actual replication topology:

Node3 (primary) → Node2 (synchronous standby) → Node1 (cascade standby)

### How can we reproduce it (as minimally and precisely as possible)?

Here's a **minimal, precise reproduction steps** section you can include in the GitHub issue to help developers replicate the problem:

**Reproduction Steps**  
1. **Initial Cluster Setup**  
   - Deploy a 3-node Patroni cluster (Node1, Node2, Node3) with PostgreSQL 14.10  
   - Configure etcd 3.5.21 as DCS  
   - Global Patroni configuration:  
     ```yaml  
     synchronous_mode: true  
     synchronous_node_count: 2  
     ```  
   - Node-specific configurations:  
     - Node3: No special tags (primary)  
     - Node2: No special tags (serves as initial synchronous standby)  
     - Node1: Add tag `replicatefrom: node2`  

2. **Verify Initial Topology**  
   - Confirm cluster is healthy with Node3 as primary  
   - Check `synchronous_standby_names` on Node3 shows Node2 as synchronous standby  
   - Validate replication flow:  
     ```  
     Node3 (primary) → Node2 (synchronous standby) → Node1 (cascade standby)  
     ```  

3. **Trigger Failure Scenario**  
   - **Step 1**: Stop Node2 server (hard shutdown, e.g., `systemctl stop patroni && poweroff`)  
   - **Wait** for Patroni to detect Node2 failure (monitor logs for demotion messages)  
   - **Verify**: Node1 is promoted to synchronous standby for Node3  
     - Check Node3 logs for:  
       ```log  
       INFO: Assigning synchronous standby status to ['node1']  
       ```  

4. **Recover Node2**  
   - **Step 2**: Start Node2 server  
   - **Step 3**: Start Patroni service on Node2 (`systemctl start patroni`)  
   - **Wait** for Node2 to rejoin the cluster and sync with Node3  

5. **Observe Failure**  
   - **Monitor Node3 logs** during Node2 recovery. Look for:  
     ```log  
     INFO: Assigning synchronous standby status to ['node1', 'node2']  
     ```  
   - **Trigger write operations** on Node3 (e.g., `INSERT INTO test VALUES (1);`)  
   - **Result**: Writes will block indefinitely due to incorrect synchronous standby configuration  

**Key Observations During Reproduction**  
- The issue **may not occur immediately** on the first try. Repeat steps 3-5 2-3 times if needed  
- Timing is critical:  
  - Faster Node2 recovery increases probability of misconfiguration  
  - Slower recovery may allow Patroni to self-correct  
- Check `pg_stat_replication` on Node3 during failure:  
  ```sql  
  SELECT application_name, sync_state FROM pg_stat_replication;  
  -- Expected: Only Node2 should be 'sync'  
  -- Actual: Both Node1 and Node2 may show as 'sync' during failure  
  ```  

This minimal reproduction focuses on the critical failure path while excluding unnecessary complexity. Let me know if you need further refinements!

### What did you expect to happen?

**Expected Behavior**  
When Node1 is configured as a **cascade standby** of Node2 (via `replicatefrom: node2`), PostgreSQL should **only consider Node2 as a synchronous standby** for Node3 (primary). The replication topology and synchronous configuration should reflect the actual data flow:  

```
Node3 (primary) → Node2 (synchronous standby) → Node1 (cascade standby)
```

**Specific Expectations**:  
1. **Synchronous Standby Configuration**:  
   - `synchronous_standby_names` on Node3 should **never include Node1** when Node1 is replicating from Node2  
   - Patroni should dynamically update synchronous standbys based on the **active replication topology**, not just node presence  

2. **Write Transaction Behavior**:  
   - Write transactions on Node3 should wait for confirmation only from Node2 (the direct synchronous standby)  
   - Node1's replication status should be irrelevant to transaction commit semantics, as it receives data via Node2  

3. **State Transition Logic**:  
   - When Node2 recovers and rejoins the cluster:  
     - Node1 should automatically resume replicating from Node2 (per `replicatefrom` tag)  
     - Patroni should **demote Node1 from synchronous status** on Node3  
     - Node3 should reconfigure `synchronous_standby_names` to include only Node2  

4. **Logging Consistency**:  
   - Node3 logs should show clean transitions between synchronous standbys:  
     ```log  
     INFO: Assigning synchronous standby status to ['node2']  # After Node2 recovery  
     ```  
   - No intermediate states where both Node1 and Node2 are incorrectly marked as synchronous standbys  

**Why This Matters**  
- **Data Consistency**: Synchronous replication ensures write transactions are durable on at least one standby before committing. Misconfigured synchronous standbys can violate this guarantee.  
- **Availability**: Write blocking occurs when the primary waits for acknowledgments from nodes that aren’t part of the direct replication path.  
- **Topology Integrity**: Patroni should accurately reflect the operational replication hierarchy in its metadata and PostgreSQL configuration.

### Patroni/PostgreSQL/DCS version

Patroni Version: 4.0.5
PostgreSQL Version: 14.10
DCS Type/Version: etcd 3.5.21
OS: Red Hat 1.23.4-1.el9 linux/amd64

### Patroni configuration file

```yaml
scope: patroni_cluster
namespace: /patroni/
name: node1

restapi:
  listen: 10.211.55.97:8008
  connect_address: 10.211.55.97:8008

etcd3:
  hosts: 10.211.55.98:2379,10.211.55.100:2379,10.211.55.101:2379

#zookeeper:
#  hosts: ['192.168.31.101:2181', '192.168.31.102:2181', '192.168.31.103:2181']

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    maximum_lag_on_syncnode: -1
    primary_start_timeout: 300
    synchronous_mode: false
    synchronous_mode_strict: false
    failsafe_mode: true
    postgresql:
      use_pg_rewind: true
      parameters:
        wal_level: replica
        hot_standby: "on"
        max_connections: 100
        max_worker_processes: 8
        max_replication_slots: 10
        max_prepared_transactions: 0
        max_locks_per_transaction: 64
        wal_log_hints: "on"
        track_commit_timestamp: "off"
        wal_keep_size: 5000
        max_wal_senders: 10
        max_replication_slots: 10
        archive_mode: "off"
        archive_timeout: 1800s
        logging_collector: "on"

postgresql:
  listen: 10.211.55.97:5432
  connect_address: 10.211.55.97:5432
  data_dir: /data/pgsql
  bin_dir: /usr/local/pgsql14/bin

  authentication:
    replication:
      username: postgres
      password: postgres
    superuser:
      username: postgres
      password: postgres
    rewind:
      username: postgres
      password: postgres

  pg_hba:
  - local   all             all                                     trust
  - host    all             all             0.0.0.0/0               trust
  - host    all             all             ::1/128                 trust
  - local   replication     all                                     trust
  - host    replication     all             0.0.0.0/0               trust
  - host    replication     all             ::1/128                 trust

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
    replicatefrom: node2

log:
  level: DEBUG
  traceback_level: INFO
  dir: /data/hac

watchdog:
  mode: off
```

### patronictl show-config

```yaml
loop_wait: 10
maximum_lag_on_failover: 1048576
maximum_lag_on_syncnode: -1
postgresql:
  parameters:
    archive_mode: 'off'
    archive_timeout: 1800s
    hot_standby: 'on'
    max_connections: 100
    max_locks_per_transaction: 64
    max_prepared_transactions: 0
    max_replication_slots: 10
    max_wal_senders: 10
    max_worker_processes: 8
    track_commit_timestamp: 'off'
    wal_keep_size: 5000
    wal_level: replica
    wal_log_hints: 'on'
  use_pg_rewind: true
remove_data_directory_on_rewind_failure: true
retry_timeout: 3
synchronous_mode: true
synchronous_mode_strict: false
synchronous_node_count: 2
ttl: 30
```

### Patroni log files

```shell
2025-06-03 09:52:07,649 INFO: Lock owner: node3; I am node3
2025-06-03 09:52:07,656 INFO: Updating synchronous privilege temporarily from ['node2'] to []
2025-06-03 09:52:07,660 INFO: Assigning synchronous standby status to []
2025-06-03 09:52:07,776 INFO: no action. I am (node3), the leader with the lock
2025-06-03 09:52:17,663 INFO: no action. I am (node3), the leader with the lock
2025-06-03 09:52:27,664 INFO: no action. I am (node3), the leader with the lock
2025-06-03 09:52:37,655 INFO: no action. I am (node3), the leader with the lock
2025-06-03 09:52:47,650 INFO: Lock owner: node3; I am node3
2025-06-03 09:52:47,656 INFO: Assigning synchronous standby status to ['node1']
2025-06-03 09:52:49,775 INFO: Synchronous standby status assigned to ['node1']
2025-06-03 09:52:49,781 INFO: no action. I am (node3), the leader with the lock
2025-06-03 09:52:57,657 INFO: no action. I am (node3), the leader with the lock
2025-06-03 09:53:07,661 INFO: no action. I am (node3), the leader with the lock
2025-06-03 09:53:17,653 INFO: no action. I am (node3), the leader with the lock
2025-06-03 09:53:27,653 INFO: no action. I am (node3), the leader with the lock
2025-06-03 09:53:37,652 INFO: Lock owner: node3; I am node3
2025-06-03 09:53:37,659 INFO: Assigning synchronous standby status to ['node1', 'node2']
2025-06-03 09:53:39,784 INFO: Synchronous standby status assigned to ['node2']
2025-06-03 09:53:39,789 INFO: no action. I am (node3), the leader with the lock
```

### PostgreSQL log files

```shell
synchronous_standby_names = '2 (node1,node2)'
```

### Have you tried to use GitHub issue search?

- [x] Yes
