### ISSUE TITLE
patroni can't use etcd v3.6+

### ISSUE THREAD

**Issue by amorozov** [patroni/patroni#3382]
### What happened?

Currently patroni uses [etcd v2 HTTP API](https://github.com/patroni/patroni/discussions/3381#discussioncomment-13498382). Unfortunately the API is deprecated and finally [removed from etcd v3.6](https://github.com/etcd-io/etcd/issues/17009#issue-2008448884).

So it seems that the switch to the new API is inevitable.

### How can we reproduce it (as minimally and precisely as possible)?

Install etcd v3.6

Get a line in the patroni logs like this:

`Failed to get list of machines from https://10.77.73.212:2383/v2: EtcdException('Bad response : 404 page not found\n'`

### What did you expect to happen?

patroni to use etcd v3.6

### Patroni/PostgreSQL/DCS version

-   Patroni version: 4.0.6-1 (from debian package) 
-   PostgreSQL version: 15
-   DCS (and its version): etcd-3.6.1 

### Patroni configuration file

```yaml
scope: 15/main
name: shard2-master
namespace: shard2

log:
  format: '%(asctime)s %(levelname)s: %(message)s'
  level: INFO
  max_queue_size: 1000
  traceback_level: ERROR
  type: plain

restapi:
  connect_address: 127.0.1.1:8008
  listen: 127.0.1.1:8008

etcd:                     # Конфигурация DCS (etcd/Consul/ZooKeeper)
  hosts: ["10.77.73.212:2383", "10.77.73.213:2383", "10.77.73.210:2383"]
  protocol: 'https'
  cacert: '/usr/local/share/ca-certificates/easy-rsa-local.crt'
  cert: '/etc/patroni/certs/patroni-infra0.crt'
  key: '/etc/patroni/certs/patroni-infra0.key'

# The bootstrap configuration. Works only when the cluster is not yet initialized.
# If the cluster is already initialized, all changes in the `bootstrap` section are ignored!
bootstrap:
  # This section will be written into <dcs>:/<namespace>/<scope>/config after initializing
  # new cluster and all other cluster members will use it as a `global configuration`.
  # WARNING! If you want to change any of the parameters that were set up
  # via `bootstrap.dcs` section, please use `patronictl edit-config`!
  dcs:
    loop_wait: 10
    retry_timeout: 10
    ttl: 30
    postgresql:
      parameters:
        TimeZone: Etc/UTC
        ac_audit_destination: logfile
        ac_audit_log_only_failures: 'off'
        ac_audit_mode: internal
        ac_auto_adjust_macs: 'off'
        ac_caps_ttl: '10'
        ac_debug_print: 'off'
        ac_enable_admin_options: 'off'
        ac_enable_copy_to_file: 'on'
        ac_enable_dblink_mac: 'off'
        ac_enable_grant_options: 'off'
        ac_enable_maclabels_on_files: 'off'
        ac_enable_sequence_ccr: 'on'
        ac_enable_truncate: 'on'
        ac_enable_trusted_owner: 'on'
        ac_forbid_copy_from_program: 'off'
        ac_ignore_maclabel: 'off'
        ac_ignore_server_maclabel: 'on'
        ac_ignore_socket_maclabel: 'on'
        ac_integrity_check: NONE
        ac_integrity_naptime: 30s
        ac_integrity_processes: '8'
        ac_kiosk_mode: 'off'
        ac_log_stmt_length: '100'
        ac_rand_free_memory: 'off'
        ac_restrict_sh_libs_location: 'off'
        ac_wipe_buffers: 'off'
        ac_wipe_files: 'off'
        ac_wipe_pages: 'off'
        default_text_search_config: pg_catalog.english
        dynamic_shared_memory_type: posix
        effective_cache_size: 100GB
        external_pid_file: /var/run/postgresql/15-main.pid
        from_collapse_limit: '20'
        hot_standby: 'on'
        join_collapse_limit: '20'
        lc_messages: en_US.UTF-8
        lc_monetary: en_US.UTF-8
        lc_numeric: en_US.UTF-8
        lc_time: en_US.UTF-8
        log_checkpoints: 'on'
        log_connections: 'on'
        log_disconnections: 'on'
        log_destination: stderr
        log_directory: pg_log
        log_filename: postgresql-%a.log
        log_line_prefix: '%m [%p] %q%u@%d '
        log_min_duration_statement: 1000
        log_rotation_age: 1d
        log_rotation_size: '0'
        log_temp_files: '0'
        log_timezone: Etc/UTC
        log_truncate_on_rotation: 'on'
        logging_collector: 'on'
        maintenance_work_mem: 16GB
        max_connections: '500'
        max_files_per_process: '8000'
        max_locks_per_transaction: '150'
        max_prepared_transactions: '0'
        max_replication_slots: '10'
        max_wal_senders: '10'
        max_wal_size: 1GB
        max_worker_processes: '16'
        max_parallel_workers: '16'
        max_parallel_workers_per_gather: '6'
        min_wal_size: 80MB
        shared_buffers: 77322MB
        shared_preload_libraries: 'pg_stat_statements'
        ssl: 'on'
        ssl_cert_file: /etc/ssl/certs/ssl-cert-snakeoil.pem
        ssl_key_file: /etc/ssl/private/ssl-cert-snakeoil.key
        temp_buffers: 256MB
        track_activity_query_size: 16384
        track_commit_timestamp: 'off'
        track_io_timing: 'on'
        unix_socket_directories: /var/run/postgresql
        wal_buffers: 128MB
        wal_keep_segments: '128' 
        wal_keep_size: 1024MB
        wal_level: logical
        wal_log_hints: 'off'
        work_mem: 20480MB
      use_slots: true

postgresql:
  authentication:
    replication:
      password: 'patroni_password'
      username: 'patroni_replication'
    superuser:
      password: 'patroni_password'
      username: 'patroni_super'
    rewind:
      password: 'patroni_password'
      username: 'patroni_rewind'
  bin_dir: /usr/lib/postgresql/15/bin
  connect_address: 127.0.1.1:5432
  data_dir: /var/lib/postgresql/15/main
  listen: '*:5432'
  create_replica_methods:
    - basebackup
  basebackup:
    max-rate: 100M
    checkpoint: fast
  parameters:
    config_file: /var/lib/patroni/postgresql/15/main/postgresql.conf
    hba_file: /var/lib/patroni/postgresql/15/main/pg_hba.conf
    ident_file: /var/lib/patroni/postgresql/15/main/pg_ident.conf
slots:
  shard2:
    type: 'logical'
    database: 'server_db'
    plugin: pgoutput

tags:
  clonefrom: true
  failover_priority: 1
  noloadbalance: false
  nostream: false
  nosync: false
```

### patronictl show-config

```yaml
$ patroni show-config 
Config is empty.
```

### Patroni log files

```shell
Jun 18 04:34:28 cn-msk-asm2pp-app03 patroni[256799]: 2025-06-18 04:34:28,518 ERROR: Failed to get list of machines from https://10.77.73.212:2383/v2: EtcdException('Bad response : 404 page not found\n')
Jun 18 04:34:28 cn-msk-asm2pp-app03 patroni[256799]: 2025-06-18 04:34:28,518 INFO: waiting on etcd
Jun 18 04:34:33 cn-msk-asm2pp-app03 patroni[256799]: 2025-06-18 04:34:33,546 ERROR: Failed to get list of machines from https://10.77.73.213:2383/v2: EtcdException('Bad response : 404 page not found\n')
Jun 18 04:34:33 cn-msk-asm2pp-app03 patroni[256799]: 2025-06-18 04:34:33,569 ERROR: Failed to get list of machines from https://10.77.73.210:2383/v2: EtcdException('Bad response : 404 page not found\n')
Jun 18 04:34:33 cn-msk-asm2pp-app03 patroni[256799]: 2025-06-18 04:34:33,593 ERROR: Failed to get list of machines from https://10.77.73.212:2383/v2: EtcdException('Bad response : 404 page not found\n')
Jun 18 04:34:33 cn-msk-asm2pp-app03 patroni[256799]: 2025-06-18 04:34:33,593 INFO: waiting on etcd
Jun 18 04:34:38 cn-msk-asm2pp-app03 patroni[256799]: 2025-06-18 04:34:38,621 ERROR: Failed to get list of machines from https://10.77.73.213:2383/v2: EtcdException('Bad response : 404 page not found\n')
Jun 18 04:34:38 cn-msk-asm2pp-app03 patroni[256799]: 2025-06-18 04:34:38,647 ERROR: Failed to get list of machines from https://10.77.73.210:2383/v2: EtcdException('Bad response : 404 page not found\n')
Jun 18 04:34:38 cn-msk-asm2pp-app03 patroni[256799]: 2025-06-18 04:34:38,671 ERROR: Failed to get list of machines from https://10.77.73.212:2383/v2: EtcdException('Bad response : 404 page not found\n')
Jun 18 04:34:38 cn-msk-asm2pp-app03 patroni[256799]: 2025-06-18 04:34:38,672 INFO: waiting on etcd
```

### PostgreSQL log files

```shell
-
```

### Have you tried to use GitHub issue search?

- [x] Yes
